prometheus/node_exporter

Makefile

This makes a simple 'make' work on a machine without golang,
and doesn't pull in libraries from elsewhere.
Bump golang version, 1.3 doesn't do http basic auth.

Make build hermetic.

---

collector/textfile.go
node_exporter.go

This allows static metrics (e.g. an attributes collector replacement),
and cronjobs to expose stats by echoing into a file in the text exposition format.
For example:
echo "my_metric 123" > mycronjob.prom.$$
mv mycronjob.prom.$$ mycronjob.prom
This entire repo needs docs, I'll do them up separately. We should also look at moving the megacli and lastlogin collectors over to this as they're creating processes. Attributes is superseded by this, which'll also let us remove the config file.
@discordianfish @juliusv 
Depends on #34

Add text file exporter

---

Makefile

The download link was missing the suffix for OS X. This is taken straight from prometheus' Makefile.
Also using the golang.org instead of directly taking it from the CDN seems cleaner.

fix go tarball download for OS X, use redirect from golang.org

---

collector/stat.go

Fixes issue described in #38
/proc/stat reports a blank line which needs to be ignored.
Old kernels misses one CPU time field, this needs to be ignored too.

Fixed panic when parsing /proc/stat on 2.6.32-25-pve

---

collector/diskstats.go

Whatever virtualization bigv.io use, it exposes block devices as /dev/vda{,1,2}. As we only care about stats for the whole block devices, and not partitions, add vd? partitions to ignore list.
I'm unsure whether we should also ignore /dev/fd? and /dev/sr?. There is a case that the latter might still be useful, but the former is really dubious. Thoughts?
@juliusv @brian-brazil

Also ignore vda1 and friends

---

README.md
collector/diskstats.go
collector/filesystem.go
collector/ntp.go
collector/textfile.go

This puts all collector-specific flags into their own namespace under
"collector.<collector-name>", and moves from camel case to dashes, which
is the standard in Prometheus land now.

Make collector-specific flags consistent with others.

---

README.md
collector/fixtures/tcpstat
collector/tcpstat.go
collector/tcpstat_test.go

This collector expose following metrics:
* Number of TCP ESTABLISHED connections
* Number of TCP LISTEN ports
* Number of TCP SYN_SENT state connections
* Number of TCP SYN_RECV state connections
* Number of TCP FIN_WAIT1 state connections
* Number of TCP FIN_WATI2 state connections
* Number of TCP TIME_WAIT state connections
* Number of TCP CLOSE state connections
* Number of TCP CLOSE_WAIT state connections
* Number of TCP LAST_ACK state connections
* Number of TCP CLOSING state connections

Add TCP state collector

---

Makefile
README.md
node_exporter.go

The glog flag interface is neither intuitive nor consistent with the rest of our flags unfortunately. We also seem to use both the fmt and glog library for logging. What do people prefer?
@brian-brazil @discordianfish

Document logging

---

README.md
collector/fixtures/net/ip_vs
collector/fixtures/net/ip_vs_result.txt
collector/fixtures/net/ip_vs_stats
collector/ipvs.go
collector/ipvs_test.go

This collector exposes IPVS status from `/proc/net/ip_vs` and stats from
`/proc/net/ip_vs_stats`.
Note that it is _not_ tested with IPv6, YMMV.

Add IPVS stats collector.

---

node_exporter.go

This makes the `-collectors.print` output easier to read.

Sort collector names.

---

CHANGELOG.md
Makefile

This release adds the IPVS collector and removes the deprecated
attributes collector.
@juliusv @discordianfish not sure if I'm doing this right?

Cut release 0.9.0

---

collector/filesystem.go

Collects more information for labelling scraped filesystems with the device
and fstype. This is useful for setting alerts which should change based on
filesystem type, or for filtering out shared mounts such as with NFS volumes.

Add device,fstype collection to the filesystem exporter.

---

collector/netdev.go
collector/netdev_test.go

At DigitalOcean we want to be able to ignore some network devices. We have machines that can have hundreds of virtual network devices from our guest virtual machines that get exposed on the host. This can explode the number of metrics we gather out of node_exporter. The metrics we really want from node_exporter are for the host machine, not the guests.
I followed similar naming guide as the filesystem exporter and diskstats. The default regexp provided to flags matches the "" (empty-string) device, so nobody should be affected by this change.
I pass the compiled `*regexp.Regexp` into the parser for easier testability.
It seems somebody brought up wanting this ability before:
https://github.com/prometheus/node_exporter/issues/60

Allows netdev devices to be ignored

---

collector/netstat_linux.go
collector/netstat_linux_test.go

This is the naive implementation for #59. I thought of a few other approaches, mainly looping over a list of files and doing the merge of maps in getStats(). Any other approach would be longer though and I'm not sure of its benefit given the limited and well defined set of inputs (/proc/net/netstat, /proc/net/snmp). I'm happy to hear other opinions if you think this can be refactored a bit more. @matthiasr

Add support for stats from /proc/net/snmp as well.

---

collector/fixtures/sockstat
collector/sockstat_linux.go
collector/sockstat_linux_test.go
node_exporter.go

Implements a collector for the /proc/net/sockstat proc file.  Collects the following values:
`sockets_used` number of sockets in use
`tcp_inuse` number of TCP sockets in use
`tcp_orphan` number of orphaned TCP sockets
`tcp_tw` the time wait for new TCP sockets
`tcp_alloc` the total number of allocated TCP sockets
`tcp_mem` the number of pages consumed by TCP sockets (1 page = 4096 bytes)
`tcp_mem_bytes` the number of bytes consumed by TCP sockets (# of pages * page size)
`udp_inuse` number of UDP sockets in use
`udp_mem` the number of pages consumed by UDB sockets (1 page = 4096 bytes)
`udp_mem_bytes` the number of bytes consumed by UDP sockets (# of pages * page size)
`udplite_inuse` number of UDPLITE sockets in use
`raw_inuse` number of RAW sockets in use
`frag_inuse` number of IP …

Implementation of /proc/net/sockstat collector

---

collector/sockstat_linux_test.go

Updated the sockstat test case wording to report what was actually tested, and not "sockets used" for all test cases.

Fixed sockstat test wording

---

collector/uname_linux.go
node_exporter.go

This creates a single metric like:
```
node_uname_info{domainname="(none)",machine="x86_64",nodename="desktop",release="3.16.0-48-generic",sysname="Linux",version="#64~14.04.1-Ubuntu SMP Thu Aug 20 23:03:57 UTC 2015"} 1
```

Add Linux uname collector.

---

README.md
collector/fixtures/mdstat
collector/mdadm.go
collector/mdadm_test.go
node_exporter.go

Implementing a collector able to parse /proc/mdstat and exposing metrics regarding the state of the md-devices present.
exposed metrics atm:
* `md_is_active` indicates whether the device in question is marked as active
* `md_disks_total` indicates the number of disks the device consists of
* `md_disks_active` indicates how many of those devices are active (if lower than `md_disks_total` the devic should be considered degraded)
* `md_blocks_total` indicates the number of blocks the device contains
* `md_blocks_synced` indicates the number of blocks in sync
Comments, suggestions etc.?

adding collector for linux-mdadm-software-raid

---

AUTHORS.md

filled the author's file with the contributors listed via GitHub.
Mailadresses are, if available, taken from the respective GitHub-profiles, otherwise from the git log. The latter case is marked with a line note.
for names without addresses no address could be found on github or in the git log.

filled authors

---

collector/netdev_freebsd.go
collector/netdev_linux.go
collector/netdev_linux_test.go

Similarly to #117, I have modified the netdev collectors to  use ConstMetrics that are forgotten just after they are used. This would solve #62.
In this case, the change is more intrusive, as I tried to make the code more readable by changing the way the stats structure is created (from direction:device:stat to device:direction_stat).
Again, I modified the freebsd quite blindly. Any suggestions on how to test that are welcome.

Revamp the netdev collector to use throw-away ConstMetrics.

---

collector/filesystem_common.go
collector/filesystem_freebsd.go
collector/filesystem_linux.go

Following up on #61, this PR rewrites a big chunk of the filesystem exporter to use ConstMetrics that are forgotten just after they are used. I have done the same changes in the freebsd version, but I have no way of testing them (in fact, I don't even know how to tell go to compile it for sanity checking), but I am confident it should work, as the changes are literally the same.

Revamp the filesystem collector to use throw-away ConstMetrics.

---

collector/diskstats_linux.go
collector/filefd_linux.go
collector/filesystem_linux.go
collector/interrupts_linux.go
collector/ipvs.go
collector/ipvs_test.go
collector/loadavg_linux.go
collector/mdadm.go
collector/meminfo_linux.go
collector/netdev_linux.go
collector/netstat_linux.go
collector/procpath.go
collector/sockstat_linux.go
collector/stat_linux.go
collector/tcpstat_linux.go

Remove all hardcoded references to `/proc`. For all collectors that do
not use `github.com/prometheus/procfs` yet, provide a wrapper to
generate the full paths.
Reformulate help strings, errors and comments to remove absolute
references to `/proc`.
This is a breaking change: the `-collector.ipvs.procfs` flag is removed
in favor of the general flag. Since it only affected that collector it
was only useful for development, so this should not cause many issues.

Add flag to change the location of the procfs.

---

collector/cpu_freebsd.go

When I reviewed the cpu metrics, on my FreeBSD machine, I noticed the cpu metrics were not in seconds.  This code works for me, but the documentation for this is not great -- this is what I found:
* [sys/kern/kern_clock.c](https://github.com/freebsd/freebsd/blob/master/sys/kern/kern_clock.c#L361)
* [manpage for kvm_getcptime](https://www.freebsd.org/cgi/man.cgi?query=kvm_getcptime&sektion=3&manpath=FreeBSD+7.1-RELEASE)

converted freebsd cpu metrics to seconds

---

collector/stat_linux.go

Comment seems to be copied from netdev_linux.go, where it is correct.

fix copy-paste error in comment

---

collector/filesystem_freebsd.go

Good day.  I deleted a line -- that appears to allow this code to compile cleanly.
````
$ $ uname -a
FreeBSD prod.example.org 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
$ gmake GO_VERSION=1.5
GOPATH=/usr/home/prodbin/gocode/src/github.com/prometheus/node_exporter/.build/gopath /usr/local/bin/go get -d
touch dependencies-stamp
GOPATH=/usr/home/prodbin/gocode/src/github.com/prometheus/node_exporter/.build/gopath /usr/local/bin/go build -ldflags "-X main.Version=0.11.0" -o node_exporter
cc: warning: argument unused during compilation: '-pthread'
/usr/home/prodbin/gocode/src/github.com/prometheus/node_exporter/.build/gopath/src/github.com/prometheus/node_exporter/collector/filesystem_freebsd.go …
```

Fixed minor compile time error

---

collector/uname_linux.go
collector/uname_linux_int8.go
collector/uname_linux_uint8.go

The syscall.Utsname struct under ppc64/ppc64le uses uint8 type instead
of int8.
I was able to cross-compile node_exporter for ppc64 that way. Not tested due to lack of hardware. `GOARCH=ppc64 make`.
@SuperQ @fabxc

Fix uname collector for ppc64 architectures

---

collector/filesystem_linux.go

Current behaviour throws away all stats on any Statfs error. In practice
this is not useful. This turns such errors into debug log messages -
though silently ignoring them seems even more valid to me.
(note this is a suggested partial fix for issue #81 )

Make filesystem collector more robust.

---

Makefile.COMMON

I updated Makefile.COMMON in blackbox_exporter based on the version here. I've since learned of the util project so sent this in to bring it up to date.

Update with latest Makefile.COMMON from util.

---

collector/fixtures/e2e-output.txt
collector/loadavg_linux.go
collector/loadavg_linux_test.go

Export of 5m and 15m load average on linux. 
I had to open a new pull request because I deleted my previous fork.

Add load5 and load15 to linux load metric

---

collector/ntp.go

@grobie @juliusv Hi! I've made a huge mistake in my previous PR #146 . Using flag in `init()` function of `ntp` collector definitely is not a good idea.

Do not use flag before flag.Parse() was called

---

collector/netdev_common.go
collector/netdev_linux.go
collector/netdev_openbsd.go

i removed transmit_drop (ifi_oqdrops) because OpenBSD lacks this field in struct if_data.

collector: add openbsd support for netdev

---

collector/interrupts_common.go

As OS X doesn't have it's own interrupts provider, don't build
interrupts_common on OS X as well. Otherwise build fails, because
interrupts_common depends on variables provided by platform-specific
files.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>

Fix compilation on OS X

---

collector/ntp.go

'go vet' spotted a missing argument to fmt.Errorf function in collectors/ntp.go

Add missing argument to fmt.Errorf function in 'ntp' collector

---

collector/diskstats_linux.go
collector/diskstats_linux_test.go
collector/fixtures/e2e-output.txt

This is only calculated for raw devices, since determinining the parent
device for partitions would require additional work, and partitions are
excluded from collection by default.

Calculate Linux disk bytes read/written based on sector size

---

Makefile
collector/version.go
node_exporter.go

When dealing with a larger number of servers, it's easy to lose track what version of the node_exporter is running on which machine. Especially because sometimes metrics or labels get renamed from version to version (e.g. filesystem => mountpoint), it's rather important to have a way to ensure all servers are running the expected version.
Currently the exporter doesn't provide a way to retrieve its version (except from the logs), so I added a new `/version` endpoint, which does simply return the version as plain text.
This would allow deployment scripts to verify that the running version actually matches the expected one and fail otherwise. It would also make it possible to get an overview over all the different node_exporter versions running on my servers and find out which one need to …

Expose version and other build information as metric similar to Prometheus itself

---

collector/interrupts_common.go

There is no interrupts_freebsd.go implementation yet.
Compilation fails currently:
```
collector/interrupts_common.go:39: undefined: interruptLabelNames
```

Fix compilation on FreeBSD. Refs #139

---

collector/interrupts_common.go
collector/loadavg.go
node_exporter.go

Removes unused signal handlers left over from signal based collection
and block the non windows-relevant collectors loadavg and interrupts.
Signal based collection removed in 1c17481a4289a81b70e482fcf1d4a432da87c5de over a year ago.
@brian-brazil @discordianfish @grobie

Build cleanly under windows.

---

README.md
collector/vmstat.go
node_exporter.go

this adds a vmstat collector to node_exporter  #185 
in /proc/vmstat the most values are simple counters[1], however some are not, i blacklisted these values unitl i found a good way to deal with.
```
counterBlacklist := []string{"nr_dirty", "nr_writeback", "nr_unstable", "nr_page_table_pages","nr_mapped ,nr_slab"}
```
please review
[1] http://www.linuxinsight.com/proc_vmstat.html

Add vmstat collector

---

end-to-end-test.sh

Reduce merge conflicts by breaking up the list into a multi-line string.

Re-arrange collectors list in end-to-end test

---

collector/filefd_linux.go

fix block nesting bug causing filefd values never be updated post initial call

fix block nesting bug

---

collector/conntrack_linux.go
collector/helper.go

Entry collector uses readUintFromFile() function which is defined by
conntrack collector. Thus, it is impossible to build node_exporter w/o
contract collector. Fix this by factoring out the function into
helper.go file.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>

Fix build w/o conntrack collector

---

collector/filesystem_bsd.go
collector/filesystem_common.go
collector/filesystem_linux.go

Adds a metric for indicating filesystem read-only status.
node_filesystem_readonly_bool is 1 when the filesystem is read-only, 0 when it is read-write.
Closes #147 
Implemented but not tested for BSD as well.

Add filesystem read-only metric.

---

Makefile.COMMON

Go expects to build a project from a location like
`.../src/github.com/prometheus/node_exporter`.
Well, would need to be backported to prometheus/utils. Unsure about it, feels ugly. Any suggestions?
@juliusv @matthiasr @fabxc

Ensure make executes go commands in the right dir structure

---

collector/fixtures/sys/devices/system/node/node0/meminfo
collector/fixtures/sys/devices/system/node/node1/meminfo
collector/meminfo_numa_linux.go

It turns out, on some kernels (notably - CentOS6) there is an empty line
inserted at the beginning of /sys/devices/system/node/node*/meminfo
files.  The leads to node_exporter crash on such kernels.
Fix this by checking for empty string first.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>

meminfo_numa: fix crash on CentOS 6 kernel

---

collector/diskstats_linux.go

-Fix a small typo in the error message for sectors written.

fix a small typo in an error message

---

collector/filesystem_bsd.go

When compiling `20ecedd0b4c983bd7b88f97cd7a21461988a6c12` with GNU make (`gmake`) on FreeBSD 10.2-RELEASE, I get the following error:
```
collector/filesystem_bsd.go:60: non-bool mnt[i].f_flags & MNT_RDONLY (type C.uint64_t) used as if condition
Makefile.COMMON:85: recipe for target 'node_exporter' failed
gmake: *** [node_exporter] Error 2
```
This problem is fixed by this patch.

Fix compile error on FreeBSD

---

collector/cpu_freebsd.go
collector/filesystem_bsd.go

This removes the requirement to run node_exporter as root / with read
access to /dev/kmem in order to get cpu usage statistics.

Re-implement CPU metrics collection through sysctls.

---

README.md
node_exporter.go

As of 1fc84e2fb69ee3d1f063399b00a6284fc8e27cb8 it does not require root anymore.
The CPU collector has been tested for a day on FreeBSD with frequent polling (30s) and does not show memory leaks, reliability or performance issues.

Add FreeBSD 'cpu' exporter to default collectors.

---

collector/systemd_linux.go

This CL adds a new flag "-collector.systemd.private" which can be used to instruct the systemd collector to connect directly to systemd. This is useful for servers which don't have dbus installed (security concerns etc.)

systemd-collector: support private/direct connections without dbus

---

.travis.yml

This is
[deprecated](https://groups.google.com/forum/#!topic/golang-announce/qu_rAphYdxY)
and no longer necessary as we don't try to build with Go 1.4 anyway.

Stop installing golang.org/x/tools/cmd/vet during Travis build

---

README.md
collector/logind_linux.go
collector/logind_linux_test.go

logind provides a nice interface to find out about the numbers of sessions
on a system; it is used on most Linux distributions, even those which
aren't using systemd.
The exporter exposes the total number of sessions indexed by the following
attributes:
* seat
* type ("tty", "x11", ...)
* class ("user", "greeter", ...)
* remote ("true"/"false")

Add 'logind' exporter

---

collector/cpu_freebsd.go

In short: the slice needn't be that big. MAXCPU is 64 on freebsd, unless you compile a special kernel.
This should fix issue #225. Perhaps @problame can comment?

Fix compilation on freebsd/386

---

collector/netdev_freebsd.go
collector/netdev_freebsd_test.go

As promised, this tests the actual conversion, except the step where we change the type from the ulong to uint64.
Changing the tests to use oldconvert() too makes it fail on freebsd/386 (but I had to reapply this patch to before #207) to get it to compile at all on 386.

Add a unit test for the conversion

---

.gitignore
collector/ntp.go
vendor/github.com/beevik/ntp/CONTRIBUTORS
vendor/github.com/beevik/ntp/README.md
vendor/github.com/beevik/ntp/ntp.go
vendor/vendor.json

Previously the raw time difference was used which includes the network trip time
between the node and the ntp server. This makes setting alerts off the value
troublesome as it depends on the latency as well as the clock offset.
This PR also includes the updated version of the golang ntp library
This closes #243

Use the offset calculation that includes round trip time in the ntp collector

---

collector/filesystem_bsd.go
collector/filesystem_common.go
collector/filesystem_linux.go

This addresses at least some of the comments in #217.
It now compiles on Linux. I don't have any BSD lying around to test with.

Add flag to ignore certain filesystem types (Copy of #217)

---

collector/fixtures/e2e-output.txt
collector/fixtures/proc/mdstat
collector/fixtures/proc/mdstat_invalid
collector/mdadm_linux.go
collector/mdadm_linux_test.go

Fix for https://github.com/prometheus/node_exporter/issues/219

Add support for raid0 devices in mdadm_linux collector.

---

collector/textfile.go

Current the file handler not closed. Only closed by gc. May be has some hidden trouble.
@beorn7

Close file handler in textfile

---

collector/filesystem_bsd.go
collector/filesystem_common.go

Well that was easy :)
The cgo based bsd variant just works on darwin:
```
$ curl -s 192.168.1.104:9100/metrics|grep '/dev/disk1'
node_filesystem_avail{device="/dev/disk1",fstype="hfs",mountpoint="/"} 7.5835293696e+10
node_filesystem_files{device="/dev/disk1",fstype="hfs",mountpoint="/"} 5.8315941e+07
node_filesystem_files_free{device="/dev/disk1",fstype="hfs",mountpoint="/"} 1.8514476e+07
node_filesystem_free{device="/dev/disk1",fstype="hfs",mountpoint="/"} 7.6097437696e+10
node_filesystem_readonly{device="/dev/disk1",fstype="hfs",mountpoint="/"} 0
node_filesystem_size{device="/dev/disk1",fstype="hfs",mountpoint="/"} 2.38862102528e+11
```

Enable *bsd collector on darwin

---

collector/fixtures/proc/net/sockstat_rhe4
collector/sockstat_linux.go
collector/sockstat_linux_test.go

sorry for open a pull request for such a vintage OS, but the change is small and node exporter works reliable there after the patch (with go 1.4.2).
The only difference that caused a parsing error is a missing memory field in the UDP section of sockstat, i made the extraction of udp memory from sockstat optional with this patch.
ps.: just in case someone finds this post in need of  a prometheus node-exporter for RHE4, one also needs a patched [go 1.4.2](https://github.com/mgit-at/go/tree/release-branch.go1.4-rhe4)

sockstat: add support for RHE4

---

collector/fixtures/proc/mdstat
collector/mdadm_linux.go

I have a qnap NAS which inserts tabs in the mdstat file..
This is the actual file from my nas:
Linux dubcube 3.4.6

Fix mdstat tabs parsing

---

README.md
collector/filesystem_bsd.go
collector/filesystem_common.go

Add dragonfly as a compile target.
Sample output from my machine:
```
node_filesystem_avail{device="/dev/serno/6VY96M9D.s1a",fstype="ufs",mountpoint="/boot"} 5.43205376e+08
node_filesystem_avail{device="/pfs/@@-1:00001",fstype="null",mountpoint="/var"} 2.08283615232e+11
node_filesystem_avail{device="/pfs/@@-1:00002",fstype="null",mountpoint="/tmp"} 2.08283615232e+11
node_filesystem_avail{device="/pfs/@@-1:00003",fstype="null",mountpoint="/home"} 2.08283582464e+11
node_filesystem_avail{device="/pfs/@@-1:00004",fstype="null",mountpoint="/usr/obj"} 2.08283615232e+11
node_filesystem_avail{device="/pfs/@@-1:00005",fstype="null",mountpoint="/var/crash"} 2.08283615232e+11
node_filesystem_avail{device="/pfs/@@-1:00006",fstype="null",mountpoint="/var/tmp"} 2.08283615232e+11 …
```

Compile fs stats for dfly

---

collector/fixtures/e2e-output.txt
collector/fixtures/sys/devices/system/node/node0/numastat
collector/fixtures/sys/devices/system/node/node1/numastat
collector/meminfo_numa_linux.go
collector/meminfo_numa_linux_test.go

Read the `numastat` metrics from `/sys/devices/system/node/node*` when
reading NUMA meminfo metrics.
* Update end-to-end test output.
* Add `numastat` metrics as counters.
* Add tests for error conditions.
* Refactor meminfo numa metrics struct
* Refactor meminfoKey into a simple struct of metric data.  This makes it easier to pass slices of metrics around.
* Refactor tests.

Add Linux NUMA "numastat" metrics

---

.promu.yml

Disable linux/{ppc64,ppc64le} until we figure out what is wrong with the
automated build pipeline.
CC @sdurrheimer @EdSchouten This will fix the build.

Disable broken ppc builds

---

collector/cpu_dragonfly.go
collector/cpu_dragonfly_test.go

Hey,
This reports the node cpu time for machines running DragonFlyBSD. It is analogous to `cpu_freebsd.go`, but unfortunately DragonFly required a different implementation.
The code here is heavily influenced by the FreeBSD implementation, as well as this:
https://www.dragonflybsd.org/mailarchive/users/2010-04/msg00056.html
I have a separate implementation that uses creates a go slice from a C array of the double values, instead of how this implementation uses a string, if that is preferred: https://github.com/stuartnelson3/node_exporter/blob/dfly-cpu-doubles/collector/cpu_dragonfly.go
Note:
The units seem to be off by perhaps 3 orders of magnitude. I'm waiting for a response from the DragonFly community as to what the units for the various cpu modes.
**FIXED:** It seems I was using the …

export DragonFlyBSD CPU time

---

README.md
collector/devstat_dragonfly.go

Similar to the FreeBSD implementation, this exports data available from libdevstat. It's unfortunately less granular, but potentially still helpful.
https://www.dragonflybsd.org/cgi/web-man?command=devstat&section=3
Question:
A few of the values returned from `compute_stats` are gauges whose values I believe could be computed with the counter values already exported. Would it be preferred to drop these rates exported by Dragonfly in favor of calculating them with Prometheus?
@matthiasr

Dragonfly devstat

---

collector/uname_linux_int8.go

Just a quick drive-by fix for the linux/mips64 builds so I can export metrics from my EdgeRouter :smile:

mips64 build fix

---

README.md

This adds bind-mounts and ignore flags to Docker example and explains
why it's best run uncontainerized.

Improve Docker documentation

---

text_collector_examples/smartmon.sh

Add a utility to parse the output of `smartctl`.
* Scans all disks.
* Prints metrics for `smartctl --info`.
* Prints metrics for `smartctl --attributes`.

Add text file utility for SMART metrics

---

end-to-end-test.sh

`which` is not installed by default on a base Arch Linux installation:
```
time="2016-12-21T18:35:36+01:00" level=info msg="Listening on 127.0.0.1:16199" source="node_exporter.go:176"
=========================
make: *** [Makefile:36: test-e2e] Fehler 1
Build step 'Shell ausführen' marked build as failure
```
whereas `command` is part of any POSIX shell

Use POSIX "command" instead of non-standard "which"

---

AUTHORS.md
README.md
collector/drbd_linux.go
collector/fixtures/e2e-output.txt
collector/fixtures/proc/drbd
end-to-end-test.sh

In addition to the NFS stats collector, we also wrote a similar one for parsing `/proc/drbd` to extract DRBD replication stats. This allows us to keep an eye on whether our systems are still in sync with each other, the amount of network/disk I/O, etc.

A collector for DRBD

---

text_collector_examples/README.md
text_collector_examples/storcli.py

Collect metrics from the StorCLI utility on the health of MegaRAID
hardware RAID controllers and write them to stdout so that they can be
used by the textfile collector.
We parse the JSON output that StorCLI provides.
Script must be run as root or with appropriate capabilities for storcli
to access the RAID card.
Designed to run under Python 2.7, using the system Python provided with
many Linux distributions.
The metrics look like this:
```
mbostock@host:~$ sudo ./storcli.py
megaraid_status_code 0
megaraid_controllers_count 1
megaraid_emergency_hot_spare{controller="0", model="AVAGOMegaRAIDSASPCIExpressROMB"} 1
megaraid_scheduled_patrol_read{controller="0", model="AVAGOMegaRAIDSASPCIExpressROMB"} 1
megaraid_virtual_drives{controller="0", model="AVAGOMegaRAIDSASPCIExpressROMB"} 1 …
```

Add StorCli text collector example script

---

collector/filesystem_linux.go

node_exporter currently triggers autofs to mount the underlying
filesystem on every scrape. This is undesirable. Better ignore autofs.
The underlying filesystem that autofs mounts will be monitored though,
when the (real) filesystem is mounted.

Ignore autofs filesystems on linux

---

collector/filesystem_common.go
collector/filesystem_linux.go

This metric is the total number of errors occurred when getting stats
for the given device.
This closes #325

Add node_filesystem_device_errors_total metric

---

collector/runit.go

This closes #362
While the runit collect probably will get deprecated soon, this should have had a flag from day 1 so I think it's fair to add this for now.

Add runit service dir flag

---

Makefile

This allows the user to override how/where promu and/or go is invoked.
This closes https://github.com/prometheus/node_exporter/issues/271

Allow overrides for GO and PROMU

---

Makefile

If GOPATH includes multiple paths, running `make promu` would fail.
This fixes it by always using the first path.

Fix Makefile by using first element of GOPATH

---

collector/cpu_freebsd.go
collector/filesystem_freebsd.go
collector/loadavg_freebsd.go
collector/loadavg_unix.go
collector/meminfo_bsd.go

This PR replaces the loadavg and filesystem collectors for FreeBSD with pure Go versions, using syscalls and sysctl directly.
It is possible that these may also work for other BSDs without changes, but I don't have any machines to test that on.
I use `unsafe` in two places, once for endianness reasons (loadavg) and once to avoid some memory allocations (file systems). I'm happy to remove either of those.

Replace some FreeBSD collectors with pure Go versions

---

CONTRIBUTING.md
README.md
collector/collector.go
collector/gmond.go
collector/megacli.go
collector/ntp.go

Hi,
this is a stab at #307. The definition is still up for discussion, so is the scope in general. But this is what I think makes most sense. You could argue to keep 'common' stuff beyond the kernel, like systemd metrics. But this would make it really hard to draw a line without having to discuss it over and over again.
Therefor I would propose to limit the scope to the definition here. This will also allow us to get better system/hw metrics across various OSes. All deprecated collector can be easily split into standalone exporters. This is something we should definitely do for the process supervisor collectors.

RFC: Limit node-exporter scope, mark collectors deprecated that don't fit

---

collector/netdev_common.go
collector/netdev_darwin.go

Same as for openbsd, this is just slightly adjusted from freebsd
variant.
I'd like to merge all those and only have the bare minimum in platform specific files but for now I think adding it as this is fine. Will help with the refactoring later.

Add netdev collector for darwin

---

collector/bonding_linux.go
collector/collector.go
collector/cpu_freebsd.go
collector/devstat_freebsd.go
collector/diskstats_linux.go
collector/fixtures/e2e-output.txt
collector/interrupts_common.go
collector/interrupts_linux.go
collector/interrupts_openbsd.go
collector/ipvs_linux.go
collector/ipvs_linux_test.go
collector/loadavg.go
collector/ntp.go
collector/runit.go
collector/tcpstat_linux.go
collector/time.go
collector/vmstat_linux.go

I didn't touch the gmond and megacli collectors since we'll remove them soon anyway.
I also kept devError a regular metric because that seemed appropriate to me since it's about counting all errors that happened in the exporter, not gathering some external state where ConstMetrics should be used.
Closes #240

Convert remaining collectors to use ConstMetrics

---

README.md
collector/cpu_darwin.go

This is pretty much copied 1:1 from gopsutils which is licensed under BSD. I've added a note `Based on gopsutil/cpu/cpu_darwin_cgo.go @ ae251eb, licensed as under BSD` right under the prometheus license header. Anyone knows if this is fine like this? License wise that should be okay afaik.

Add cpu collector for darwin

---

collector/fixtures/e2e-output.txt
collector/hwmon_linux.go

The chip label generation has been changed in #334 to prefer the unique device path (e.g. the location on the PCI bus) due to #333.
After discussion in #355, we learnt that the way forward is to provide an annotation metric (instead of a new label on the existing metrics). The annotation metric allows to link the unique chip sysfs path to a human-readable chip type which may not be unique among chip sysfs paths (for example, dual-slot systems have multiple chipType="coretemp" sensors).
This allows to mitigate the downsides of the solution to #333 (namely that the device path may not be stable across kernels and reboots) for cases where it does not matter that multiple devices may have the same human-readable type (e.g. aggregation or where at most one device of a type is present).
For …

hwmon: Provide annotation metric to link chip sysfs paths to human-readable chip types

---

collector/meminfo.go
collector/meminfo_bsd.go
collector/meminfo_darwin.go
collector/meminfo_linux.go

Instead of doing the whole metric exposition in a platform specific collector implementation, this creates and updates the metrics in meminfo.go and expected a platform specific implementation of getMemInfo on *meminfoCollector.
The second commit adds meminfo metrics on Darwin.
This closes #386 
---
Now I'm not sure about those metrics in general.. It would be much nicer to have a metric that is summed across all dimensions the total memory, basically something like node_memory_bytes_total{area="wire|cache|used.."}.
We decided against this for linux since we just exposed raw procfs values since it seems futile to track all changes there and add whatever was split out from some metrics. Now for all the bsds, we explicitly refer to some vmstat struct fields, so it doesn't really matter if …

Refactor meminfo and add darwin metrics

---

collector/filesystem_bsd.go
collector/filesystem_common.go
collector/filesystem_freebsd.go
collector/filesystem_linux.go

Closes #377
--
Now we should also have tests for that. I've tried enabling the filesystem collector in the end to end tests but failed. Somehow it always showed a difference for my root filesystem. Anyone know why the collector isn't included in the tests?
Either way, we should have end-to-end tests for that, but I don't think it should block this bugfix here either.

Make sure we only return one metric per mounted fs

---

collector/loadavg_solaris.go

It seems Solaris prefers `sys/loadavg.h` over `stdlib.h` when fetching the load average.
Using `stdlib.h`
```
$GOOS=solaris GOARCH=amd64 go build node_exporter.go
could not determine kind of name for C.getloadavg
```
Related PR comments: https://github.com/prometheus/node_exporter/pull/155#issuecomment-152975331
For Illumos based OSes it was required to include `sys/time.h` to ensure that `hrtime_t` was defined.
https://www.illumos.org/issues/6002
It also required setting the ldflags `-fno-stack-protector -lssp` to avoid undefined symbols when linking with gcc.
```
/opt/local/go/pkg/tool/solaris_amd64/link: running gcc failed: exit status 1
Undefined                       first referenced
symbol                             in file
__stack_chk_fail …
```

Added loadavg collector for Solaris

---

README.md
collector/fixtures/e2e-output.txt
collector/fixtures/wifi/interfaces.json
collector/fixtures/wifi/wlan0/stationinfo.json
collector/wifi_linux.go
end-to-end-test.sh
vendor/github.com/mdlayher/netlink/conn.go
vendor/github.com/mdlayher/netlink/sockopt_linux_386.go
vendor/vendor.json

Depends on #412 .
No idea how to test this honestly.  I've been developing by copying the binary over to my laptop and poking at it there.  Can CI tests be done with a virtual wireless device of some sort?

Add initial wifi collector

---

collector/fixtures/e2e-output.txt
collector/mountstats_linux.go

Fixes #382 
cc: @discordianfish @SuperQ

Add NFS event metrics to mountstats collector

---

collector/zfs.go

Appears to have just been a simple mistake, since the switch below handles this case.
```
$ ./node_exporter -log.level debug
INFO[0000] Starting node_exporter (version=, branch=, revision=)  source="node_exporter.go:136"
INFO[0000] Build context (go=go1.7.4, user=, date=)      source="node_exporter.go:137"
INFO[0000] No directory specified, see --collector.textfile.directory  source="textfile.go:57"
INFO[0000] Enabled collectors:                           source="node_exporter.go:156"
INFO[0000]  - edac                                       source="node_exporter.go:158"
INFO[0000]  - loadavg                                    source="node_exporter.go:158"
INFO[0000]  - netdev                                     source="node_exporter.go:158"
INFO[0000]  - netstat …
```

Make ZFS collector fail gracefully when not available

---

collector/wifi_linux.go
vendor/github.com/mdlayher/netlink/conn.go
vendor/github.com/mdlayher/wifi/client.go
vendor/github.com/mdlayher/wifi/client_linux.go
vendor/github.com/mdlayher/wifi/client_others.go
vendor/vendor.json

Had to update `wifi` because I forgot to add a `Close` method until now.  Oops.
Looks good on my machine that doesn't have nl80211.
```
$ genl-ctrl-list
0x0010 nlctrl version 2
0x0011 VFS_DQUOT version 1
0x0013 NLBL_MGMT version 3
0x0014 NLBL_CIPSOv4 version 3
0x0015 NLBL_UNLBL version 3
0x0016 acpi_event version 1
0x0017 thermal_event version 1
0x0018 tcp_metrics version 1
0x0019 TASKSTATS version 1
$ ./node_exporter -collectors.enabled wifi
INFO[0000] Starting node_exporter (version=, branch=, revision=)  source="node_exporter.go:136"
INFO[0000] Build context (go=go1.7.4, user=, date=)      source="node_exporter.go:137"
INFO[0000] Enabled collectors:                           source="node_exporter.go:156"
INFO[0000]  - wifi …
```

Make wifi collector fail gracefully if metrics not available

---

.travis.yml
circle.yml

Update travis/circle CI builds to use Go 1.7.

Use go 1.7

---

collector/hwmon_linux.go

```
$ ./node_exporter -web.listen-address 192.168.1.1:9100 -collectors.enabled hwmon -log.level debug
INFO[0000] Starting node_exporter (version=, branch=, revision=)  source="node_exporter.go:136"
INFO[0000] Build context (go=go1.7.4, user=, date=)      source="node_exporter.go:137"
INFO[0000] Enabled collectors:                           source="node_exporter.go:156"
INFO[0000]  - hwmon                                      source="node_exporter.go:158"
INFO[0000] Listening on 192.168.1.1:9100                 source="node_exporter.go:176"
DEBU[0001] hwmon collector metrics are not available for this system  source="hwmon_linux.go:404"
DEBU[0001] OK: hwmon collector succeeded after 0.002255s.  source="node_exporter.go:95"
```
Fixes #426

Allow graceful failure in hwmon collector

---

collector/wifi_linux.go
vendor/github.com/mdlayher/wifi/client.go
vendor/github.com/mdlayher/wifi/client_linux.go
vendor/github.com/mdlayher/wifi/client_others.go
vendor/github.com/mdlayher/wifi/wifi.go
vendor/vendor.json

Prevents this kind of error from happening if the interface isn't connected to an access point:
```
$ ./node_exporter -collectors.enabled wifi -web.listen-address :9101
INFO[0000] Starting node_exporter (version=, branch=, revision=)  source="node_exporter.go:136"
INFO[0000] Build context (go=go1.7.4, user=, date=)      source="node_exporter.go:137"
INFO[0000] Enabled collectors:                           source="node_exporter.go:156"
INFO[0000]  - wifi                                       source="node_exporter.go:158"
INFO[0000] Listening on :9101                            source="node_exporter.go:176"
ERRO[0004] ERROR: wifi collector failed after 0.000302s: failed to retrieve station info for device wlan1: file does not exist  source="node_exporter.go:92"
```
Also bumps the vendored …

Update vendored wifi, handle stations with missing info

---

README.md

There's a slow trickle of people trying to use the node exporter on windows, so point them in the right direction.

Point to WMI exporter

---

collector/fixtures/proc/10/mountstats
collector/mountstats_linux.go

It's possible to mount an NFS share in multiple locations.
* Duplicates contain the same metric values, so they can be ignored.
* Update fixture.

Handle multiple NFS device mounts

---

README.md
collector/fixtures/e2e-output.txt
collector/fixtures/proc/spl/kstat/zfs/dmu_tx
collector/fixtures/proc/spl/kstat/zfs/fm
collector/fixtures/proc/spl/kstat/zfs/vdev_cache_stats
collector/fixtures/proc/spl/kstat/zfs/xuio_stats
collector/fixtures/proc/spl/kstat/zfs/zfetchstats
collector/fixtures/proc/spl/kstat/zfs/zil
collector/zfs.go
collector/zfs_linux.go
collector/zfs_linux_test.go

This covers the majority of the missing data from ZFS's procfs data beyond Arcstats. Each path is broken up into a separate commit for cleanliness, with a slight refactor in the first commit that made the initial Arcstats code more easily extensible with less repetition.

Update ZFS Collector with most non-zpool metrics

---

collector/fixtures/e2e-output.txt
collector/zfs.go

This fixes #442, and prevents other ZFS metrics from slipping through in the future.
Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

ZFS Collector: Convert dashes to underscores for metrics

---

README.md
node_exporter.go

Add wifi collector to default collectors

---

vendor/github.com/prometheus/procfs/mountstats.go
vendor/vendor.json

Fixes #437 .
Not super sure about a couple of those lines removed in `vendor/vendor.json`.  I just ran `govendor fetch github.com/prometheus/procfs` and it did that for me.

Bump github.com/prometheus/procfs for uint64 mountstats counters

---

text_collector_examples/ntpd_metrics.py

Parse the output of `ntpq -np` to provide metrics from a local NTP
daemon.

Add a textfile helper for NTPd.

---

Dockerfile

Use glibc variation of quay.io/prometheus/busybox image to make the docker image work until we find how to rebuild node_exporter statically for linux/amd64
@SuperQ

Make the docker image work until we fix linux/amd64 static build.

---

Makefile

The End-to-end tests as they are now, are very dependent on running on Linux.
This makes the Makefile more OS agnostic regarding end to end tests.
@discordianfish 
fixes #476

disable end-to-end tests for non Linux OSes in Makefile

---

vendor/github.com/mdlayher/netlink/conn_linux.go
vendor/vendor.json

This one hasn't caused a bug in node_exporter yet, but in the case of a failure to `bind()`, the socket should still be cleaned up.

Bump github.com/mdlayher/netlink to clean up on bind failure

---

node_exporter_test.go

Implements #494.
@mdlayher @SuperQ @discordianfish 
Well, I couldn't find a system where the wifi collector would leak file descriptors. Both my DO box and Travis support the necessary netlink calls. I was also not really successful leaking a file descriptor by not closing a file handle correctly. The /proc filesystem seems to be a bit special here? Let me know if you have any concerns.

Test node_exporter for file descriptor leaks

---

collector/meminfo_bsd.go
collector/sysctl_bsd.go

Replaces #499, dunno what happened there.

Refactor meminfo_bsd.go to use sysctl_bsd.go

---

vendor/github.com/mdlayher/netlink/conn.go
vendor/github.com/mdlayher/netlink/conn_linux.go
vendor/vendor.json

Basically, this replaces some of my complicated netlink PID assignment logic with a call to `getsockname()`. I don't know why I didn't think of this before today.
There should be no effect on `node_exporter`.  I'm making this PR so that this update doesn't catch someone by surprise later on.

Update github.com/mdlayher/netlink with code simplifications

---

node_exporter.go
node_exporter_test.go

Problems of a single collector, like duplicated metrics read via the
textfile collector, should not fail the collection and export of other
metrics.
Fixes #509.
@matthiasr @beorn7 @SuperQ 
Test errors are unrelated to this change and the result of a new minimum go version required by staticcheck.

Continue scrape with duplicated metrics

---

collector/fixtures/e2e-output.txt
end-to-end-test.sh
node_exporter.go

This is in line with best practices, and also saves us
63 timeseries on a default Linux setup.

Report collector success/failure and duration per scrape.

---

collector/fixtures/e2e-output.txt
collector/fixtures/wifi/wlan0/bss.json
collector/wifi_linux.go

Tested on my laptop:
```
$ curl -s http://192.168.1.20:9101/metrics | grep "node_wifi_station_info"            
node_wifi_station_info{bssid="44:d9:e7:03:2a:56",device="wlp2s0",mode="client",ssid="The Red Dragon Inn"} 1
```
Fixes #508 .

Add synthetic node_wifi_station_info metric for BSS information

---

vendor/github.com/mdlayher/wifi/client.go
vendor/github.com/mdlayher/wifi/wifi.go
vendor/vendor.json

This removes and unnecessary restriction and will enable better WiFi collector debugging information in the logs.  PR to follow for the WiFi collector changes.

Bump github.com/mdlayher/wifi to relax station info restrictions

---

collector/devstat_freebsd.go

Static linking requires all  (recursive) library dependencies to be  listed  explicitly.
Fixes this build error on FreeBSD 11:
```
/usr/local/go/pkg/tool/freebsd_amd64/link: running cc failed: exit status 1
/usr/lib/libkvm.a(kvm.o): In function `_kvm_read_core_phdrs':
/usr/src/lib/libkvm/kvm.c:(.text+0x3a4): undefined reference to `elf_begin'
/usr/src/lib/libkvm/kvm.c:(.text+0x3b8): undefined reference to `elf_kind'
/usr/src/lib/libkvm/kvm.c:(.text+0x3c9): undefined reference to `gelf_getclass'
/usr/src/lib/libkvm/kvm.c:(.text+0x3e5): undefined reference to `gelf_getehdr'
/usr/src/lib/libkvm/kvm.c:(.text+0x41c): undefined reference to `elf_getphdrnum'
/usr/src/lib/libkvm/kvm.c:(.text+0x46d): undefined reference to `gelf_getphdr'
/usr/src/lib/libkvm/kvm.c:(.text+0x48b): undefined reference …
```

Add missing dependency for static FreeBSD build

---

text_collector_examples/smartmon.sh

"%d" in awk truncates values at 2^31. S.M.A.R.T. raw values can exceed that, thus use a floating point notation instead to encode larger values (at the possible cost of some precision).

Handle smart raw values >2^31

---

Makefile

If this is not desired, copy/symlink these binaries to a different path and
set the respective environment variables. For example:
ln -s "$(GOPATH)/bin/{promu,staticcheck}" /usr/local/bin/
PROMU=/usr/local/bin/promu STATICCHECK=/usr/local/bin/staticcheck make build
I broke the auto-update in 301d8e4.
@discordianfish @SuperQ

Download promu and staticcheck every time by default

---

collector/filesystem_bsd.go
collector/filesystem_common.go
collector/filesystem_linux.go

Instead of maintaining a counter metric for device errors in memory,
this change exports a gauge and uses const metrics to avoid leaking
metrics for unmounted filesystems.
Fixes #527.
@rtreffer @SuperQ @discordianfish

Fix export of stale device error metrics for unmounted filesystems

---

collector/systemd_linux.go

Blacklist `scope` units from systemd collector by default.
These units are created with unique IDs programatically[0].  This leads to
huge cardinality problems.
[0]: https://www.freedesktop.org/software/systemd/man/systemd.scope.html

Blacklist systemd scope units

---

collector/mdadm_linux.go

@SuperQ Just another little simplification. The error message was a bit convoluted anyway `error parsing mdstatus: error parsing mdstat: <actual error>`.

mdadm: Remove extra file existence check

---

.promu.yml

There are crossbuild errors on netbsd/arm with go1.8. Assuming there is
only a small minority of people running netbsd on ARM processors,
disabling these builds is the fastest workaround.
@derekmarcotte @sdurrheimer

Remove netbsd/arm support for now

---

circle.yml

We already use go1.8 in promu, so loading another image slows down the
build.
@sdurrheimer @SuperQ

Use go1.8 in CircleCI tests

---

.promu.yml
collector/buddyinfo.go
collector/loadavg.go
collector/meminfo.go

Use https://github.com/martinlindhe/wmi_exporter instead.
Fixes #542.
Once merged the following steps will remove Windows from the prometheus.io/download page:
1. manually delete the Windows binaries from the latest release
2. trigger a prometheus/docs travisci run

Remove Windows support

---

text_collector_examples/smartmon.sh

updated smartmon.sh example to include metric for overall health status

---

collector/fixtures/e2e-output.txt
collector/stat_linux.go

This commit fixes #553.
Please notice that the commit may change the default behavior of the cpu collector as it adds a 10th cpu "mode" label (`guest_nice`) if available.

cpu collector: guest_nice

---

collector/edac_linux.go
collector/fixtures/e2e-output.txt

Fix typo in `csrow` label of `node_edac_csrow_uncorrectable_errors_total` metric: "uknown" => "unknown"

edac: Fix typo in node_edac_csrow_uncorrectable_errors_total

---

README.md
examples/systemd/README.md
examples/systemd/node_exporter.service
examples/systemd/sysconfig.node_exporter

Mention copr yum repository, add systemd unit

---

collector/uname_linux_int8.go

Since Go 1.8 32bit MIPS Big/Little Endian are supported assuming the target runs Linux and the kernel either emulates an FPU or can access the CPU one.
This allows the node_collector to build for `mips` and `mipsle` `GOARCH` paired with `GOOS` set to `linux`, opening up the possibility of running it on things like home routers. (DD-|Open|ASUS-)Wrt firmware usually has the necessary bits in place.
`env GOOS=linux env GOARCH=mipsle go build node_exporter.go`
```
collector/uname_linux.go:56: undefined: unameToString
collector/uname_linux.go:57: undefined: unameToString
collector/uname_linux.go:58: undefined: unameToString
collector/uname_linux.go:59: undefined: unameToString
collector/uname_linux.go:60: undefined: unameToString
collector/uname_linux.go:61: undefined: unameToString
```
It …

uname_linux: Build for 32bit MIPS too

---

collector/exec_bsd.go
collector/meminfo_bsd.go
collector/sysctl_bsd.go

Adds new sysctl type, bsdSysctlTypeStructTimeval to enable parsing of
timevals from raw memory.  Assumes LittleEndian.

Add exec_boot_time for freebsd, dragonfly

---

collector/bonding_linux.go
collector/bonding_linux_test.go

@grobie 
Using the bonding collector on a (linux) server that does not have linux bonding gives a very noisy error in the log at each metric scrape:
```
ERRO[0023] ERROR: bonding collector failed after 0.000191s: open /sys/class/net/bonding_masters: no such file or directory  source=node_exporter.go:91
```
With this PR, the collector will now return (nil, nil) if the error was a non existing bonding_masters file. I've added a test that test against an empty fixtures dir to verify that it does not error on a missing file.
Perhaps I should add a log.Debugf() with the error, so it will show up in the logs when verbosity is requested by the end user?

silently ignore nonexisting bonding_masters file

---

collector/fixtures/e2e-output.txt
collector/infiniband_linux.go

According to Mellanox, it is standard practice that the port_xmit_data and port_rcv_data
files are split into 4 lanes. To get the actual transmit and receive values for each
port, the metric needs to be multiplied by 4.
If applied, this fixes #573.
Signed-Off-By: Robert Clark <robert.d.clark@hpe.com>

Multiply port data XMIT/RCV metrics by 4

---

README.md
collector/fixtures/e2e-output.txt
collector/fixtures/qdisc/results.json
collector/qdisc_linux.go
end-to-end-test.sh
vendor/github.com/ema/qdisc/LICENSE.md
vendor/github.com/ema/qdisc/Makefile
vendor/github.com/ema/qdisc/README.md
vendor/github.com/ema/qdisc/get.go
vendor/vendor.json

This collector gathers basic queueing discipline metrics via netlink,
similarly to what `tc -s qdisc show` does.

Add qdisc collector for Linux

---

README.md

It's probably a bad idea to bind-mount them read/write and should be entirely unnecessary.

Make bind-mounts in Docker example read-only

---

Dockerfile

We probably should have done that earlier. Anyway, the node-exporter doesn't require root, in fact that a requirement for any collector we accept into the node-exporter.
Still, the Dockerfile we provide runs the node-exporter as root. While that's common for docker containers and prometheus itself isn't an exception, the node-exporter runs with bind-mounts to /sys and / and while encourage to be read-only, still has a bigger attack surface.

Run node-exporter in Docker as nobody

---

README.md

Add `go get` and source directory requirements to the build
instructions.

Add go path help to build instructions

---

CHANGELOG.md

@grobie rightfully complained that this change needs a changelog entry.

Add changelog entry for node_cpu metrics move

---

collector/cpu_linux.go
collector/fixtures/e2e-output.txt

I've missed that the cpufreq values are actually kHz, not Hz. Thus translate from kHz to Hz before exporting.

Fix cpufreq statistics by converting kHz to Hz

---

.travis.yml

That's changes nothing for this repository but allows forks to use Travis CI without hacking configuration and makes merging with upstream easier.

Set Go import path on Travis CI

---

collector/fixtures/e2e-output.txt
collector/xfs_linux.go

A continuation of my previous XFS collector work. Many stats left, but I'll keep adding them in chunks to make it more manageable.

Add XFS block mapping and block map B-tree stats

---

Makefile
node_exporter_test.go

Hi! 
I noticed that currently the tests in `node_exporter.go` fail when run with the race detector. For example, on master:
```
$ go test -race -v
=== RUN   TestFileDescriptorLeak
--- SKIP: TestFileDescriptorLeak (0.00s)
node_exporter_test.go:26: proc filesystem is not available, but currently required to read number of open file descriptors: could not read /proc: stat /proc: no such file or directory
=== RUN   TestHandlingOfDuplicatedMetrics
==================
WARNING: DATA RACE
Read at 0x00c4201960a0 by goroutine 12:
github.com/prometheus/node_exporter.runCommandAndTests()
/Users/jeromefroelich/golang/src/github.com/prometheus/node_exporter/node_exporter_test.go:128 +0x17b
github.com/prometheus/node_exporter.TestHandlingOfDuplicatedMetrics() …
```

[test] Call cmd.Start and cmd.Wait separately to avoid triggering race detector

---

collector/cpu_darwin.go
collector/cpu_dragonfly.go
collector/cpu_freebsd.go
collector/devstat_dragonfly.go
collector/devstat_freebsd.go
collector/loadavg_solaris.go
collector/loadavg_unix.go
collector/sysctl_bsd.go
collector/tcpstat_linux.go

I was playing around with `golint` and decided to fix some trivial issues.
One `golint` warning for `collector/devstat_freebsd.go` remains:
```
collector/devstat_freebsd.go:40:2: don't use underscores in Go names; struct field bytes_total should be bytesTotal
```
However, the `bytes` vs `bytes_total` typedDesc looks suspicious and I decided not to touch it.

Golint fixes

---

.gitignore
collector/loadavg.go
collector/loadavg_freebsd.go
collector/loadavg_solaris.go
collector/meminfo.go

The meminfo and loadavg collectors aren't available on all operating systems supported by go, we need to list the supported ones explicitly.
Fixes #596.

Restrict build tags of collectors to supported operating systems

---

README.md
collector/fixtures/e2e-output.txt
collector/ipvs_linux.go
end-to-end-test.sh
node_exporter.go

* Silence error output when no IPVS present.
* Enable by default.
* Update end-to-end fixture.
* Update README.

Enable IPVS collector by default

---

README.md

in version 8.4 deprecated (but won’t be removed)

Status information in /proc/drbd

---

README.md

Tested a DL360 Gen9 box with an Omni-Path adapter in it. The existing InfiniBand collector can provide support for the same metrics on Omni-Path cards as well.
Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

Clarify InfiniBand collector support

---

Dockerfile.ppc64le
Makefile

A small change in the makefile determining the right architecture and a new Dockerfile.ppc64le where the base image is different (ppc64le/busybox:glibc).

Add dockerfile for ppc64le and related changes

---

collector/wifi_linux.go

Ignore the permission denined error when the wifi collector has no
permission to read metrics.
Closes: https://github.com/prometheus/node_exporter/issues/649

Ignore wifi collector permission errors

---

collector/zfs.go
collector/zfs_linux.go
collector/zfs_linux_test.go
node_exporter_test.go

This avoids issues with integer overflows on 32-bit architectures. The
Prometheus data format is float64, so regardless of the architecture we
should handle large numbers.
While here, fix the format in `node_exporter_test.go`.
Fixes #629.

Use int64 throughout the ZFS collector.

---

.promu.yml

Maintaining a fork with a different folder name breaks the travis build/test.
Sympton:
```$ make
>> formatting code
>> vetting code
>> running staticcheck
>> building binaries
>   prometheus-node-exporter
./ttar -C collector/fixtures -x -f collector/fixtures/sys.ttar
touch collector/fixtures/sys/.unpacked
>> running tests
ok  	github.com/prometheus/node_exporter	1.029s
ok  	github.com/prometheus/node_exporter/collector	1.068s
?   	github.com/prometheus/node_exporter/collector/ganglia	[no test files]
>> running end-to-end tests
./end-to-end-test.sh
./node_exporter not found. Consider running `go build` first.
make: *** [test-e2e] Error 1
The command "make" exited with 2.
Done. Your build exited with 1.
```
This pull request defines a consistent binary filename in the promu configuration …

define consistent binary filename in promu configuration file

---

Makefile

This doesn't work on at least FreeBSD and Darwin. It does work on Linux,
only try it there.
Fixes https://github.com/prometheus/node_exporter/pull/652#issuecomment-324142309

Only cross-test 32bit on Linux

---

collector/cpu_linux.go
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar

'package_throttles_total' is per package, not per cpu. This also reduces
the total number of cpu time series a lot (esp for multi core cpus).
Also add some missing fixtures for cpu2 and cpu3 for consistency.

cpu: Metric 'package_throttles_total' is per package.

---

README.md
collector/timex.go
node_exporter.go

This collector is based on adjtimex(2) system call.  The collector returns
three values, status if time is synchronised, offset to remote reference,
and local clock frequency adjustment.
Values are taken from kernel time keeping data structures to avoid getting
involved how the synchronisation is implemented.  By that I mean one should
not care if time is update using ntpd, systemd.timesyncd, ptpd, and so on.
Since all time sync implementation will always end up telling to kernel what
is the status with time one can simply omit the software in between, and
look results of the syncing.  As a positive side effect this makes collector
very quick and conceptually specific, this does not monitor availability of
NTP server, or network in between, or dns resolution, and other unrelated
but …

Add timex collector

---

Makefile

This enables native builds to still run the test and all targets without
problems on say 386.
Build failure on Buildkite build 85, prevents enabling native FreeBSD
386 builds.

Only enable race detector when GOHOSTARCH is amd64.

---

circle.yml

The default DOCKER_IMAGE_TAG setup fails when running in circle,
override with the CIRCLE_TAG.

Fix circle docker test tag name.

---

README.md

* Add link to Golang
* Add note about RHEL/CentOS build dep.
Closes: https://github.com/prometheus/node_exporter/issues/693

Add extra notes to Building section

---

Makefile
README.md
collector/collector.go
node_exporter.go

This PR adds a `collect[]` URL parameter to filter currently enabled collectors.

Add `collect[]` parameter

---

text_collector_examples/smartmon.sh

When there are no SMART compatible devices (Raspberry Pi for example) an
error is returned, but the return code is still 0.
`# scan_smart_devices: glob(3) aborted matching pattern /dev/discs/disc*`
* Remove unused `disks` variable.
* Filter for only valid `/dev` devices.

Fix smartmon.sh textfile script

---

text_collector_examples/smartmon.sh

some ssds don't report using media_wearout_indicator

added Wear_Leveling_Count attribute to smartmon.sh script

---

collector/fixtures/e2e-output.txt
collector/xfs_linux.go

I made two mistakes:
- I was using allocation btree stats as the source for block map btree stats.
- I named the metrics "block_mapping" instead of "block_map".  Too late to fix now?  We're not 1.0 so I'd rather just fix it if possible.

xfs: expose correct fields, fix metric names

---

collector/meminfo_bsd.go
collector/sysctl_bsd.go

The sysctl vfs.bufspace returns either an int or a long, depending on
the value.  Large values of vfs.bufspace will result in error messages
like:
couldn't get meminfo: cannot allocate memory
This will detect the returned data type, and cast appropriately.
This is an updated fix to the one provided in #710.
I suspect that there'll be more re-factoring here, if other uses show up.

Correct buffer_bytes > INT_MAX on BSD/amd64.

---

collector/netstat_linux.go

Fixes #717.
The return map is ranged over, but since it's nil, nothing will happen: https://play.golang.org/p/Sft1zxlRA5.

netstat: return nothing when /proc/net/snmp6 not found

---

collector/fixtures/e2e-output.txt
collector/interrupts_linux.go
collector/interrupts_linux_test.go
end-to-end-test.sh

* Fix off by one in CPU column handler.
* Add test.
* Enable interrupts in end-to-end test.
Closes: https://github.com/prometheus/node_exporter/issues/720

Fix off by one in Linux interrupts collector

---

collector/hwmon_linux.go

I believe this will fix https://github.com/prometheus/node_exporter/issues/697.

Add and use sysReadFile in hwmon collector

---

collector/cpu_linux.go
collector/fixtures/sys.ttar

This PR fixes the following crash on systems with **processor-less (memory-only) NUMA node(s)**:
```
panic: runtime error: index out of range
goroutine 40 [running]:
github.com/prometheus/node_exporter/collector.(*cpuCollector).updateCPUfreq(0xc420214690, 0xc4202f0900, 0x0, 0x0)
.../go/packages/src/github.com/prometheus/node_exporter/collector/cpu_linux.go:164 +0x13ad
github.com/prometheus/node_exporter/collector.(*cpuCollector).Update(0xc420214690, 0xc4202f0900, 0x106da40, 0x0)
.../go/packages/src/github.com/prometheus/node_exporter/collector/cpu_linux.go:94 +0x60
github.com/prometheus/node_exporter/collector.execute(0xad6ab8, 0x3, 0x1035e40, 0xc420214690, 0xc4202f0900)
.../go/packages/src/github.com/prometheus/node_exporter/collector/collector.go:131 +0x7e …
```

cpu: Support processor-less (memory-only) NUMA nodes

---

text_collector_examples/ipmitool

Converts output of `ipmitool sensor` to prometheus format.
e.g.: `ipmitool sensor | ./ipmitool > ipmitool.prom`

Added text collector conversion for ipmitool output.

---

collector/netdev_common.go

All the metric only goes up, so the type should be counter.
Fix: #747

netdev: Change valueType to CounterValue

---

collector/textfile.go

The textfile gatherer should only be added to gatherer list once.
Closes #704

textfile: fix duplicate metrics error

---

text_collector_examples/apt.sh

I found this case mostly on machines with "point release" upgrades pending, e.g. like the recent jessie and stretch updates. What do you think @SuperQ ?

apt.sh: handle multiple origins in apt-get output

---

text_collector_examples/storcli.py

This PR fixes,
1. Some [pylint](https://www.pylint.org/) issues.
2. Handle the case when StorCli is not installed returning a fake answer (empty JSON) back.
```
megaraid_controllers 0
megaraid_status_code 0
```
\* Tested with CentOS7.4 and Python2.7, but it should be running with Python3 too.

StorCli text collector: fix pylint issues and handle StorCli not installed

---

collector/fixtures/e2e-output.txt
collector/textfile.go

The textfile collector does not support client-side timestamps anymore after https://github.com/prometheus/node_exporter/pull/763. Only the e2e tests caught this, which only seem to run once something is merged into master?
@brian-brazil is this ok, or do we still need to support client-side timestamps for user-supplied textfile metrics?

Fix e2e tests after textfile custom timestamp removal

---

collector/filesystem_linux.go

Closes: https://github.com/prometheus/node_exporter/issues/773

[FIX] Exclude Linux proc from filesystem type regexp

---

collector/filesystem_linux.go

Add additional Linux virtual filesystem types to the default list.

Ignore more virtual filesystems

---

collector/meminfo.go
collector/meminfo_openbsd.go

In order to move on with #151 this is a rework of the initial work made by @mischief 
This will gather memory stats from OpenBSD.
Tested on OpenBSD 6.2 (latest release) and ready for review @SuperQ

Add openbsd meminfo

---

example-rules.yml

This pull request adds a new example rules file, which is compatible with Prometheus 2.0. The examples are copied from the original example file.
I tested it with the beta2 release, though the format should be the same in the final release.
@discordianfish @SuperQ

Add Prometheus 2.0 compatible example rules file - new YAML format

---

README.md

Improve recommendations and wording around advanced use of the collect[]
param.
Remove example that causes users to copy-and-paste it.

Update collect[] param documentation

---

collector/cpu_linux.go
collector/diskstats_linux.go
collector/diskstats_linux_test.go
collector/filesystem_common.go
collector/fixtures/e2e-output.txt
collector/infiniband_linux.go
collector/interrupts_common.go
collector/meminfo_linux.go
collector/meminfo_linux_test.go
collector/meminfo_openbsd.go
collector/stat_linux.go
collector/timex.go

I think that's all the main ones, I'm a little unsure on the timex ones even after looking at the docs and source
@SuperQ 
Fixes #150
Supercedes #559

Make metrics better follow guidelines

---

text_collector_examples/smartmon.sh

* Fix parsing of SMART-ID attributes <= 99. (See https://github.com/prometheus/node_exporter/pull/731)
* Fix smartmon.sh info label consistency.
Closes: https://github.com/prometheus/node_exporter/issues/791

Fix smartmon.sh bugs

---

text_collector_examples/smartmon.sh

Some devices has double quotes in it's model family. Something like this:   
`Model Family:     Toshiba 3.5" DT01ACA... Desktop HDD`
It makes broken metric:  
`smartmon_device_info{disk="/dev/sdb",type="sat",model_family="Toshiba 3.5" DT01ACA... Desktop HDD",device_model="TOSHIBA DT01ACA300",serial_number="63QY1WTGS",firmware_version="MX6OABB0"} 1`
This PR is fixing this by escaping `"`.

Escape double quotes in device model family

---

collector/cpu_openbsd.go

- Tested on OpenBSD 6.2 and OpenBSD-current, single and multi CPU, i386 and amd64
- Metric follows guidelines

Add OpenBSD CPU collector

---

text_collector_examples/apt.sh

This patch fixes:
./apt.test: command substitution: line 19: syntax error near unexpected token `|'
./apt.test: command substitution: line 19: `  | /usr/bin/sort   | /usr/bin/uniq -c   | awk '{ gsub(/\\\\/,

text_collector_examples/apt.sh: add missing backslash 

---

collector/filesystem_linux.go

The node exporter runs unprivileged, so it cannot statfs any filesystems
under this directory causing log spam.  In addition there tends to be
high churn in the filesystems here (as it's basically application
monitoring) which can cause high cardinaltiy and in one case caused
Prometheus's index symbol table to get very large.
Accordingly this should be ignored to reduce log spam and avoid
performance issues. The filesystems themselves can in principle be
monitored via container oriented exporters, and the underlying
filesystems will still be monitored.
@SuperQ

Ignore /var/lib/docker by default.

---

collector/nfsd_linux.go

Fixes:
```
ERRO[0007] ERROR: nfsd collector failed after 0.000041s: failed to retrieve nfsd stats: open /proc/net/rpc/nfsd: no such file or directory source="collector.go:136"
```
Now debug level only:
```
DEBU[0014] Not collecting NFSd metrics: open /proc/net/rpc/nfsd: no such file or directory  source="nfsd_linux.go:63"
```

Fix error output in nfsd collector.

---

collector/filesystem_linux.go

To avoid statfs() errors if node_exporter is running as non privileged user in docker host.

Add overlay to defIgnoredFSTypes

---

collector/meminfo_openbsd.go

All tools in OpenBSD base system use swpginuse instead of swpgonly
for reporting swap usage (snmpd, swapctl, top, vmstat), so let
memory collector use that as well for consistency.

Use swpginuse instead of swpgonly in meminfo_openbsd

---

README.md
collector/nfs_linux.go

Enable NFS client metrics by default now that it nolonger prints errors
on scrape if there are no metrics to display.
Also fixup the nfsd README to match the nfs entry.

Enable NFS client metrics by default.

---

Makefile
collector/fixtures/e2e-output.txt
node_exporter.go

Update Prometheus client golang use to use `promhttp.Handler()` instead
of `prometheus.InstrumentHandlerFunc()`.

Remove deprecated prometheus.InstrumentHandlerFunc

---

text_collector_examples/directory-size.sh

This is a possible workaround for the lack of metrics in the new
storage backend, as documented in:
https://github.com/prometheus/prometheus/issues/3684
Partly inspired by this post as well:
https://www.robustperception.io/monitoring-directory-sizes-with-the-textfile-collector/

add sample directory size exporter

---

collector/fixtures/textfile/client_side_timestamp.out
collector/fixtures/textfile/client_side_timestamp/metrics.prom
collector/fixtures/textfile/two_metric_files/metrics2.prom
collector/textfile.go
collector/textfile_test.go

This is clearer behavior and users will notice and fix their textfiles faster
than if we just output a warning.

Treat custom textfile metric timestamps as errors

---

Makefile

I was trying to build node_exporter on SmartOS and ran into this issue. It fixes #698, but also needs https://github.com/prometheus/promu/pull/88 
Install setup from smartos image: base-64-lts 16.4.1
>   pkgin in scmgit-base gcc49
>   pkgin in go-1.9
>   pkgin in git-2.14.1
>   go get github.com/prometheus/node_exporter
>   cd go/src/github.com/prometheus/node_exporter/
>   pkgin in gmake
>   make
Before my change
>[root@fry ~/go/src/github.com/prometheus/node_exporter]# make
>> formatting code
>> vetting code
>> running staticcheck
>> building binaries
>   node_exporter
./ttar -C collector/fixtures -x -f collector/fixtures/sys.ttar
touch collector/fixtures/sys/.unpacked
>> running tests
GO15VENDOREXPERIMENT=1 go test -short -race github.com/prometheus/node_exporter …

On SunOS/ solaris/ SmartOS the go test flag of -rance isn't supported.

---

collector/cpu_darwin.go

Change the definition of ClocksPerSec to read from limits.h
Per #845, CPU counters are scaled by an incorrect factor (128 was assumed, which is the FreeBSD default [?]). Correct value on Darwin is given by the C macro CLK_TCK in limits.h

Correct the ClocksPerSec scaling factor on Darwin

---

collector/exec_bsd.go

This closes #827.
Not sure the exec_ prefix makes sense for the other metrics either..
And I don't have access to a freebsd machine to test this.

Drop exec_ in boot_timestamp_seconds on *bsd

---

collector/fixtures/e2e-output.txt
collector/fixtures/e2e-ppc64le-output.txt
collector/interrupts_linux.go
collector/interrupts_openbsd.go

To match other CPU related metric labels, use a lowercase named label.

Use lowercase cpu label name in interrupts

---

examples/launchctl/README.md
examples/launchctl/io.prometheus.node_exporter.plist
examples/launchctl/node_exporter.plist

There doesn't quite seem to be a handy way to get node_exporter running on MacOS, so I've brewed up the appropriate files and a README to get started, analogue to the way it's done for systemd.

Add example launchctl-file for MacOS

---

README.md
collector/bonding_linux.go

@SuperQ We can enable this one by default anyway, it meets the requirements.

Enable bonding collector by default.

---

collector/fixtures/e2e-output.txt
collector/netstat_linux.go

Netstat is 40% of the metrics on my laptop, many of which
are highly detailed information about IP internals in the kernel.
~300 such metrics on every machine in your fleet is excessive,
so focus on key metrics by default, overridable by the user.
Fixes #515
@SuperQ I think we should aim for about 20-30 metrics from this collector, I've selected what I think are the main ones but there's undoubtedly more. Unfortunately these metrics have basically no documentation, so I'm working off experience.

Greatly trim what netstat collector exposes by default

---

Makefile

Without this change, running 'gmake' as the documentation does not finish the
build process to produce the binary.
Fixes: https://github.com/prometheus/node_exporter/issues/880

Remove -race test flag to build on OpenBSD

---

CHANGELOG.md
collector/cpu_linux.go
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar

This fixes the `node_cpu_core_throttles_total` metrics on multi-socket systems as explained in detail in my comment to PR #836. As the `core_ids` are the same for each node (aka processor or package) we need to count them seperately. Otherwise we only count the last processor's cpu core throttles.
Refactor the `core_throttles_count` handling and move it from the cpu loop
to the NUMA node loop.
Reorganize the `sys.ttar` files and use the same symlinks as the Linux
kernel.

cpu: Add a 2nd label 'package' to metric node_cpu_core_throttles_total

---

text_collector_examples/smartmon.sh

Signed-off-by: Bernd Mueller <mueller@b1-systems.de>
added S.M.A.R.T. temperature values for some Intel disks
$smartctl -i -H -d sat /dev/sda
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.4.0-92-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF INFORMATION SECTION ===
Model Family: Intel 730 and DC S35x0/3610/3700 Series SSDs
Device Model: INTEL SSDSC2BB240G7
Serial Number: PHDV716402YR240AGN
LU WWN Device Id: 5 5cd2e4 14d7afbba
Firmware Version: N2010112
User Capacity: 240,057,409,536 bytes [240 GB]
Sector Sizes: 512 bytes logical, 4096 bytes physical
Rotation Rate: Solid State Device
Form Factor: 2.5 inches
Device is: In smartctl database [for details use: -P show]
ATA Version is: ACS-3 T13/2161-D revision 5
SATA Version is: …

added additional smartmonattrs

---

Makefile

The all target should abort on incorrectly formatted code, instead of
formatting it. The CI pipeline should fail and not silently accept
wrong code.
Signed-off-by: Tobias Schmidt <tobidt@gmail.com>
This regression was introduced in 158200f.

Fix code style check in "all" make target

---

collector/fixtures/e2e-ppc64le-output.txt

Update ppc64 fixtures to unbreak end-to-end.

---

collector/fixtures/e2e-output.txt
collector/netdev_linux.go

header for transmit traffic is differs from recieve, so we cannot use recieve header as transmit, now we can see carier and colls metrics in prometheus
```
root@dimon-note:~# cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
wlp3s0:  615351    3633    0    0    0     0          0         0   139984     968    0    0    0     0       0          0
lo:  626743    3507    0    0    0     0          0         0   626743    3507    0    0    0     0       0          0
enp2s0: 137449283  136651    0    0    0     0          0      1718 32085642   98565    0    0    0     0       0          0
tun0: 8585664   20643    0    0    0 …
```

fix netdev collector for linux

---

Makefile

Make sure we cleanup the sys fixtures before unpacking to avoid obsolete
files and conflicts from sticking around.
Closes: https://github.com/prometheus/node_exporter/issues/892

Cleanup sys fixtures before unpacking

---

collector/filesystem_freebsd.go

Fixes this crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x82879d]
goroutine 10 [running]:
runtime: unexpected return pc for github.com/prometheus/node_exporter/collector.(*filesystemCollector).GetStats called from 0x0
stack: frame={sp:0xc42019d810, fp:0xc42019fac8} stack=[0xc42019c000,0xc4201a0000)
000000c42019d710:  00000008016284d0  0100000000453630 
000000c42019d720:  0000000000000000  0000000000000001 
.....
000000c42019dff0:  0000000000000000  0000000000000000 
000000c42019e000:  0000000000000000  0000000000000000 
github.com/prometheus/node_exporter/collector.(*filesystemCollector).GetStats(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/home/juergen/go/src/github.com/prometheus/node_exporter/collec …
```

Fix memory corruption when number of filesystems > 16

---

.circleci/config.yml

Workaround CGO bugs in 1.10.1.

Use Go 1.9 for build.

---

collector/cpu_common.go
collector/cpu_darwin.go
collector/cpu_dragonfly.go
collector/cpu_freebsd.go
collector/cpu_linux.go
collector/cpu_openbsd.go
collector/qdisc_linux.go

Hi @SuperQ,
I fixed some trivial [golint](https://github.com/golang/lint) issues. See,
```
collector/cpu_common.go:27:2:warning: var nodeCpuSecondsDesc should be nodeCPUSecondsDesc (golint)
collector/cpu_linux.go:188:25:warning: don't use underscores in Go names; range var core_map should be coreMap (golint)
collector/qdisc_linux.go:44:1:warning: exported function NewQdiscStatCollector should have comment or be unexported (golint)
```

Fix some golint issues

---

collector/collector.go
collector/cpu_linux.go
collector/textfile.go

Hi @SuperQ,
I removed and commented out some **unused** functions, variables, and constants.
See,
```
$ gometalinter --enable-gc --vendor --deadline 10m --disable-all --enable=unused ./...
collector/collector.go:45:6:warning: func warnDeprecated is unused (U1000) (unused)
collector/cpu_linux.go:32:2:warning: var digitRegexp is unused (U1000) (unused)
collector/supervisord.go:84:3:warning: const STOPPED is unused (U1000) (unused)
collector/supervisord.go:87:3:warning: const BACKOFF is unused (U1000) (unused)
collector/supervisord.go:89:3:warning: const EXITED is unused (U1000) (unused)
collector/supervisord.go:90:3:warning: const FATAL is unused (U1000) (unused)
collector/supervisord.go:91:3:warning: const UNKNOWN is unused (U1000) (unused)
collector/textfile.go:37:2:warning: var …
```

remove or comment unused func, var, and const

---

collector/diskstats_darwin.go

Signed-off-by: Steve Kotsopoulos <sk@fywss.com>

align Darwin disk stat names with Linux

---

text_collector_examples/directory-size.sh

The directory size text collector example uses the wrong metric name in the HELP and TYPE lines rendering the comments unusable.
This fixes that by using the same metric name.
@SuperQ

Fix metric name in directory size text collector example

---

text_collector_examples/deleted_libraries.py

Add metrics that count how many running processes are linking to deleted
libraries on each machine. Deleted libraries are usually outdated
libraries, and outdated libraries may have known security
vulnerabilities.
The rationale behind storing these as metrics is allow the rollout of
security fixes to be tracked across a fleet of machines, ensuring that
all affected processes are restarted (e.g. via a reboot).
I'm parsing the output from `/proc/*/maps` because it's using `lsof -d
DEL` can be too slow, particularly if you have sockets that bind to
thousands of IP addresses.
The metric labels include the library path and the base filename, which
allows us to pinpoint the exact path of the deleted library but also
allows us to aggregate on the library name (or approximations of it)
even if …

Add metric for outdated libraries

---

collector/cpu_freebsd.go

Added a type conversion to cpu temperature sysctl.  Will still collect/report -1 when the value is -1, this is because it should be up to interpretation whether this is the correct value for the system or not.
Some drivers will report -1 for cpu temperature.  Other sensors will report "an input into the fan control algorithm", i.e. not the actual temperature, but how much fan it wants.  Some people cool their machines
with liquid nitrogen.
Closes: https://github.com/prometheus/node_exporter/issues/945

Fix for #945, cpu temperature is signed.

---

text_collector_examples/ipmitool

'Celsius' should be spelt with an 's':
https://en.wikipedia.org/wiki/Celsius

Fix spelling of celsius in IPMI example script

---

docs/V0_16_UPGRADE_GUIDE.md
docs/example-16-compatibility-rules-new-to-old.yml
docs/example-16-compatibility-rules.yml

Hello people! 
Seems like there's a misconfiguration in the rules for the backward compatibility between node_exporters < 1.16 and 1.16. 
As said in the changelog  - `node_cpu_seconds_total` is a new metric name, and the `node_cpu` is the old one, so they should be put vice-versa.

Add example of translating new metrics to old format in case of migration to 1.16 version

---

text_collector_examples/smartmon.sh

output for scsi disk
$ /usr/sbin/smartctl -A -d scsi /dev/sdc
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.4.0-92-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF READ SMART DATA SECTION ===
Current Drive Temperature: 37 C
Drive Trip Temperature: 60 C
Manufactured in week 06 of year 2017
Specified cycle count over device lifetime: 10000
Accumulated start-stop cycles: 47
Specified load-unload count over device lifetime: 300000
Accumulated load-unload cycles: 177
Elements in grown defect list: 0
Vendor (Seagate) cache information
Blocks sent to initiator = 2400162880
Blocks received from initiator = 3175550757
Blocks read from cache and sent to initiator = 41978586
Number of read and write commands whose size <= segment size = …

added scsi smart data to prometheus exporter

---

CHANGELOG.md
collector/systemd_linux.go

`.service` units increment this counter any time the Restart= condition is
triggered.

Add support for NRestarts counter introduced in systemd 235

---

collector/filesystem_linux.go

This PR is meant to handle some of the issues mentioned in https://github.com/prometheus/node_exporter/issues/868 and https://github.com/prometheus/node_exporter/issues/244. What this attempts to do is stop monitoring an NFS mount if it doesn't return from the stat call. For each a mount a channel is created that acts like a lock for the mount point. If, when scraped, the channel can't accept, it means that the previous call to stat the mount never returned, so the mount point is skipped over. Once that "stuck" mount point recovers it will write to the channel and monitoring will resume for that mount point.
I know one of biggest issues with this kind of approach was that the exporter is supposed to be stateless and this will introduce some state. But I feel the benefits of being able to …

Changed the way that stuck NFS mounts are handled.

---

collector/filesystem_common.go
collector/filesystem_linux.go

Fixes #591 with the approach discussed by @SuperQ and @discordianfish
I verified that this exports correctly on a very troubled test machine.

Use /proc/mounts instead of statfs(2) for ro state

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/wifi/wlan0/stationinfo.json
collector/wifi_linux.go
vendor/github.com/mdlayher/wifi/client.go
vendor/github.com/mdlayher/wifi/client_linux.go
vendor/github.com/mdlayher/wifi/client_others.go
vendor/github.com/mdlayher/wifi/wifi.go
vendor/vendor.json

Signed-off-by: neiledgar <neil.edgar@btinternet.com>

Update wifi stats to support multiple stations (#977)

---

CHANGELOG.md
collector/systemd_linux.go

The no longer available `systemd_exporter` provided uptime metrics for systemd services, as such I figured I'd propose this as an extension to `node_epxorter`.
This is somewhat relevant to #562 in that it exposes how long a service has been running for, not quite the timestamp of its start.
Exporting the duration makes it easier to define alerts on this metric in my opinion and would retain the functionality as provided by the previous project.

Add systemd uptime metric collection

---

CHANGELOG.md
collector/systemd_linux.go

fixes #567
Signed-off-by: xginn8 <mamcgi@gmail.com>

Filter out uninstalled systemd units when collecting all units

---

Makefile

Fix override of make docker target to include new `DOCKER_REPO`
variable pattern.

Fix docker build

---

collector/filesystem_linux.go

It is quite common to put /var/lib/docker itself on a separate partition and that should be monitored as well.
This would resolve #1000.

Exclude only subdirectories of /var/lib/docker

---

collector/systemd_linux_test.go

The staticcheck tools seems to have been modified to include a new check which validates regexps and bails out if they contain no meta characters (e.g. they are static strings) [1].
The systemd test case uses such a regexp, staticcheck detects that and this breaks the build.
~~This PR adds the relevant file+check to the ignore list in the Makefile and fixes #1025.~~
This PR circumvents that by anchoring the regexp pattern. This fixes #1025.
[1] https://github.com/dominikh/go-tools/blob/master/cmd/staticcheck/docs/checks/SA6004 says 2018-07-28 even if the relevant commit timestamp is from 2017.

build: Fix staticcheck failure due to test regexp #1025

---

CHANGELOG.md
collector/wifi_linux.go

Disable the wifi collector by default due to suspected cashing issues and goroutine leaks.
* https://github.com/prometheus/node_exporter/issues/870
* https://github.com/prometheus/node_exporter/issues/1008

Disable wifi collector by default

---

CHANGELOG.md
collector/processes_linux.go

PIDs can vanish (exit) from /proc/ between gathering the list of PIDs
and getting all of their stats.
* Ignore file not found errors.
* Explicitly count the PIDs we find.
* Cleanup some error style issues.
Fixes: https://github.com/prometheus/node_exporter/issues/1042

Handle vanishing PIDs

---

CHANGELOG.md
collector/systemd_linux.go

Pulled from #1036. The latest systemd in our CentOS is not new enough to have NRestarts so this effectively means the systemd collector cannot collect any services. Instead of ignoring a service without NRestarts, just log and leave it at 0.
Fixes: https://github.com/prometheus/node_exporter/issues/567

Don't ignore unit if NRestarts isn't available

---

vendor/github.com/mdlayher/genetlink/conn.go
vendor/github.com/mdlayher/genetlink/family_linux.go
vendor/github.com/mdlayher/netlink/attribute.go
vendor/github.com/mdlayher/netlink/conn.go
vendor/github.com/mdlayher/netlink/conn_linux.go
vendor/github.com/mdlayher/netlink/conn_others.go
vendor/github.com/mdlayher/netlink/debug.go
vendor/github.com/mdlayher/netlink/doc.go
vendor/github.com/mdlayher/netlink/nlenc/endian.go
vendor/vendor.json

We're dealing with a possible Go runtime bug as part of https://github.com/prometheus/node_exporter/issues/870, so this updates the wifi dependency to a patch I've had some luck with that seems to stop the potential bad runtime interaction found in: https://github.com/golang/go/issues/25128.
The key point is that the OS thread is now unlocked before a netlink connection is terminated.

vendor: bump github.com/mdlayher/wifi and dependencies

---

text_collector_examples/md_info.sh

Add metrics that expose more information about MD RAID devices and
disks:
- the RAID level in use
- the RAID set that a disk belongs to
This allows for things like alert on unusually high I/O
utilisation for a disk compared to other disks in the same RAID set,
which usually means the disk is failing, and for comparing
write/read latency across RAID sets.
Output looks like:
node_md_disk_info{disk_device="/dev/dm-0", md_device="md1", md_set="A"} 1
node_md_disk_info{disk_device="/dev/dm-3", md_device="md1", md_set="B"} 1
node_md_disk_info{disk_device="/dev/dm-2", md_device="md1", md_set="A"} 1
node_md_disk_info{disk_device="/dev/dm-1", md_device="md1", md_set="B"} 1
node_md_disk_info{disk_device="/dev/dm-4", md_device="md1", md_set="A"} 1
node_md_disk_info{disk_device="/dev/dm-5", …

Add metrics exposing extended md RAID info

---

collector/loadavg_solaris.go

This is a fix for issue #1017 
@discordianfish You reviewed my previous SmartOS PR https://github.com/prometheus/node_exporter/pull/762 Can you take a look again?
I apologize if I created a pile of notifications trying to get my commit username correct.

Fix SmartOS build #1017

---

collector/diskstats_linux.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt

@SuperQ @languitar 
Fix typo on unit description of metric `*read_time_seconds_total` from milliseconds to seconds.

Fix typo on description of read_time_seconds_total

---

CHANGELOG.md
collector/meminfo.go
collector/meminfo_darwin.go

* Cast stats to float64 before doing math on them to avoid integer
wrapping.
* Remove invalid `_total` suffix from gauge values.
Fixes: https://github.com/prometheus/node_exporter/issues/855

Correctly cast Darwin memory info

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
vendor/github.com/prometheus/client_golang/prometheus/collector.go
vendor/github.com/prometheus/client_golang/prometheus/desc.go
vendor/github.com/prometheus/client_golang/prometheus/doc.go
vendor/github.com/prometheus/client_golang/prometheus/fnv.go
vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
vendor/github.com/prometheus/client_golang/prometheus/histogram.go
vendor/github.com/prometheus/client_golang/prometheus/http.go
vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
vendor/github.com/prometheus/client_golang/prometheus/labels.go
vendor/github.com/prometheus/client_golang/prometheus/metric.go
vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
vendor/github.com/prometheus/client_golang/prometheus/registry.go
vendor/github.com/prometheus/client_golang/prometheus/summary.go
vendor/github.com/prometheus/client_golang/prometheus/value.go
vendor/github.com/prometheus/client_golang/prometheus/vec.go
vendor/github.com/prometheus/client_golang/prometheus/wrap.go
vendor/vendor.json

@SuperQ Similar to https://github.com/prometheus/pushgateway/pull/204 , this is meant to use the current client_golang code in a large exporter to make sure it is sane before declaring the long awaited v0.9 release.
As it appears, node_exporter was already pretty much up-to-date WRT deprecated types in client_golang. So I didn't change anything except updating the e2e-output.txt fixture. If you think there is anything else about client_golang usage we could/should do now, let me know.

Update vendoring for client_golang and friends

---

text_collector_examples/smartmon.sh
text_collector_examples/storcli.py

Reworked the example files for smartmon and storcli.
The present files didn't expose enough metrics for us - so I enhanced the parsing without calling any more system functions. Thus the load on the systems should stay the same.
For the `smartmon.sh` script it is 100% backwards compatible,
the `storcli.py` loses the following metrics - which were moved into the VD/PD section (so they are now more specific):
- megaraid_emergency_hot_spare
- megaraid_virtual_drives_optimal
- megaraid_drive_groups_optimal

textfile example script rework

---

collector/timex.go

This removes the cgo import from timex collector, as it was only used
to define two constants. Those are part of the Linux kernel<->userspace
interface, thus there is no need to depend on libc to source them:
https://github.com/torvalds/linux/blob/v4.18/include/uapi/linux/timex.h
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>

collector/timex: remove cgo dependency

---

CHANGELOG.md
collector/systemd_linux.go
collector/systemd_linux_test.go

Get all units from systemd and filter in Go.
* Improves compatibility with older versions of systemd.
* Improve debugging by printing when units pass the filter.
* Remove extraneous newlines from log messages.
Fixes: https://github.com/prometheus/node_exporter/issues/1075

Change systemd unit filtering

---

collector/filesystem_linux.go

When starting Docker containers a whole bunch of netns (network namespace) mounts are created that the node exporter can't make any sense of (and can't read either).
This ignores the Docker specific mounts under `/run/docker/netns`.
Fixes #875

filesystem: Ignore Docker netns mounts

---

CHANGELOG.md
collector/cpu_openbsd.go

Starting with (not yet released) OpenBSD 6.4, sysctl KERN_CPTIME2 will
return ENODEV for offline CPUs.
SMT siblings are reported as offline when hw.smt is disabled, which is
the default since one of the later Spectre variants. So this might
affect a few systems.
For more details see:
https://cvsweb.openbsd.org/src/sys/kern/kern_sysctl.c#rev1.348
Signed-off-by: Ralf Horstmann <ralf@ackstorm.de>

Update cpu collector for OpenBSD 6.4

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
collector/infiniband_linux.go
collector/infiniband_linux_test.go

Hi,
PTAL. This should be "handling" #966, where the Intel iWARP RDMA modules are reporting **N/A (no PMA)** instead of an integer. I added an example to the fixtures, and the end to end tests.

infiniband: Handle iWARP* RDMA modules N/A

---

vendor/github.com/prometheus/client_golang/prometheus/collector.go
vendor/github.com/prometheus/client_golang/prometheus/histogram.go
vendor/github.com/prometheus/client_golang/prometheus/registry.go
vendor/vendor.json

This is mostly required to fix a bug with histograms on 32bit platforms.
(Which might or might not be used in node_exporter. Just in case...)
Signed-off-by: beorn7 <beorn@soundcloud.com>

Update prometheus/client_golang vendoring

---

examples/launchctl/README.md

LaunchDaemons are the correct way to create services that are restart proof.
There is now only a single destination place mentioned in the readme for the plist file.
Signed-off-by: Dávid Balakirev <dave00ster@gmail.com>
@SuperQ, @discordianfish if one of you could have a look please.

launchctl example based on LaunchDaemons

---

collector/cpu_linux.go
collector/fixtures/sys.ttar

* Update Linux cpufreq collector to use new procfs library functions.
* Split thermal throttle collection to a separate function.
* Add new required fixtures and repack ttar file.
Closes: https://github.com/prometheus/node_exporter/issues/644

Update cpufreq metrics collector

---

collector/zfs_linux.go

```
collector/zfs_linux.go:32:2: don't use ALL_CAPS in Go names; use CamelCase
collector/zfs_linux.go:33:2: don't use ALL_CAPS in Go names; use CamelCase
collector/zfs_linux.go:34:2: don't use ALL_CAPS in Go names; use CamelCase
collector/zfs_linux.go:35:2: don't use ALL_CAPS in Go names; use CamelCase
collector/zfs_linux.go:36:2: don't use ALL_CAPS in Go names; use CamelCase
collector/zfs_linux.go:37:2: don't use ALL_CAPS in Go names; use CamelCase
collector/zfs_linux.go:38:2: don't use ALL_CAPS in Go names; use CamelCase
collector/zfs_linux.go:39:2: don't use ALL_CAPS in Go names; use CamelCase
```
Interestingly, most of these aren't used.  I wouldn't object to removing them.

collector: fix golint problems in ZFS collector

---

collector/filesystem_linux.go
collector/filesystem_linux_test.go

Previously, this code could panic and take down node_exporter if the info was malformed.

collector: add bounds check and test for filesystem collector

---

collector/collector.go

Solves a golint issue:
```
collector/collector.go:79:43: exported func NewNodeCollector returns unexported type *collector.nodeCollector, which can be annoying to use
```
I also considered returning `prometheus.Collector`, but since the Collectors field is called elsewhere, this is the more correct solution IMO.

collector: export NodeCollector for documentation purposes

---

docs/example-16-compatibility-rules.yml

Some missing compatibility rules for
- node_time -> node_time_seconds
- node_memory_ShmemHugePages -> node_memory_ShmemHugePages_bytes
- node_memory_ShmemPmdMapped -> node_memory_ShmemPmdMapped_bytes

Add more compat rules

---

CHANGELOG.md
collector/netstat_linux.go

Tcp SYN packet retransmits are a very useful signal as they affect
network performance disproportionately to regular TCP retransmits.
Closes: https://github.com/prometheus/node_exporter/issues/1023

Add TCPSynRetrans to netstat default filter

---

CHANGELOG.md
collector/systemd_linux.go

Adds the current and max tasks for a systemd unit. LGTY @SuperQ?
Signed-off-by: Arno Uhlig <arno.uhlig@sap.com>

[systemd] collect taskCurrent, tasksMax per systemd unit

---

examples/init.d/node_exporter

CLI flags use two dashes instead of one since v0.15.0
Fixes #1156
Signed-off-by: Paul Gier <pgier@redhat.com>

examples/init.d: fix web.listen-address flag

---

collector/cpu_dragonfly.go
collector/memory_bsd.go

Discussion was here:
https://github.com/prometheus/node_exporter/issues/1127

Check BSD's mib which accounts for swap size

---

CHANGELOG.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/wifi_linux.go

This commit add transmit/receive bytes total for the wifi collector (which is not enabled by default). The `wifi` package by @mdlayher already collects those values but they were not sent to prometheus, that's why the change is fairly trivial.
I currently need those values for our monitoring setup. Are you happy to have them added as is?
If not, what do you think the best solution would be?
cc @SuperQ
(the contributors guide says to mention someone, but I wasn't sure who given that this collector was written by @mdlayher)

Add receive/transmit bytes total metric (wifi collector).

---

collector/cpu_dragonfly.go

I have confirmed this simple unit change works fine with following step:
1. Run `cat /dev/urandom | gzip -c > /dev/null` as many as the number of cores (it was 4 here)
2. Confirm `(sum(irate(node_cpu_seconds_total{}[5m])) - sum(irate(node_cpu_seconds_total{mode="idle"}[5m])))` reports similar number as above (was completely same to 4 in grafana dashborad)
3. Kill one of those processes and confirm it decrease around 1
4. Do 3 until no 2's processes alive
Fixes: https://github.com/prometheus/node_exporter/issues/1129

 Change Dfly's CPU counting frequency

---

text_collector_examples/storcli.py

We use the output-compatible perccli and storcli.py does not handle 'Unknown' as a result:
```
sg="Error parsing \"/var/lib/node_exporter/perccli.prom\": text format parsing error in line 222: expected float as value, got \"Unknown\"" source="textfile.go:212"
```
I know, the perccli should not return 'Unknown' but this error breaks all other useful measurements because the prom file is not parsable. My if condition fixes this.

Handle 'Unknown' as measurement value.

---

collector/filesystem_linux.go

The pull request #1002 changed the logic used on Linux servers to determine if a filesystem is
read-only. As a result of this change, the variable `readOnly` is now unused and can be removed.
Signed-off-by: Jerome Froelich <jeromefroelich@hotmail.com>

Remove unused variable readOnly from filesystem_linux.go

---

CHANGELOG.md
collector/filesystem_linux.go
collector/filesystem_linux_test.go
collector/fixtures_hidepid/proc/mounts

On some systems, `/proc/1/mounts` is hidden from non-root users due to
the `hidepid` procfs feature. Attempt to fallback to `/proc/mounts` if
`/proc/1/mounts` is not found.
Fixes: https://github.com/prometheus/node_exporter/issues/1171

Add fallback for missing /proc/1/mounts

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/netstat_linux.go

In order to get a better idea of TCP packet loss, we need to know how
many `node_netstat_Tcp_OutSegs` there are so we can compare this to
`node_netstat_Tcp_RetransSegs`.

netstat: Add TCP In/Out Segs

---

text_collector_examples/smartmon.sh

Add this new metric (where sda is active and sdb is in standby mode):
smartmon_device_active{disk="/dev/sda",type="sat"} 1
smartmon_device_active{disk="/dev/sdb",type="sat"} 0
Also skip further metrics if the drive is in a low-power mode. This
prevents spinning up disks just to get the metrics (which matches e.g.
debian's default behavior for smartd).
Signed-off-by: Andre Heider <a.heider@gmail.com>

smartmon.sh: add metric for active/low-power mode

---

Makefile

Adding $(PROMTOOL) to .PHONY makes it impossible to provide an alternative path
to promtool.

Do not use .PHONY for $(PROMTOOL)

---

CHANGELOG.md
README.md
collector/boot_time_solaris.go
collector/cpu_solaris.go
collector/loadavg_solaris.go
collector/zfs_solaris.go
go.mod
go.sum
vendor/modules.txt

Added `kstat` based Solaris metrics, adds:
* boottime
* cpu
* zfs
Tested on `OpenIndiana Hipster 2018.10`.
Closes: https://github.com/prometheus/node_exporter/issues/1208

Add kstat-based Solaris metrics

---

collector/paths.go

It's a nitpick, but this is technically correct:
> The path package should only be used for paths separated by forward slashes, such as the paths in URLs. This package does not deal with Windows paths with drive letters or backslashes; to manipulate operating system paths, use the path/filepath package.
One of the VSCode tools also set the kingpin import name.

collector: use path/filepath for handling file paths

---

collector/systemd_linux.go

Adds a new label called "type" systemd_unit_state which contains the Type field from the unit file.  Applies only to the .service and .mount unit types.  The other unit types do not include a job type.
Fixes #1210

collector/systemd: add new label "type" for systemd_unit_state

---

text_collector_examples/storcli.py

Signed-off-by: Matt Pursley <mpursley@gmail.com>
This commit adds the physical disk "state" to megaraid_pd_info metric.  Seems like the "state" of a disk is very important to include, as this is the best way to tell if a disk is in a bad state (e.g. failed, unassigned, etc.)
Here's an example of the metric with this label included... 
megaraid_pd_info{controller="1",enclosure="25",slot="3",disk_id="16",interface="SAS",media="HDD",model="ST4000NM0023",DG="0",state="Onln",firmware="GS0F"} 1.0
megaraid_pd_info{controller="1",enclosure="25",slot="4",disk_id="26",interface="SAS",media="HDD",model="ST4000NM0295",DG="0",state="DHS",firmware="DT31"} 1.0
@SuperQ @discordianfish Please review

add physical disk "state" to megaraid_pd_info metric

---

Makefile

In #1232 the Makefile was cleaned up but it looks like the `ifeq ($(OS_detected), Linux)` wasn't correctly changed to match `linux` when using `GOHOSTOS`.
@SuperQ @pgier

Fixed capitalization of linux in Makefile

---

CHANGELOG.md
README.md
collector/uname.go
collector/uname_freebsd.go
collector/uname_linux.go

This PR implements the uname collector for FreeBSD.
- Breaks out the common part into `uname.go`
- Adds a `uname` type which is a `struct` of strings named after their `unix.Utsname` counterparts.
- OS specific methods return the `uname` for consumption by the collector in `uname.go`
- Leaves the Linux collector in `uname_linux.go`
- Adds a FreeBSD collector in `uname_freebsd.go`
FreeBSD does not have a `uname.Domainname` like Linux, so we attempt to emulate it in order to enable comparing `node_uname_info` across operating systems. Perhaps a user wants to count all nodes under a specific domainname, etc.
In the event a domain name cannot be split out of the `uname.Nodename`, we set the domainname to `(none)`, which appears to be what happens on Linux when uname doesn't know the …

collector: Implement uname collector for FreeBSD

---

CHANGELOG.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/netclass_linux.go

This moves the variable label values such as 'operstate' out of
the 'network_up' metric and into a separate metric called '_info'.
This allows the 'up' metric to remain continous over state changes.
Fixes #1236
Signed-off-by: Paul Gier <pgier@redhat.com>

netclass_linux: remove varying labels from the 'up' metric

---

CHANGELOG.md
collector/bonding_linux.go
collector/fixtures/sys.ttar

With a bond interface the state of the slave interface from the bond's
point of view is reflected in `mii_status` and is independent of the
link's `operstate`.
When a bond is monitored with `miimon`, `mii_status` will reflect the
state of the physical link as configured via the operator.
When a bond is monitored via `arp_interval` the `mii_status` will
reflect the results of the bond ARP checking.  This means the link can
be down from the bond's point of view, but up from a physical
connection point of view.
If a bond is not monitored via miimon or arp, the `mii_status` should
likely be always `up`, however I have observed a case where this is not
true and the `operstate` is `up` while `mii_status` is `down`.  Kernel
bond documentation stresses that a bond should not be configured without …

collector/bonding_linux: Monitor bond mii_status not link operstate

---

CHANGELOG.md
collector/systemd_linux.go
collector/systemd_linux_test.go

The purpose of this change is primarily to address issue #1201.  The
addition of several new systemd metrics in v0.17.0
(pr #1098, #968, #992, #952) caused the overall collection time
to increase by about a factor of 10.  The increase is not due
to any particular change, just a consequence of making a lot
more calls over dbus.
The two main design changes here are (1) turn off many of the dbus
metrics by default and (2) execute dbus calls in parallel to speed up
collection.  This also organizes metric collection closer to how the
data is organized in systemd.  And it gathers metrics which are specific
to "service" unit types in bulk instead of making three separate calls
for TasksMax, TasksCurrent, and NRestarts.  This bulk request also allows
for enabling more service unit data in the …

Systemd refactor

---

CHANGELOG.md
collector/systemd_linux.go

Include additional unit types in the default systemd collector
blacklist.
Closes: https://github.com/prometheus/node_exporter/issues/1251

Update systemd blacklist

---

CHANGELOG.md
README.md
collector/cpu_linux.go
collector/cpu_solaris.go
collector/cpufreq_linux.go
collector/cpufreq_solaris.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
end-to-end-test.sh

The cpu frequency information is not always needed and/or available.  This change allows the cpu frequency metrics to be enabled/disabled separately from the other cpu metrics, and also prevents a frequency metric failure (such as a parse error) from failing the main cpu collector.
Fixes #1241

collector/cpu: split cpu frequency into separate collector

---

text_collector_examples/ipmitool

This flag causes no ipmi data to be emitted and an error log is generated on each invocation: "awk: not an option: -nf".
I was unable to locate a "-n" flag in the mawk or gawk man pages, so I tested it by manually changing the script on a running Debian buster system.  The issue was resolved and metrics were emitted.

remove "-n" flag from /usr/bin/awk in ipmitool text collector example

---

text_collector_examples/inotify-instances

This is an alternative take on the embedded inotify collector:
https://github.com/prometheus/node_exporter/pull/988
The proposed embedded collector was not accepted for inclusion because
it was not possible for a single unprivileged node_exporter process to
detect inotify resource utilisation in other user domains.
This text collector works around the problem by giving the operator a
choice between the following:
- Run only the text collector as root to gain visibility over all
processes on the system.
- Run one or more instances of the text collector as an unprivileged
user to gain visibility over subsets of the system.
In either case, the data generated by this collector can be useful when
hunting down inotify instance leaks -- and when confirming the
resolution of such leaks.

Add the inotify-instances text collector

---

text_collector_examples/yum.sh

Added example of simple yum update monitor for CentOS. Based on `apt.sh`.
```
[root ~]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)
[root ~]# ./yum.sh
yum_updates_pending{origin="base"} 128
yum_updates_pending{origin="updates"} 14
```

yum.sh: yum update monitor

---

go.mod
go.sum
vendor/github.com/godbus/dbus/conn.go
vendor/github.com/godbus/dbus/decoder.go
vendor/github.com/godbus/dbus/default_handler.go
vendor/github.com/godbus/dbus/object.go
vendor/github.com/godbus/dbus/transport_unix.go
vendor/modules.txt

Towards: https://github.com/prometheus/node_exporter/issues/1301
Update `github.com/godbus/dbus` to version with patch for the memory issue related to systemd units listing.

update github.com/godbus/dbus to latest master

---

collector/buddyinfo.go
collector/cpu_linux.go
collector/cpufreq_linux.go
collector/ipvs_linux.go
collector/netclass_linux.go
collector/processes_linux.go
collector/processes_linux_test.go
collector/stat_linux.go

Initialize the proc or sys fs once per collector instead of doing it on every update of the metrics.

Early init of procfs

---

.circleci/config.yml
.dockerignore
Dockerfile
Dockerfile.ppc64le
Makefile
Makefile.common

See https://github.com/prometheus/prometheus/pull/5031 for context.
Requires the following now repositories to be created:
- promu/node-exporter-arm32v7-linux
- promu/node-exporter-arm64v8-linux
- promu/node-exporter-ppc64le-linux
- quay.io/prometheus/node-exporter-arm32v7-linux
- quay.io/prometheus/node-exporter-arm64v8-linux
- quay.io/prometheus/node-exporter-ppc64le-linux
Fixes https://github.com/prometheus/node_exporter/issues/1034
Requires prometheus/busybox#19

Docker images for ARM32v7, ARM64v8 and ppc64le

---

CHANGELOG.md
collector/textfile.go

Previously, the node_textfile_mtime_seconds metric was based on the Fileinfo.ModTime() of the ioutil.ReadDir() return value. This is based on lstat() and therefore has unintended consequences for symlinks (modification time of the symlink instead of the symlink target is
returned). It is also racy as the lstat() is performed before reading the file.
This commit changes the node_textfile_mtime_seconds metric to be based on a fresh Stat() call on the open file.  This eliminates the race and works as expected for symlinks. Fixes #1324.

textfile: use opened file's mtime as timestamp

---

CHANGELOG.md
collector/netdev_darwin.go

Avoid 32-bit counter rollovers.
Closes: https://github.com/prometheus/node_exporter/issues/1318

Use 64-bit Darwin netstat counters

---

collector/uname.go

Make collector a pointer for consistency.
Fixes: https://github.com/prometheus/node_exporter/issues/1300

Cleanup uname Update call

---

CHANGELOG.md
collector/memory_bsd.go

This PR fixes #1344 
The size of the `sysctl` call during the MIB name check was wrong, causing this check to fail on FreeBSD (and probably on DragonFly too, failure was expected there, but probably not this failure).
This PR fixes things so that the size of the sysctl call matches the documented `dataType` of `bsdSysctlTypeUint64` from the array of sysctls.

meminfo: Fix the size mismatch in the swapTotal check mib for BSD.

---

.circleci/config.yml
text_collector_examples/md_info_detail.sh

The latest codespell update appears to be finding some new issues.  This change fixes or ignores those errors as appropriate.

fix codespell warnings

---

text_collector_examples/btrfs_stats.py

Python 2.7 will not be maintained past 2020. Therefore upgrade `text_collector_examples/btrfs_stats.py` to Python 3.

btrfs_stats: Upgrade to Python 3

---

CHANGELOG.md
collector/netdev_bsd.go
collector/netdev_common.go
collector/netdev_darwin.go
collector/netdev_linux.go
collector/netdev_linux_test.go
collector/netdev_openbsd.go

Sometimes it is desired to monitor only one netdev. The golang regexp
does not support a negated regex, so the ignored-devices flag is too
cumbersome for this task.
This change introduces a new flag: accept-devices, which is mutually
exclusive to ignored-devices. This flag allows specifying ONLY the
netdev you'd like.
Signed-off-by: Noam Meltzer <noam@cynerio.co>

Add --collector.netdev.device-whitelist flag

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/10/mountstats
collector/mountstats_linux.go
go.mod
go.sum
vendor/github.com/prometheus/procfs/MAINTAINERS.md
vendor/github.com/prometheus/procfs/Makefile
vendor/github.com/prometheus/procfs/Makefile.common
vendor/github.com/prometheus/procfs/README.md
vendor/github.com/prometheus/procfs/fixtures.ttar
vendor/github.com/prometheus/procfs/fs.go
vendor/github.com/prometheus/procfs/mountstats.go
vendor/github.com/prometheus/procfs/net_dev.go
vendor/github.com/prometheus/procfs/net_unix.go
vendor/github.com/prometheus/procfs/nfs/parse.go
vendor/github.com/prometheus/procfs/proc_ns.go
vendor/github.com/prometheus/procfs/proc_status.go
vendor/github.com/prometheus/procfs/sysfs/clocksource.go
vendor/github.com/prometheus/procfs/ttar
vendor/modules.txt

* Update procfs vendor to pull in github.com/prometheus/procfs/pull/165
* Update mountstats collector to use new types.
* Rollover counter automatically to avoid float64 accuracy issues.
* Update e2e test.
Fixes: https://github.com/prometheus/node_exporter/issues/1363

Fix rollover bug in mountstats collector

---

text_collector_examples/storcli.py

@SuperQ
This is only a minor change to .format() arguments, and is useful on CentOS6 servers which have only python2.

Make storcli.py compatible with python2

---

text_collector_examples/apt.sh

Some repositories (eg: proxmox) have labels with spaces in it, which make the script fail.
Example with proxmox (`deb http://download.proxmox.com/debian/pve stretch pve-no-subscription`):
`Label: Proxmox Debian Repository`
```
apt_upgrades_pending{origin="Debian-Security:9/stable",arch="all"} 1
apt_upgrades_pending{origin="Debian-Security:9/stable",arch="amd64"} 6
apt_upgrades_pending{origin="ProxmoxDebian",arch="Repository:stable"} 1
```
After the commit in this PR:
```
apt_upgrades_pending{origin="Debian-Security:9/stable",arch="all"} 1
apt_upgrades_pending{origin="Debian-Security:9/stable",arch="amd64"} 6
apt_upgrades_pending{origin="ProxmoxDebianRepository:stable",arch="amd64"} 1
```

apt.sh: Account for spaces in repository label

---

collector/filesystem_linux.go

The filesystem is always read-only and is often used as a virtual FS with a "seed" configuration file for a VM in cloud environment.
So, I'm following the logic from #1104 about `squashfs` being read-only and suggest to add `iso9660` to default ignore-list as well.
The trigger for the PR was the fact that the FS never has any free space. So time series about this FS will likely trigger an alert about "seed" partition if the rule about disk space is fstype-agnostic.
/cc @discordianfish

Ignore iso9600 filesystem on Linux

---

CHANGELOG.md
collector/systemd_linux.go

Fixes the `node_systemd_service_restart_total` label for unit name from 'state' to 'name'. State doesn't really make sense here especially considering what the label is being set to:
```
ch <- prometheus.MustNewConstMetric(
c.nRestartsDesc, prometheus.CounterValue,
float64(restartsCount.Value.Value().(uint32)), unit.Name)
```

Fixes systemd restart counter label from state to name

---

text_collector_examples/multipathd_info

multipathd_info is a script that exposes device mapper multipathing
metrics from multipathd daemon.
Signed-off-by: Saket Sinha <saket.sinha@cloud.ionos.com>

Add mulitipathd_info text collector example

---

text_collector_examples/ipmitool

Hi,
```
VBAT             | 0x4        | discrete   | 0xxxxx| na        | na        | na        | na        | na        | na        
Chassis Intru    | 0x1        | discrete   | 0xxxxx| na        | na        | na        | na        | na        | na        
PS1 Status       | 0x1        | discrete   | 0xxxxx| na        | na        | na        | na        | na        | na        
PS2 Status       | 0x1        | discrete   | 0xxxxx| na        | na        | na        | na        | na        | na  
```
At least in our deployments, these metrics were all zero prometheus wouldn't accept the hex value. I used substr() to try to make it more portable. With this small fix, we get the right values:
```
node_ipmi_status{sensor="PS2 Status"} 1.000000
node_ipmi_status{sensor="PS1 Status"} 1.000000
```

FIX ipmitool sensor discrete values are expressed in hex

---

go.mod
go.sum
vendor/github.com/prometheus/procfs/fixtures.ttar
vendor/github.com/prometheus/procfs/proc.go
vendor/github.com/prometheus/procfs/proc_fdinfo.go
vendor/github.com/prometheus/procfs/sysfs/class_infiniband.go
vendor/github.com/prometheus/procfs/vm.go
vendor/modules.txt

procfs v0.0.4-0.20190627154503-39e1aff1547e is a requirement for https://github.com/prometheus/node_exporter/pull/1357 (because procfs v0.0.3 contained bug https://github.com/prometheus/procfs/pull/187)

Update procfs to v0.0.4-0.20190627154503-39e1aff1547e

---

collector/zfs_freebsd.go

Based on the solaris implementation.  There's a lot of other sysctls
available on FreeBSD that aren't reported here.  It'll be easy to add,
if they're useful.  All of the sysctls are uint64.

Added FreeBSD zfs support per #1063.

---

collector/tcpstat_linux.go
collector/tcpstat_linux_test.go

It will resolve  #1360
- read the `/proc/net/tcp` with single syscall by using `ioutil.ReadAll`.
- I think `sl  local_address rem_address ...` will always be the first line, so remove the check `strings.HasPrefix(parts[0], "sl")` in the loop.

read /proc/net files with a single read syscall

---

CHANGELOG.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/xfs_linux.go

Include directory operation and read/write system call metrics for XFS
filesystems.
Signed-off-by: Steven Kreuzer <skreuzer@FreeBSD.org>

Expose additional XFS runtime statistics

---

CHANGELOG.md
collector/filesystem_bsd.go
collector/filesystem_freebsd.go
collector/filesystem_linux.go
collector/filesystem_linux_test.go
collector/fixtures_bindmount/proc/mounts
collector/paths.go

Change-type: patch
Connects-to: #1418

properly strip path.rootfs from mountpoint labels

---

docs/node-mixin/dashboards/node.libsonnet

Possible way of fixing #1437
Additionally this is fixing incorrect query responsible for reporting disk space usage in "Nodes" dashboard.
This version is already applied in https://demo.cloudalchemy.org :)
/cc @beorn7 @SuperQ @metalmatze

docs/node-mixin: fix incorrect queries

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
node_exporter.go

As per prometheus/client_golang#543, pass the Registry for exporter
metrics when setting up the /metrics HTTP handler.
With this, the `promhttp_metric_handler_errors_total` metric will
increment on (possibly non-fatal) collection-time errors, such as
duplicate metrics from text files.
Signed-off-by: Matthias Rampke <mr@soundcloud.com>

Report non-fatal collection errors in the exporter metric.

---

CHANGELOG.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/10/mountinfo
collector/fixtures/proc/10/mountstats
collector/mountstats_linux.go

Use the extra information gleaned from the mountinfo file to add
a 'mountaddr' field for NFS metrics. This helps prevent prometheus from
ignoring mounts that come from the same URL, but are actually from
different IP addresses.
(PR #1400 closed accidentally after rebasing to master)

Added mountinfo changes to node_exporter

---

text_collector_examples/storcli.py

If you're using a JBOD setup (`storcli /c0/e1/s1 set jbod`) with 0 drive groups/virtual drives, the exporter crashes and doesn't output physical drives infos
This PR fixes it

Handle JBOD setup for storcli exporter

---

README.md
collector/uname.go
collector/uname_bsd.go

@SuperQ - mind taking a look. This partially Fixes #1222 
Adds uname support for Darwin and OpenBSD.
I built and tested the OpenBSD build flag in a vagrant box but didn't have as much luck with dragonfly and netbsd (have no *BSD experience and had trouble with the go tooling setup). 
Cross compiling on mac also fails for those two OS.
Looking at https://github.com/golang/sys/blob/master/unix/ztypes_netbsd_amd64.go#L457 and https://github.com/golang/sys/blob/master/unix/ztypes_dragonfly_amd64.go#L463 I think it might be safe to add those OS but omitted them since I was unable to test them.
Heres the output for the two additions below, I kept the same implementation that was in place for FreeBSD:
`uname && uname -n` : 
```
OpenBSD
openbsd64.expressvpn
```
--------------------
`uname && …

Extend uname collector

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/schedstat_linux.go
go.mod
go.sum
vendor/github.com/prometheus/procfs/fixtures.ttar
vendor/github.com/prometheus/procfs/internal/util/parse.go
vendor/github.com/prometheus/procfs/schedstat.go
vendor/github.com/prometheus/procfs/zoneinfo.go
vendor/modules.txt

Upstream bugfix: https://github.com/prometheus/procfs/pull/191
Signed-off-by: Phil Frost <phil@postmates.com>

Fix seconds reported by schedstat

---

docs/node-mixin/dashboards/node.libsonnet

- Use stacking where it makes sense.
- Normalize idle CPU so that stacking is more meaningful.
- Consistently fill where stacking is used but don't fill where not.
- Fix y axis max value for Idle CPU panel.
- Fix y axis min value for memory usage panel.
- Use `$__interval` for range where applicable (and set min step
to 1m).
- Make the right Y axis for disk I/O actually work.
This is just an incremental improvements. It doesn't touch the more
involved TODOs.
@metalmatze

node-mxin: Improve nodes dashboard

---

docs/node-mixin/alerts/alerts.libsonnet
docs/node-mixin/config.libsonnet

This addresses the blissful scenario where single-node failures are
unproblematic. No reason to wake somebody up if a node is about to
screw itself up by filling the disk.
@metalmatze

node-mixin: Make the severity of "critical" alerts configurable

---

CHANGELOG.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/ip_vs_result.txt
collector/fixtures/proc/net/ip_vs
collector/ipvs_linux.go
collector/ipvs_linux_test.go

A new PR that's basically the same as #764 plus covers remaining issue (also hopefully covers #1296)

Ipvs firewall mark

---

CHANGELOG.md
collector/systemd_linux.go

The dbus property 'SystemState' was added in version 212 of systemd.
Check that the version of systemd is higher than 212 before attempting
to query the SystemState property.
https://github.com/systemd/systemd/commit/f755e3b74b94296a534033dd6ae04d9506434210
Resolves issue #291

systemd: check version for availability of SystemState

---

CHANGELOG.md
collector/filesystem_linux_test.go
collector/fixtures_bindmount/proc/mounts
collector/paths.go

fix for issue #1463 and expanded test case to properly check this
Change-type: patch
Connects-to: #1463
Signed-off-by: Nick Payne <nickp@balena.io>

fix issue where rootfs path strips to the empty string

---

go.mod
go.sum
vendor/github.com/prometheus/procfs/buddyinfo.go
vendor/github.com/prometheus/procfs/cpuinfo.go
vendor/github.com/prometheus/procfs/fixtures.ttar
vendor/github.com/prometheus/procfs/proc_status.go
vendor/github.com/prometheus/procfs/schedstat.go
vendor/github.com/prometheus/procfs/sysfs/class_infiniband.go
vendor/github.com/prometheus/procfs/sysfs/class_power_supply.go
vendor/github.com/prometheus/procfs/sysfs/net_class.go
vendor/github.com/prometheus/procfs/sysfs/system_cpu.go
vendor/modules.txt

- Fixes: #1465 failure in netclass collector
- Adds parsing of CPU information

update procfs to v0.0.5

---

docs/node-mixin/alerts/alerts.libsonnet

Fix some `node-mixin` prometheus alert rules `expr` to use percentage instead of ratio, to be consistent with their `annotations`' unit (`%`). 
@SuperQ

Fix node-mixin prometheus alert rules to use percentage

---

docs/node-mixin/dashboards/use.libsonnet
docs/node-mixin/rules/rules.libsonnet

It's intended to show the rate of swap IOs, but it used the paging
metrics instead.
This commit replaces `node_vmstat_pgpgin` and `node_vmstat_pgpgout` with
`node_vmstat_pswpin` and `node_vmstat_pswpout` in the
`instance:node_memory_swap_io_pages:rate1m` recording rule.
See coreos/kube-prometheus#222.

docs/node-mixin: Fix node_memory_swap_io_pages rule

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
collector/powersupplyclass.go

Use the powerSupplyClass from `procfs` and show metrics about the power supplies from `/sys/class/power_supply` as wished in issue #676.
These changes are based in the commit 6ed1f7e1041181781dd2826d3001075d011a80cc in `procfs` and therefore the depedency is updated.

Introduce Collector for Power Supply Class

---

docs/node-mixin/config.libsonnet
docs/node-mixin/dashboards/use.libsonnet

We actually have to count or sum, respectively, _all_ the selected
metrics for the cluster-wide view. Which means it's easiest to use the
`scalar` approach after all (but only in the cluster dashboard). This
still propagates all the labels.
I have extended the comment for the `nodeExporterSelector` to note
that the cluster dashboard only makes sense if all the selected node
exporter actually belong to the same cluster.
Since this is jsonnet, users can easily disable the cluster
dashboard. Or even create multiple instances of the dashboards with
different `nodeExporterSelector`s for different clusters.
@metalmatze

Fix the normalization for the cluster-wide dashboards

---

docs/node-mixin/dashboards/use.libsonnet

This is completely breaking node-mixins as `jsonnetfmt` panics with:
```
$ jsonnetfmt -i use.libsonnet 
STATIC ERROR: use.libsonnet:20:11: text block syntax requires new line after |||.
```
/cc @beorn7 @s-urbaniak @metalmatze

docs/node-mixin/dashboards: do not mix tabs and spaces

---

collector/textfile.go

Deferring in a loop is generally a bad practice as it could leave an arbitrary number of file descriptors open for a long period of time, so I decided to refactor this and tidy it up some while I was at it.

collector: refactor textfile collector to avoid looping defer

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/infiniband_linux.go

Parsing the sysfs files for InfiniBand should be added to the procfs library (see https://github.com/prometheus/procfs/pull/164). Then also collect the InfiniBand port state, the physical state, and the maximum signal transfer rate.

Collect InfiniBand port state and physical state

---

collector/meminfo_openbsd.go

`node_exporter` always reports OpenBSD cache memory as zero[1]. After some investigation, it seems that the `sysctl` call isn't properly set[2].
This PR resolves that situation by using the same metric than OpenBSD's top(1).
Tested on OpenBSD/amd64 6.6
@SuperQ /  @discordianfish 
[1] `node_memory_cache_bytes{} = 0`
[2] https://github.com/openbsd/src/blob/master/sys/uvm/uvmexp.h#L61

Fix OpenBSD cache memory information

---

.circleci/config.yml
collector/bcache_linux.go
collector/buddyinfo.go
collector/cpu_linux.go
collector/cpufreq_linux.go
collector/infiniband_linux.go
collector/ipvs_linux.go
collector/mdadm_linux.go
collector/meminfo_openbsd.go
collector/mountstats_linux.go
collector/netclass_linux.go
collector/netdev_darwin.go
collector/nfs_linux.go
collector/nfsd_linux.go
collector/pressure_linux.go
collector/processes_linux.go
collector/schedstat_linux.go
collector/sockstat_linux.go
collector/stat_linux.go
collector/thermal_zone_linux.go
collector/timex.go
collector/wifi_linux.go
collector/xfs_linux.go

>  In Go 1.13, the fmt.Errorf function supports a new %w verb. When this verb is present, the error returned by fmt.Errorf will have an Unwrap method returning the argument of %w, which must be an error. In all other ways, %w is identical to %v.
https://blog.golang.org/go1.13-errors

Wrap errors

---

CHANGELOG.md
collector/netclass_linux.go

Integer division and the order of operations when converting Mbps to Bps
results in a loss of accuracy if the interface speeds are set low.
e.g. 100 Mbps is reported as 12000000 Bps, should be 12500000
10 Mbps is reported as 1000000 Bps, should be 1250000
This issue may crop up in environments w/ legacy networking equipment (e.g. 10BASE-T or 10BASE-TX), or when explicitly setting interface speeds to something low that wasn't auto-negotiated.

Fixed inaccurate 'node_network_speed_bytes' when speeds are low

---

CHANGELOG.md
collector/supervisord.go

For example:
--collector.supervisord.url=unix:///var/run/supervisor.sock
Fixes prometheus/node_exporter#262
Signed-off-by: Paul Cameron <cameronpm@gmail.com>

Add unix socket support for supervisord collector

---

CHANGELOG.md
README.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
collector/rapl_linux.go
end-to-end-test.sh

This adds metrics from procfs/sysfs powercap files.
Depends on a vendor/ (and go.mod) update, which is at the parent 57cd9ac. That patch probably needs to be carefully checked, I have never before updated these dependencies in any project.

RAPL collector

---

collector/infiniband_linux.go

Handle non-existent infiniband results silent.
Fixes: https://github.com/prometheus/node_exporter/issues/1511

Fix inifiband collector log noise

---

collector/systemd_linux.go

This requires root, so it shouldn't be used.
This closes #1246

systemd: Clarify private flag description

---

CHANGELOG.md
collector/btrfs_linux.go
collector/btrfs_linux_test.go
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
end-to-end-test.sh
vendor/github.com/prometheus/procfs/btrfs/btrfs.go
vendor/github.com/prometheus/procfs/btrfs/get.go
vendor/modules.txt

This PR adds a Btrfs collector using the changes contained in the PR for procfs (https://github.com/prometheus/procfs/pull/223).
Currently, only a few useful metrics are exported that can be used to calculate the allocation of the filesystem. Let me know if anything else is useful.
This PR is a draft pending a release containing the changes in `procfs`.
Resolves #1100

Add Btrfs collector

---

collector/meminfo_darwin.go

Exposing swap usage on MacOS.
node_memory_swap_used_bytes
node_memory_swap_free_bytes
node_memory_swap_total_bytes
Just made up the metric names following the lowercase notation of other darwin names, can change them if someone have better suggestions.
This is my first attempt to write anything in go, but the changes seems to work fine so would be nice to have this feature included in future releases.

Swap usage on darwin from sysctl vm.swapusage #1607

---

.golangci.yml
https/tls_config_test.go

* Enable golint in golangci-lint tests.
* Fix up minor linting issues.

Enable golint

---

docs/node-mixin/alerts/alerts.libsonnet
docs/node-mixin/config.libsonnet

This makes it possible to tweak the thresholds for the NodeFilesystemSpaceFillingUp alerts. Which might be necessary in systems like Kubernetes, where the image garbage collector runs at 85%, so it's not a problem that the disk reaches that usage %.
For context, this came from this issue in the `kube-prometheus` project: https://github.com/coreos/kube-prometheus/issues/294
cc @SuperQ @discordianfish 
Signed-off-by: iuri aranda <iuri@skyscrapers.eu>

Make FS space alerts thresholds configurable

---

collector/schedstat_linux.go

Suppres error log noise if schedstat file doesn't exist.

Catch missing schedstat file

---

CHANGELOG.md
collector/cpu_linux.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt

The `node_cpu_info` metric contains some information like the `model`
(which is an integer), but not the human readable model name. Also the
stepping of the processor might be interesting, since different stepping
of a processor might behave differently.

Add model_name and stepping to  node_cpu_info metric

---

docs/node-mixin/alerts/alerts.libsonnet

Add alert to detect the desynchronized clock.
300s is an arbitrary number based on maximum possible desynchronization between nodes for Kerberos setup. I am keen on lowering it based on some other data, but I couldn't find any better source.
For example OpenShift is using same alert but with a much tighter target of `0.05s`.
/cc @beorn7 @metalmatze

docs/node-mixin: alert on desynchronised clock

---

collector/systemd_linux.go

It should be backward compatible and work with version strings reported by systemd >=241.
Fixes #1646
Signed-off-by: paulfantom <pawel@krupa.net.pl>

collector/systemd: use regexp to extract systemd version

---

examples/systemd/README.md

The readme file does not mention the need to create a folder named
/var/lib/node_exporter/textfile_collector as a step. Lack of this
folder results errors for node_exporter service which is visible
in systemd status output. These errors possibly harmless but it is
not good to have them still.
$ sudo systemctl status node_exporter
--- snipped ---
Apr 04 14:51:35 ubuntu node_exporter[14713]: level=info ts=2020-04-04T14:51:35.584Z caller=node_exporter.go:190 msg="Listening on" address=:9100
Apr 04 15:05:34 ubuntu node_exporter[14876]: level=error ts=2020-04-04T15:05:34.464Z caller=textfile.go:197 collector=textfile msg="failed to read textfile collector directory" path=/var/lib/node_exporter/textfile_collector=textfile msg="failed to read textfile collector directory" …

Update systemd example readme file

---

docs/example-16-compatibility-rules-new-to-old.yml

Some missing compatibility rules for
* node_time -> node_time_seconds
* node_memory_ShmemHugePages -> node_memory_ShmemHugePages_bytes
* node_memory_ShmemPmdMapped -> node_memory_ShmemPmdMapped_bytes
This is related to #1138 pr. But the opposite case was not considered.

Add more compatible rules

---

README.md
collector/perf_linux.go
collector/perf_linux_test.go

This diff adds a new option for the perf collector by adding the `--collector.perf.tracepoints` flag. This will enable users to collect counters for any kernel tracepoint. This diff makes use of the [`TracepointEventAttr`](https://godoc.org/github.com/hodgesds/perf-utils#TracepointEventAttr) function for configuring tracepoints for profiling.

Add perf tracepoint collection flag

---

https/tls_config.go

We're looking to reuse this in Cortex to client side encrypt our
connections and not having this exposed is making us copy this entire
function.
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

Expose the function to generate tls.Config

---

collector/meminfo_linux.go

In CentOS Linux release 6.2 (Final), kernel 3.10.90, node exporter would come across the following error:
```
panic: runtime error: index out of range [1] with length 1
goroutine 1548 [running]:
github.com/prometheus/node_exporter/collector.parseMemInfo(0xbbd920, 0xc0000f4fc8, 0x0, 0xc000000000, 0xc0000f4fc8)
/Users/alpaca/Projects/prom-agent/vendor/github.com/prometheus/node_exporter/collector/meminfo_linux.go:50 +0x4d6
```
it is caused by empty lines read from /proc/meminfo. No idea why but there is a quick fix.
```
2020/04/10 09:52:49 !!!! DirectMap4k:      585388 kB
2020/04/10 09:52:49 !!!! DirectMap2M:    80119808 kB
2020/04/10 09:52:49 !!!! DirectMap1G:    53477376 kB
2020/04/10 09:52:49 !!!! 
panic: runtime error: index out of range [1] with length 1
```

Fix accidently empty lines in meminfo_linux

---

https/README.md
https/testdata/tls_config_auth_clientCAs_invalid.bad.yml
https/testdata/tls_config_auth_clientCAs_missing.bad.yml
https/testdata/tls_config_noAuth.bad.yml
https/testdata/tls_config_noAuth.good.blocking.yml
https/testdata/tls_config_noAuth.good.yml
https/testdata/tls_config_noAuth_certPath_empty.bad.yml
https/testdata/tls_config_noAuth_certPath_invalid.bad.yml
https/testdata/tls_config_noAuth_certPath_keyPath_empty.bad.yml
https/testdata/tls_config_noAuth_certPath_keyPath_invalid.bad.yml
https/testdata/tls_config_noAuth_keyPath_empty.bad.yml
https/testdata/tls_config_noAuth_keyPath_invalid.bad.yml
https/tls_config.go
https/web-config.yml

Make TLS config consistent with Prometheus

---

https/README.md
https/tls_config.go

TLS 1.0 and 1.1 are considered unsecure, while TLS 1.2 would imply that
we add more configuration variables, e.g. to pick cipher suites. TLS1.3
means that cipher suites are not configurable anyway.
Last releases of Prometheus support TLS 1.3 (since Prometheus 2.13).

TLS: only support TLS 1.2 / 1.3

---

examples/openwrt-init.d/node_exporter

MBOI - OpenWrt seems to use a lua script to 'fake' node_exporter; I thought why not run the full node exporter.  They have a 'different' init.d script system to the usual, but very little is needed.
Signed-off-by: Tom Wilkie <tom@grafana.com>

Add init.d script for OpenWrt.

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/spl/kstat/zfs/pool1/objset-1
collector/fixtures/proc/spl/kstat/zfs/pool1/objset-2
collector/fixtures/proc/spl/kstat/zfs/poolz1/objset-1
collector/fixtures/proc/spl/kstat/zfs/poolz1/objset-2
collector/zfs.go
collector/zfs_linux.go
collector/zfs_linux_test.go

For #1602 
Reading contents of each objset in each zpool.

read contents of objset file

---

.circleci/config.yml
CHANGELOG.md
collector/cpu_linux.go

Cache CPU metrics to avoid counters (ie iowait) jumping backwards.
Fixes: https://github.com/prometheus/node_exporter/issues/1686

Linux CPU: Cache CPU metrics

---

collector/meminfo_linux.go

Compile regexp outside of parsing function in meminfo_linux.go

Move regexp to global in meminfo_linux.go

---

collector/fixtures/ip_vs_result_lbs_local_address_local_port.txt
collector/fixtures/ip_vs_result_lbs_local_port.txt
collector/fixtures/ip_vs_result_lbs_none.txt
collector/ipvs_linux.go
collector/ipvs_linux_test.go

Fixes #1708
Signed-off-by: Wing924 <weihe924stephen@gmail.com>

add a flag to aggr ipvs metrics to avoid high cardinality metrics

---

Makefile
checkmetrics.sh

The checkmetrics target currently uses promtool v2.5.0 which doesn't
include many improvements done over the time. This change also
simplifies the promtool installation, avoiding a temporary directory by
extracting the file directly to the target destination.

Fix and simplify checkmetrics make target

---

collector/filesystem_freebsd.go
collector/helper.go
collector/helper_test.go

Fixes #1727 
We must know the length of the various filesystem C strings before
turning them from a byte array into a Go string, otherwise our Go
strings could contain null bytes, corrupting the label values.

filesystem_freebsd: Fix label values

---

collector/drbd_linux.go
collector/filesystem_linux_test.go
collector/kvm_bsd.go
collector/mountstats_linux.go
collector/nfs_linux.go
collector/nfsd_linux.go
collector/perf_linux.go
collector/schedstat_linux.go
collector/sysctl_bsd.go
collector/wifi_linux.go
collector/xfs_linux.go
collector/zfs_freebsd.go
collector/zfs_linux.go
collector/zfs_solaris.go

Existing build tags for collectors seems out of sync, and when I try to build for `freebsd` with build tag `noboottime noexec nomeminfo nonetdev nozfs nofilesystem` just fails with:
```txt
github.com/prometheus/node_exporter/collector/zfs_freebsd.go:24:12: undefined: bsdSysctl
github.com/prometheus/node_exporter/collector/zfs_freebsd.go:38:14: undefined: bsdSysctl
```
which is not the expected behavior I suppose, because zfs was included even with `nozfs` tag.
This PR is an attempt to fix collectors' build tags, and once merged, users should be able to build with/without specific collectors with correct build tags.
/cc @SuperQ @discordianfish

Fix build tags for collectors

---

CHANGELOG.md
collector/filesystem_common.go
collector/netdev_common.go
collector/systemd_linux.go
collector/systemd_linux_test.go

Update netdev and systemd collectors to deprecate poorly chosen flag names.
Old flag names to be removed in 2.0.0.
https://github.com/prometheus/node_exporter/issues/1742
Add log messages for parsed flag values to help discover quoting isuses in
supervisors.
https://github.com/prometheus/node_exporter/issues/1737

Improve filter flag names.

---

CHANGELOG.md
collector/powersupplyclass.go

Handle the case when /sys/class/power_supply doesn't exist. Fixes
logging error spam.
Requires https://github.com/prometheus/procfs/pull/308

Handle no data from powersupplyclass

---

collector/powersupplyclass.go

* Remove internal wrapping of PowerSupplyClass error.
* Switch to errors.Is().

Fix up powersupplyclass error

---

CHANGELOG.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/netstat_linux.go

TCP "OutRsts" is the number of TCP Resets sent by the node. This can be
useful for monitoring connection failures and flooding.

Include TCP OutRsts in netstat metrics

---

README.md

The original link is broken (404).

Update the link to prometheus-dcgm

---

docs/node-mixin/alerts/alerts.libsonnet

With node_exporter 1.0+ it is possible to include alerting on RAID array degradation.
Adding one critical alert when an array is degraded but cannot fix itself due to lacking spare drives. Plus one warning alert for any failed drive.
I was testing those since node_exporter 1.0-rc.1.

docs/node-mixin: add alerts about failing RAID array

---

collector/bcache_linux.go
collector/fixtures/e2e-output.txt

This PR adds support for bcache writeback_rate_debug statistics.
This depends on https://github.com/prometheus/procfs/pull/277

bcache: add writeback_rate_debug stats

---

docs/node-mixin/dashboards/node.libsonnet

Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>
When there is multiple pods over the selected time range grafana display the following errors "Only queries that return single series/table is supported".
This PR add a simple avg() to fix this issue.

Fix memory gauge in mixin with multiple pods

---

collector/cpu_linux.go

We've gathered enough evidence that the CPU counter bug workaround is
working as intended. Downgrade the message from Warning to Debug.

Downgrade CPU counter warnings

---

docs/node-mixin/alerts/alerts.libsonnet

Different approach to the same problem as in https://github.com/prometheus/node_exporter/pull/1850
/cc @SuperQ

docs/node-mixin: add max error condition to alert about desynchronized clock

---

docs/node-mixin/dashboards/node.libsonnet
docs/node-mixin/dashboards/use.libsonnet
docs/node-mixin/jsonnetfile.json

This should be the way forward when importing libraries in jsonnet. It's closer to how Go imports look and makes it more obvious where packages live.
This is not breaking anything, as the old imports were already symlinks to the now directly used directories.

Use absolute jsonnet import paths

---

docs/node-mixin/README.md

Mixin: Bump jsonnet requirement to 0.16 to use go-jsonnetcmd

---

README.md

The txt was changed to rst:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/accounting/psi.rst
But it's probably better to link to the rendered docs, since the link
should be more stable.
Signed-off-by: Louis Taylor <louis@kragniz.eu>

readme: fix link to PSI documentation

---

README.md
docs/TIME.md

Get my feet wet by tweaking some wording and adding some guidance wrt collectors that are disabled by default.
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

Modest doc improvements

---

README.md

Signed-off-by: Paul Manley <paul.manley@wholefoods.com>

add btrfs and powersupplyclass to list of exporters enabled by default

---

.promu.yml
CHANGELOG.md
Makefile
README.md
collector/boot_time_openbsd_amd64.go
collector/cpu_openbsd_amd64.go
collector/diskstats_openbsd_amd64.go
collector/filesystem_openbsd_amd64.go
collector/interrupts_openbsd.go
collector/interrupts_openbsd_amd64.go
collector/meminfo_openbsd.go
collector/meminfo_openbsd_amd64.go
collector/netdev_openbsd.go
collector/netdev_openbsd_amd64.go
collector/sysctl_openbsd_amd64.go

I have rewritten all CGO dependencies for OpenBSD amd64
using pure go, be able to crosscompile node_exporter.
Signed-off-by: ston1th <ston1th@giftfish.de>

remove openbsd amd64 cgo dependecies

---

collector/infiniband_linux.go

This will not work until https://github.com/prometheus/procfs/pull/284 is merged and this module uses procfs that has the additional counters.

Add more IB counters

---

go.mod
go.sum
node_exporter.go

I cannot install this exporter. Because module name changed in exporter-toolkit. So I changed module name that.

Change exporter-toolkit module name(https -> web)

---

CHANGELOG.md
collector/timex.go

Handle case where Adjtimex syscall gets a permission denined error.
Fixes: https://github.com/prometheus/node_exporter/issues/1934

Handle EPERM for syscall in timex collector

---

collector/filesystem_common.go

this change fixes the logging message for the filesystem ignored-fs-types flag to output the flag instead of the mountpoints flag.

collector/filesystem: fixing logging message

---

docs/node-mixin/alerts/alerts.libsonnet

Within `node_exporter` the metric `node_md_disks` exports the following states:
- Active
- Failed
- Spare
In the meantime, on the jsonnet alerts it was using the label `state="fail"` instead of `state="failed"`. 
This pull request fixes that issue.
---
This information can be also confirmed on:
- [Node Exporter collector source code](https://github.com/prometheus/node_exporter/blob/master/collector/mdadm_linux.go#L146)
```go
ch <- prometheus.MustNewConstMetric(
disksDesc,
prometheus.GaugeValue,
float64(mdStat.DisksFailed),
mdStat.Name,
"failed",
)
```
- [Node Exporter fixture for node_md_disks](https://github.com/prometheus/node_exporter/blob/master/collector/fixtures/e2e-output.txt#L1243)
```go
node_md_disks{device="md0",state="active"} 2
node_md_disks{device="md0",state="failed"} 0 …
```

fix: node_md_disks state label from fail to failed

---

docs/node-mixin/alerts/alerts.libsonnet

These fields should be identical to prevent issues with Alertmanager templates.

Use description instead of message as field for annotations

---

collector/conntrack_linux.go
collector/pressure_linux.go
collector/rapl_linux.go
collector/zfs.go

Fixes #1723 
Related to #1323 
- Make empty collection of ZFS return success=0
- Modify behaviour of other collectors that return nil as error when experiencing error in the Update method

Fix node_scrape_collector_success behaviour

---

collector/processes_linux.go
collector/processes_linux_test.go

As @acastong writes in #1901, 
> This is very closely related to #1043 : that change fixed processes disappearing between list the /proc directory and reading the actual process stats. But another race condition is possible: between opening the `/proc/<process id>/stat` file and actually reading it, another race condition can occur and the error code returned is different. Bellow is a small code snippet to reproduce that race condition.
>
> The recommended fix is to modify `getAllocatedThreads()` in `collector/processes_linux.go` to continue after `stat, err := pid.Stat()` if the error meets this condition: `strings.Contains(err.Error(),syscall.ESRCH.Error())`.
This PR just does what @acastong suggests.
Closes #1901

ProcessStatCollector: continue if PID disappears between opening and reading file

---

CHANGELOG.md
collector/supervisord.go

Supervisord supports auth via adding `username` and `password` in the[ configuration file.](http://supervisord.org/configuration.html)
Passing that info via CLI args is insecure. 
Passing them via Env vars is a bit more secure without any downsides to the default configuration.

Added an ability to pass collector.supervisord.url via ENV vars

---

collector/bcache_linux.go
collector/fixtures/e2e-output.txt

Fix typos in collector/bcache_linux.go and collector/fixtures/e2e-output.txt
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

bcache: fix typo

---

README.md
collector/fibrechannel_linux.go
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
end-to-end-test.sh

This adds support for collecting linux Fibre Channel stats. Resolves issue #570

Add fibre channel collector

---

collector/fixtures/e2e-output.txt
collector/fixtures/proc/zoneinfo
collector/zoneinfo_linux.go
end-to-end-test.sh

Signed-off-by: Wisniewski, Krzysztof2 <Krzysztof2.Wisniewski@intel.com>

Add zoneinfo collector

---

collector/rapl_linux.go

Catch permission denined errors in the rapl collector.

Fix rapl collector log noise

---

collector/zfs_linux.go
go.mod
go.sum

* Bump procfs to include some fixes to error messages.
* Lower zpoolStatePaths log from Warn to Debug.
* Add workaround for missing `%w` in procfs errors[0].
Fixes: https://github.com/prometheus/node_exporter/issues/1961
Fixes: https://github.com/prometheus/node_exporter/issues/1960
[0]: https://github.com/prometheus/procfs/pull/357

Fix some noisy log lines

---

CHANGELOG.md
collector/pressure_linux.go

When CONFIG_PSI_DEFAULT_DISABLED=y, the pressure system returns
"operation not supported", rather than permission denied or not
exposing the /proc/pressure files.
Fixes: https://github.com/prometheus/node_exporter/issues/1961

Handle errors from disabled PSI subsystem

---

CHANGELOG.md
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
collector/powersupplyclass.go

Avoid panic on invalid UTF-8 from /sys/class/power_supply by
sanitizing strings parsed from the kernel.
Fixes: https://github.com/prometheus/node_exporter/issues/1979

Sanitize strings from /sys/class/power_supply

---

CHANGELOG.md
collector/netclass_linux.go

* Handle no such file and permission denied errors.
* Reduce excessive error wrapping.
Fixes: https://github.com/prometheus/node_exporter/issues/1840

Silence missing netclass errors

---

CHANGELOG.md
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
collector/netclass_linux.go
end-to-end-test.sh

Some devices (ex virtual) don't have a speed and report `-1` as the
speed value. Add a flag to allow ignoring speed on these devices.
Fixes: https://github.com/prometheus/node_exporter/issues/1967

Add flag to ignore network speed if it is unknown

---

CHANGELOG.md
collector/filesystem_bsd.go
collector/filesystem_common.go
collector/filesystem_freebsd.go
collector/filesystem_linux.go
collector/filesystem_openbsd_amd64.go

PR #1743 changed filter flag names to `collector.netdev.device-exclude` and `collector.systemd.unit-exclude`. To follow this naming scheme, `collector.filesystem.ignored-mount-points` and `collector.filesystem.ignored-fs-types`should be renamed as well and the old flags deprecated for 2.0.
Fixes: #1994
FYI: I couldn't run `make` and `make test` because of some linting issues in other modules I didn't want to touch:
```
GO111MODULE=on /Users/frederic/go/bin/golangci-lint run  ./...
collector/diskstats_common.go:54:2: `ioTimeSecondsDesc` is unused (deadcode)
ioTimeSecondsDesc = prometheus.NewDesc(
^
collector/helper.go:23:6: `readUintFromFile` is unused (deadcode)
func readUintFromFile(path string) (uint64, error) {
^
collector/paths.go:39:6: `rootfsFilePath` is unused (deadcode)
func …
```

Rename filesystem collector flags to match netdev and systemd collectors

---

docs/node-mixin/config.libsonnet
docs/node-mixin/dashboards/node.libsonnet
docs/node-mixin/dashboards/use.libsonnet
docs/node-mixin/rules/rules.libsonnet

The default scrape interval of Prometheus is 60s, so we can't use a 1m
rate.
Signed-off-by: Johannes 'fish' Ziemke <github@freigeist.org>

Use 5m rate in mixins

---

.promu-cgo.yml
Makefile.common
collector/filesystem_bsd.go
collector/filesystem_common.go
collector/filesystem_openbsd_amd64.go
collector/zfs_linux.go

Add darwin/arm64 to the CGO crossbuilder list.
* Update Makefile.common to pick up new promu.
* Fix possible nil pointer caught by staticcheck.
* Update collector build tags.
Fixes: https://github.com/prometheus/node_exporter/issues/1997

Add Darwin arm64 build

---

node_exporter.go

Matches updated behaviour in Prometheus and other tools.
Signed-off-by: David Leadbeater <dgl@dgl.cx>

Make node_exporter print usage to STDOUT

---

Makefile

rm interactively asks for confirmation while removing read-only
files and fixtures sys has dozens of them.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

Use rm -rf to remove fixtures

---

collector/cpu_linux.go
collector/cpu_linux_test.go

The Linux CPU idle stat can also jump backwards slightly in some cases.
Fixes: https://github.com/prometheus/node_exporter/issues/1903

Handle small backwards jumps in CPU idle

---

CHANGELOG.md
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
collector/tapestats_linux.go

It is heavily based on diskstats to allow metrics reuse by simply
s/disk/tape/ the query.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

Add tapestats to collect tape devices statistics

---

collector/conntrack_linux.go

Fix un-handled file not found for conntrack stats.

Fix conntrack collector log noise

---

docs/node-mixin/README.md

`go get` is deprecated for installation of commands as of go v1.17
Ref: https://go.googlesource.com/go/+/ced0fdbad0655d63d535390b1a7126fd1fef8348
Signed-off-by: Frederic Hemberger <mail@frederic-hemberger.de>

docs: Replace `go get` with `go install` for command installation

---

collector/processes_linux.go
go.mod
go.sum

Update procfs library to include ignored fields ParseInt handling.
Wrap error returns so that the user can know more about what failed.
Returns from getAllocatedThreads() are errors anyway.
Fixes: https://github.com/prometheus/node_exporter/issues/2110

Fix processes collector long int parsing

---

collector/ethtool_linux.go

This adds a new flag --collector.ethtool.metrics-include to the ethtool
collector. Only metrics matching this regexp will be collected.
This closes #2096

Add collector.ethtool.metrics-include

---

collector/ethtool_linux.go
collector/ethtool_linux_test.go

OpenMetrics and the Prometheus exposition format require the metric name to consist only of alphanumericals and "_", ":" and they must not start with digits. The metric names from the ethtool stats might contain spaces, brackets, and dots. Converting them directly to metric names will produce invalid metric names.
Therefore sanitize the metric names and convert them to lower case.
The function `SanitizeMetricName` will be useful for other exporters. Please let me know where the best place is for it. Maybe https://github.com/prometheus/common or https://github.com/prometheus/client_golang?
Fixes: https://github.com/prometheus/node_exporter/issues/2083

ethtool: Sanitize metric names

---

docs/node-mixin/alerts/alerts.libsonnet

In our tests in OpenShift it looks like 1h is too long to prevent catastrophic failures.

docs/node-mixin/alerts: make NodeFilesystemAlmostOutOfSpace fire earlier

---

CHANGELOG.md
collector/cpu_linux.go

In high scale virtualized / cloud environments there are typically
no guest VMs. Add a boolean flag to allow disabling the Linux guest
CPU metrics.

Add flag to disable guest CPU metrics

---

README.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/usr/lib/os-release
collector/os_release.go
collector/os_release_test.go
end-to-end-test.sh
go.mod
go.sum

Currently Node Exporter has a metric called `node_uname_info` which of course exposes uname info. While this is nice, it does not help if you are running different OSes which could have similar uname info.
Therefore parse `/etc/os-release` or `/usr/lib/os-release` and expose a `node_os_info` metric which provide information regarding the OS release/version of the node. Also expose the major.minor part of the OS release version as `node_os_version`.
Since the os-release files will not change often, cache the parsed content and only refresh the cache if the modification time changes.
This `os` collector will read files outside of `/proc` and `/sys`, but the os-release file is widely used and the format is standardized: https://www.freedesktop.org/software/systemd/man/os-release.html
Fixes …

Add os release collector

---

CHANGELOG.md
go.mod
go.sum

New version contains fix for `panic`, see lufia/iostat#2

Update github.com/lufia/iostat to v1.1.1

---

docs/node-mixin/rules/rules.libsonnet

Looks like it's about 10x faster on large setups

mixin: Cheaper calculation for instance:node_num_cpu:sum

---

.golangci.yml

These lead to false positives when build tags disable certain files as
reported in https://github.com/prometheus/node_exporter/issues/1545
They'll get deprecated and removed eventually anyway:
https://github.com/golangci/golangci-lint/issues/1841

Disable soon to deprecated linters

---

Makefile

Fixes: https://github.com/prometheus/node_exporter/issues/2148

Bump promtool version in Makefile

---

collector/cpu_linux.go
collector/fixtures/e2e-output.txt

Signed-off-by: binjip978 <binjip978@gmail.com>

collect flag_info and bug_info only for one core

---

collector/diskstats_linux.go
collector/diskstats_linux_test.go
collector/fixtures/e2e-output.txt

This refactors diskstats to use procfs. It is laying the groundwork for adding device-mapper metadata from #885 using prometheus/procfs/pull/412.
There is no user-visible change except for the addition of a new node_disk_info metric. I'm undecided if this should even be here at this point. Major/minor numbers aren't very useful. And maybe it should be `{dev="252:2"}` instead? Opinions?
Also of note, the tests have been rewritten in a way I'm finally happy with. What do you think of the approach to fully render all the metrics to text and assert that the strings match?
Signed-off-by: W. Andrew Denton git@flying-snail.net

Refactor diskstats

---

docs/node-mixin/rules/rules.libsonnet

Add a fallback to Buffers+Cached+MemFree+Slab for older Linux kernels
where the MemAvailable metric is not available for memory utilization.

mixin: Add fallback for MemAvailable

---

.circleci/config.yml
.golangci.yml
.yamllint
docs/example-16-compatibility-rules-new-to-old.yml
docs/example-16-compatibility-rules.yml
docs/example-17-compatibility-rules-new-to-old.yml
docs/example-17-compatibility-rules.yml
example-rules.yml

After a recent change in prometheus/prometheus, Makefile.common includes
now a yamllint target which currently fails. This PR adds the missing
yamllint config and fixes the yamllint errors.
Fixes: https://github.com/prometheus/node_exporter/issues/2087
Signed-off-by: Michal Wasilewski <mwasilewski@gmx.com>

add yamllint config, fix yamllint errors

---

docs/node-mixin/dashboards/node.libsonnet
docs/node-mixin/rules/rules.libsonnet

'iowait' and 'steal' indicate specific idle/wait states, which shouldn't
be counted into CPU Utilisation. Also see
https://github.com/prometheus-operator/kube-prometheus/pull/796 and
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/667.
Per the iostat man page:
%idle
Show the percentage of time that the CPU or CPUs were idle and the
system did not have an outstanding disk I/O request.
%iowait
Show the percentage of time that the CPU or CPUs were idle during
which the system had an outstanding disk I/O request.
%steal
Show the percentage of time spent in involuntary wait by the
virtual CPU or CPUs while the hypervisor was servicing another
virtual processor.
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>

mixin: exclude iowait and steal from CPU Utilisation

---

collector/cpu_darwin.go

LLVM/Clang 11.0 adds a `-Wundef-prefix=TARGET_OS_` build flag which
breaks this build flag.

Workaround LLVM/Clang 11.0 for Darwin builds

---

collector/ethtool_linux.go
collector/fixtures/ethtool/eth0/statistics

Sanitizing the metric names can lead to duplicate metric names:
```
caller=level.go:63 level=error caller="error gathering metrics: [from Gatherer #2] collected metric \"node_ethtool_giant_hdr\" { label:<name:\"device\" value:\"ens192\" > untyped:<value:0" msg=" > } was collected before with the same name and label values"
```
Generate a map from the sanitized metric names to the metric names from ethtool. In case of duplicate sanitized metric names drop both metrics, because it is unknown which one to take.
Fixes: https://github.com/prometheus/node_exporter/issues/2185

ethtool: Prevent duplicate metric names

---

collector/cpu_linux.go
collector/drm_linux.go

'make' command fails because of 'golangci-lint'
```
collector/cpu_linux.go:145:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
if err := c.updateThermalThrottle(ch); err != nil {
return err
}
collector/drm_linux.go:102:2: if-return: redundant if ...; err != nil check, just return error instead. (revive)
if err := c.updateAMDCards(ch); err != nil {
return err
}
```

Remove redundant nil check

---

README.md

Nvidia archived gpu-monitoring-tools and created new repos for each of it's 3 projects. This is the new repo for the dcgm-exporter project.

Update README dcgm-exporter repository

---

README.md
collector/lnstat_linux.go

The new `lnstat` collector produces a high number of metrics, per-cpu, and results in approximately double the number of metrics previously scraped. For example, a typical server with 64 cores produces 3832 lnstat metrics compared to 4147 metrics for the remaining collectors.
Therefore disable the `lnstat` collector by default.

Disable lnstat collector by default

---

CHANGELOG.md
collector/fixtures/e2e-output.txt
collector/netstat_linux.go

TCP timeouts count is a useful signal to show
abnormal network performance and is another
signal to aid debugging. This metric can be
used to generate proactive alerts for host
network namespace workloads.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

Add TCPTimeouts to netstat default filter

---

collector/fixtures/e2e-output.txt
collector/stat_linux.go
end-to-end-test.sh

This adds a new Linux metric, node_softirqs_total, which corresponds
to the 'softirq' line in /proc/stat. This metric is disabled by
default and it can be enabled with '--stat.softirq'.
Closes #2220.

Add node_softirqs_total metric

---

collector/filesystem_freebsd.go

Closes #2152.
I noticed that `MNT_READONLY` and `MNT_NOWAIT` are available under `unix` dependency as well, is there a reason they were defined as local constants instead of relying on the external library?
In this PR I made the shortest change possible and used the library for the new flag, but if you'd like me to use this PR to change those two as well (or, on the opposite, define also this third one as local constant), tell me.

Ignore filesystems flagged as MNT_IGNORE.

---

CHANGELOG.md
collector/arp_linux.go
collector/fixtures/proc/net/arp
end-to-end-test.sh

Allow filtering APR entries based on device. Useful for ignoring
entries for network namespaces (containers).

Add device filter flags to arp collector

---

collector/filesystem_linux.go

analogous to the /var/lib/docker exclude added in
https://github.com/prometheus/node_exporter/pull/814
podman rootful containers mount eg. shm filesystems at
/var/lib/containers/storage/*-containers/*/userdata/shm. these should be
treated like things under /var/lib/docker by default.
Signed-off-by: Lauri Tirkkonen <lauri@hacktheplanet.fi>
@SuperQ

filesystem_linux: exclude mounts under /var/lib/containers/storage

---

collector/meminfo_darwin.go

I was recently working on some changes to the mixin for Darwin dashboards (see https://github.com/prometheus/node_exporter/pull/2236), specfically around memory usage, and noticed that the way I was calculating the memory is likely incorrect. I'm attempting to calculate the memory usage statistics as close to what Apple's Activity Monitor does (e.g. App Memory in this case).  From what I can tell App Memory is calculated from `(vmstat.internal_page_count - vmstat.purgeable_count) * pageSize` 
Please let me know if there's any issues with exposing these additional values from vmstat in the Darwin meminfoCollector.

add additional vm_stat memory metrics for darwin

---

collector/systemd_linux.go

systemd patch versions are as important as the major version number;
they indicate security or bug fixes or other behavioural changes between
versions.
Use float64 over float32 as the rounding error with float32 rendered
250.3 as 250.3000030517578 in my testing.
Signed-off-by: Joe Groocock <jgroocock@cloudflare.com>

systemd: Expose systemd minor version

---

go.mod
go.sum

https://github.com/lufia/iostat/pull/5
Signed-off-by: Public <latchkey@gmail.com>

iostat: update due to visible deprecated warning on osx

---

docs/node-mixin/dashboards/node.libsonnet
docs/node-mixin/dashboards/use.libsonnet

Currently when dashboard code is generated - datasource with name "Prometheus" is picked up as default one. This change is about using Grafana's default datasource instead of hardcoded "Prometheus" (which not everyone has set)
Done the same way as it is in kubernetes-mixin, thanos-mixin, etc

[node-mixin] change current datasource to grafana's default

---

collector/diskstats_linux.go

Fixes #2310
Signed-off-by: W. Andrew Denton <git@flying-snail.net>

diskstats_linux: always scale reads and writes by 512 bytes, not by device units

---

collector/powersupplyclass_darwin.go

this is necessary to build on darwin using nix, as nix-darwin uses an older macOS SDK, built from apple's open source releases.

powersupplyclass_darwin: extra includes to build against older macOS SDK

---

collector/fixtures/proc/net/tcpstat
collector/tcpstat_linux.go
collector/tcpstat_linux_test.go
go.mod

This changes the implementation of the tcpstat Collector to use netlink instead of reading the /proc/net/tcp(6) file. I tested it against a Host with 1 Million Connections and while the file-based implementation never finished and used all available cpu time, this only takes 1-2 seconds.
Closes #1061

refactor: Use netlink for tcpstat collector

---

collector/filesystem_freebsd.go
collector/helper.go
collector/helper_test.go
collector/uname_bsd.go
collector/uname_linux.go

Use `unix.ByteSliceToString` to convert `Utsname` `[]byte` fields to strings.
This also allows to drop the `bytesToString` helper which serves the same
purpose and matches `ByteSliceToString`'s implementation.

collector: use ByteSliceToString from golang.org/x/sys/unix

---

collector/rapl_linux.go

Fixes https://github.com/prometheus/node_exporter/issues/2299 by wrapping metric name in `SanitizeMetricName()` as suggested by @discordianfish

rapl_collector: fix issue with invalid metric name (#2299)

---

collector/arp_linux.go
collector/device_filter.go
collector/device_filter_test.go
collector/ethtool_linux.go
collector/netdev_bsd.go
collector/netdev_common.go
collector/netdev_darwin.go
collector/netdev_linux.go
collector/netdev_linux_test.go
collector/netdev_openbsd.go
collector/netdev_openbsd_amd64.go

Rename the network device filter to a more generic device filter.

Rename netDevFilter helper

---

CHANGELOG.md
collector/rapl_linux.go

Add an optional flag to set the RAPL zone as a label, instead of as part
of the metric name.
Fixes: https://github.com/prometheus/node_exporter/issues/2299

Add rapl zone label option

---

docs/node-mixin/README.md

fix the following markdownlint errors (and some more):
[..]mixins/node-exporter/README.md:13: MD031 Fenced code blocks should be surrounded by blank lines
[..]mixins/node-exporter/README.md:21: MD031 Fenced code blocks should be surrounded by blank lines
[..]mixins/node-exporter/README.md:27: MD031 Fenced code blocks should be surrounded by blank lines
[..]mixins/node-exporter/README.md:33: MD031 Fenced code blocks should be surrounded by blank lines
[..]mixins/node-exporter/README.md:41: MD034 Bare URL used
A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

fix the following markdownlint issues

---

README.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/selinux_linux.go
end-to-end-test.sh
go.mod
go.sum

Adds a collector for gathering basic SELinux metrics.

Add selinux collector 

---

collector/diskstats_common.go
collector/diskstats_darwin.go
collector/diskstats_linux.go
collector/diskstats_linux_test.go
collector/diskstats_openbsd.go
collector/diskstats_openbsd_amd64.go

Use standard include/exclude pattern for device include/exclude in the diskstats collector.
Refactor diskstats collector include/exclude to work on all platforms.

Add diskstats include and exclude device flags

---

CHANGELOG.md
README.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/slabinfo
collector/slabinfo_linux.go
end-to-end-test.sh

Close https://github.com/prometheus/node_exporter/issues/1799
This patch adds a collector to collect metrics from /proc/slabinfo.

collector: add slab info

---

docs/node-mixin/alerts/alerts.libsonnet

Few alerts in mixin were missing metric selectors. This PR allows to select just particular nodes to be covered by those alerts. Additionally it also allows to exclude devices for NodeRAIDDegraded alert.

docs/node-mixin: add missing selectors

---

CHANGELOG.md
README.md
collector/filesystem_openbsd_amd64.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/sys/kernel/seccomp/actions_avail
collector/sysctl_linux.go
end-to-end-test.sh
go.mod
go.sum

Depends on https://github.com/prometheus/procfs/pull/460

Add sysctl collector

---

README.md

The zfs collector for FreeBSD was committed in
3d504bc5cb41b4f2b7fda614fbba3c3f43402124.
Signed-off-by: Mateusz Piotrowski <0mp@FreeBSD.org>

Document availability of zfs collector on FreeBSD

---

collector/memory_bsd.go

These two memory classes have been here for a while now in FreeBSD,
adding them allows having information for all memory classes.

memory_bsd: add user_wired_bytes & laundry_bytes

---

docs/example-16-compatibility-rules-new-to-old.yml

label_replace for new to old rules are wrong for the node_cpu metrics.
I've verified the fix, and it works.
The old node_cpu had labels such as `cpu=cpu0` the new one has `cpu=0` so this converts it correctly.

fix compatibility rule to convert to old node_cpu metric

---

docs/node-mixin/lib/prom-mixin.libsonnet

1.    Update units of network and disk graphs
https://prometheus.io/docs/prometheus/latest/querying/functions/#rate
rate() calculates per-second average rate, therefore Bps units should be used for disks.
In networking bandwidth throughput is usually measured in bits/s so network graphs' units are changed accordingly.
2.  Change io time units from seconds to %util
When applying rate() to seconds we have 'seconds per second' or fractions of the second, so actually it actually can be from 0 to 1.
3.  Update intervalFactor to 1 for better rates

mixin: update units for disk and networking panels

---

docs/example-16-compatibility-rules.yml

The name is reverse - see also the reversed `example-17-compatibility-rules-new-to-old.yml`.
Signed-off-by: Florian Best <best@univention.de>

Fix CPU renaming rule

---

collector/cpu_linux.go
collector/cpu_linux_test.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar

Hi
This PR adds the "isolated" label on `cpu` collector for linux. 
I'm not sure if it should be added as a label on this collector or as a new metric, please let me know.
This is my first time writing go :grimacing:  so please let me know if I should be doing things differently

Implement #2250: Add "isolated" metric on cpu collector on linux

---

collector/qdisc_linux.go
end-to-end-test.sh

Rebased and resubmitted https://github.com/prometheus/node_exporter/pull/2345

qdisk-linux: Add exclude and include flags for interface name

---

collector/cpu_openbsd.go

Return the copyright date in `collector/cpu_openbsd.go` to the original
value.
Minor change revert on https://github.com/prometheus/node_exporter/pull/1971

Fix up copyright date change

---

collector/bonding_linux.go
collector/filefd_linux.go
collector/helper.go
collector/hwmon_linux.go
collector/ipvs_linux_test.go
collector/loadavg_linux.go
collector/perf_linux_test.go
collector/qdisc_linux.go
collector/textfile.go
collector/textfile_test.go
collector/wifi_linux.go
node_exporter_test.go

`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>

Remove ioutil

---

collector/perf_linux.go

This change adds additional perf counter values for stalled frontend/backend cycles. There is a decent [post](https://stackoverflow.com/questions/22165299/what-are-stalled-cycles-frontend-and-stalled-cycles-backend-in-perf-stat-resul) that describes stalled cycles and how they are used in the `perf` subsystem.
Tested locally:
```
curl  localhost:9100/metrics | grep perf | grep 'cpu="0"'
node_perf_branch_instructions_total{cpu="0"} 7.25668184e+08
node_perf_branch_misses_total{cpu="0"} 1.5600914e+07
node_perf_cache_bpu_read_hits_total{cpu="0"} 7.23401709e+08
node_perf_cache_bpu_read_misses_total{cpu="0"} 1.5085842e+07
node_perf_cache_l1_instr_read_misses_total{cpu="0"} 1.3356764e+07
node_perf_cache_l1d_read_hits_total{cpu="0"} 1.379718659e+09
node_perf_cache_l1d_read_misses_total{cpu="0"} …
```

Add additional perf counters for stalled frontend/backend cycles

---

collector/os_release.go

`os_release.Update` may be called concurrently; it in turn calls `UpdateStruct` which:
1. Reads `c.osFilename` and `c.osMtime`, if both values are set and match some condition the function it returns. `Update` assumes that `c.os` is set if this path is executed.
2. Acquires mutex (line 132)
3. Sets `c.osFilename` and `c.osMtime`
4. Sets `c.os` 
5. Releases mutex
There is a race condition here: the reads in 1. are not protected by a mutex, so the following pathological interleaving will occasionally occur:
thread `t1` will execute step 3., followed by 
thread `t2` executing step 1., returns from `UpdateStruct` assuming that `c.os` is set, execution continues in line 159, breaks out of the loop and `c.os` is accessed in line 173, resulting in a segfault as it is `(nil,nil)`.
One option is …

Bug: Fix race condition in os_release.go

---

collector/os_release.go

There was no possibility to get MacOs version in `node_os_info` or `node_os_version` metrics. This PR will fix this. 
Signed-off-by: sfreydin <sfreydin@macpaw.com>

Add support for MacOs version

---

collector/fixtures/textfile/metrics_merge_different_help.out
collector/fixtures/textfile/metrics_merge_different_help/a.prom
collector/fixtures/textfile/metrics_merge_different_help/b.prom
collector/fixtures/textfile/metrics_merge_empty_help.out
collector/fixtures/textfile/metrics_merge_empty_help/a.prom
collector/fixtures/textfile/metrics_merge_empty_help/b.prom
collector/fixtures/textfile/metrics_merge_no_help.out
collector/fixtures/textfile/metrics_merge_no_help/a.prom
collector/fixtures/textfile/metrics_merge_no_help/b.prom
collector/fixtures/textfile/metrics_merge_same_help.out
collector/fixtures/textfile/metrics_merge_same_help/a.prom
collector/fixtures/textfile/metrics_merge_same_help/b.prom
collector/textfile.go
collector/textfile_test.go

The textfile collector will now provide a unified metric description (that will look like "Metric read from file/a.prom, file/b.prom") for metrics collected accross several text-files that don't already have a description.
Signed-off-by: Guillaume Espanel <guillaume.espanel.ext@ovhcloud.com>
Fixes: #1885

Merge metrics descriptions in textfile collector

---

collector/btrfs_linux.go
collector/btrfs_linux_test.go
go.mod
go.sum

Makes ioctl syscalls to load the device error stats you'd normally see using `btrfs device stats /mnt/myFs`.
On the command line, you'd normally see this kind of info via:
```
sudo btrfs device stats /mnt/fakebtrfs2
[/dev/loop1].write_io_errs    0
[/dev/loop1].read_io_errs     0
[/dev/loop1].flush_io_errs    0
[/dev/loop1].corruption_errs  0
[/dev/loop1].generation_errs  0
[/dev/loop2].write_io_errs    0
[/dev/loop2].read_io_errs     0
[/dev/loop2].flush_io_errs    0
[/dev/loop2].corruption_errs  0
[/dev/loop2].generation_errs  0
```
All feedback appreciated!
Requested in #2173 & #1100

Add btrfs device error stats

---

go.mod
go.sum

- Bumping  golang.org/x/crypto from 0.0.0-20220214200702-86341886e292 to 0.0.0-20220314234659-1baeb1ce4c0b to fix CVE-2022-27191 high severity vulnerability.
- Bumping golang.org/x/net from 0.0.0-20220225172249-27dd8689420f to 0.0.0-20220906165146-f3363e06e74c to fix CVE-2022-27664 high severity vulnerability.

Bump crypto and net CVE-2022-27191 CVE-2022-27664

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/hwmon_linux.go

We don't need to fully sanitize the hwmon label values to metric/label name strings.
* Just make sure they're valid UTF-8.
* Always included the label metric to avoid group_left failures.

Fix hwmon label sanitizer

---

docs/node-mixin/alerts/alerts.libsonnet
docs/node-mixin/config.libsonnet
docs/node-mixin/dashboards/use.libsonnet
docs/node-mixin/lib/prom-mixin.libsonnet

This adds the option to filter filesystem related alerts and dashboard using the `mountpoint` label.

docs/node-mixin: add fsMointpointSelector to alerts and dashboards

---

collector/netdev_linux.go
collector/netdev_linux_test.go

Some systems have broken netlink messages due to patched kernels. Since these messages can not be parsed, add a flag to fall back to parsing from `/proc/net/dev`.
Fixes: https://github.com/prometheus/node_exporter/issues/2502

Add procfs fallback to netdev collector

---

README.md

Copr community prometheus-exporters repository is unfortunately obsoleted.

readme: remove RHEL/CentOS/Fedora installation info

---

collector/netclass_linux.go
collector/netclass_rtnl_linux.go
collector/utils.go
go.mod
go.sum

This pull request adds a collector replacing the netclass collector using netlink library.
Sometimes collecting netclass metrics from sysfs `/sys/class/net/<iface>/<metric>` is much slower than using the netlink library . This modification aims to provide a faster way to collect these metrics.
It is also possible to include metrics in netdev collector in this collector, since netlink response message to RTM_GETLINK already contains the metrics.
To activate the collector, we need to disable the netclass collector at the same time. Please refer to the arguments below:
```
./node_exporter --web.listen-address=127.0.0.1:9100 --collector.netclass_rtnl --no-collector.netclass
```
Meanwhile, we can ignore some network devices from the collector by using the argument ` …

add RTNL version of netclass collector

---

CHANGELOG.md
node_exporter.go

Avoid running on all CPUs by limiting the Go runtime to one CPU by default. Avoids having Go routines schedule on every CPU, driving up the visible run queue length on high CPU count systems.
This also helps workaround a kernel deadlock issue with reading from sysfs concurrently.
See:
* https://github.com/prometheus/node_exporter/issues/1880
* https://github.com/prometheus/node_exporter/issues/2500

Default GOMAXPROCS to 1

---

README.md

The `--web.config` flag changed to `--web.config.file` in https://github.com/prometheus/node_exporter/commit/440a132c389dddd405b44d2d5e47157d1159e4d0#diff-7907251477470326df65250bf7fa699e0756ce5d6282e27b34c112132a7ef6b5R162 and was realised in the recent v1.5.0 release.
Signed-off-by: Joe Groocock <me@frebib.net>
---
This didn't appear to be noted as a breaking change. I only noticed when my containers updated and everything stopped working:
```
node_exporter: error: unknown long flag '--web.config', try --help
```
```
/ $ /bin/node_exporter --help | grep web.config
--web.config.file=""       [EXPERIMENTAL] Path to configuration file that
```

Correct documentation for --web.config.file flag

---

node_exporter.go

With `--runtime.gomaxprocs=0`, the GOMAXPROXS value will default to the number of logical CPUs. In this case, it is more useful to log the actual value than the value set by the user via the command-line.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>

Log current value of GOMAXPROCS

---

docs/node-mixin/dashboards/use.libsonnet

The query for the panel was incorrect promql and couldn't be parsed/executed by Grafana/prometheus.

Fix Multi-Cluster USE dashboard Disk Space query

---

CHANGELOG.md

Add note about the change to the experimental web flag.
Fixes: https://github.com/prometheus/node_exporter/issues/2535

Update v1.5.0 release notes

---

collector/arp_linux.go

There was a comment about migrating the ARP collector to ProcFS so additional ARP stats can be added later on. This will enable that work.
It turns out #2547 and #2548 were failing because of an unannounced Github outage rather than any weird code problems.

Migrate arp_linux.go to procfs

---

go.mod
go.sum

This change updates the perf-utils library to 0.6.0 which has some fixes for automatically detecting the correct tracefs mountpoint if available.
Tested locally with:
```
curl localhost:9100/metrics | grep perf | head
node_perf_branch_instructions_total{cpu=0} 5.9196044e+07
node_perf_branch_instructions_total{cpu=1} 4.7814633e+07
node_perf_branch_instructions_total{cpu=10} 7.1260328e+07
node_perf_branch_instructions_total{cpu=11} 5.1564527e+07
node_perf_branch_instructions_total{cpu=12} 6.071945e+07
```
Signed-off-by: Daniel Hodges <hodges.daniel.scott@gmail.com>

Bump perf-utils version to 0.6.0

---

collector/perf_linux.go

The patch add profiler options for the perf collector.
1. `--collector.perf.disable-hardware-profilers` `--collector.perf.disable-software-profilers` `--collector.perf.disable-cache-profilers` will allow users to disable hardware/software/cache profilers.
2. Users can customize the perf profilers via setting `--collector.perf.hardware-profilers=` `--collector.perf.software-profilers=` `--collector.perf.cache-profilers=`.
3. Fix a bug that introduced in v1.4.0 (https://github.com/prometheus/node_exporter/blob/v1.4.0/collector/perf_linux.go#L313):
`cacheProfilers` is always zero (`perf.AllCacheProfilers`) when using `&` bitwise operator. It actually enables all cache perf profilers.
example:
```bash
./node_exporter \
--collector.perf \
--collector.perf.hardware-profilers=CpuCycles \ …
```

Add profiler options for perf collector

---

collector/cpu_linux.go
collector/cpu_linux_test.go
go.mod
go.sum

This is related to https://github.com/prometheus/procfs/pull/438.
We have a case that some of the CPU (threads) are offline intentionally. But due to procfs is returning interpolated values, which makes our cpu caculation return invalid values.
This patch pickup the new procfs change.

fix cpustat when some cpus are offline

---

collector/meminfo.go
collector/meminfo_netbsd.go

This is fairly simple as all the logic to call `sysctl` is in the golang.org/x/sys package.

NetBSD support for the meminfo collector

---

collector/memory_bsd.go

This PR fixes a problem with fetching the `vm.stats.vm.v_user_wire_count` sysctl value on FreeBSD.
Without this fix, the following error is encountered:
```
caller=collector.go:169 level=error msg="collector failed" name=meminfo duration_seconds=1.9608e-05 err="couldn't get memory: cannot allocate memory"
```
The issue is resolved by setting the correct `dataType` on the metric.

memory_bsd: Fix a problem fetching the user wire count on FreeBSD

---

collector/cpufreq_common.go
collector/cpufreq_linux.go
collector/cpufreq_solaris.go

Move metric descriptiions to package vars to avoid allocating them every time `NewCPUFreqCollector()` is called.

Optimize cpufreq collector

---

README.md
collector/ntp.go
docs/TIME.md

The ntp collector has always been a source of confusion and problems. The data it produces is more of a blackbox probe against an NTP server. The time sync / offset data produced is not what users expect.
Mark this collector as deprecated to be removed in v2.0.0

Deprecate ntp collector

---

CHANGELOG.md
README.md
collector/fixtures/proc/interrupts_aarch64
collector/interrupts_linux.go
collector/interrupts_linux_test.go

interrupts_linux: Fix fields on aarch64

---

collector/cpufreq_common.go
collector/cpufreq_linux.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt

Currently there are no metrics exposed about the CPU frequency governor(s). This PR exposes metrics with info about the available governors and indicate which one is in use. It also fixes inconsistencies in the description of some of the metrics exposed by the changed collector.
Adding a mention per the guidelines: @SuperQ, @discordianfish
Signed-off-by: Lukas Coppens <lukas.coppens@be-mobile.com>

feat: expose cpu frequency governor metrics

---

go.mod
go.sum

Previously node_exporter needed to be running as a highly privileged user in order to get device stats.
The change which fixes this: https://github.com/dennwc/btrfs/pull/5
Improves #2193
Closes #2632

Reduce privileges needed for btrfs device stats

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/spl/kstat/zfs/pool2/state
collector/zfs_linux.go
collector/zfs_linux_test.go

feat: added suspended as a node_zfs_zpool_state

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/netclass_linux.go

Currently only the `operstate` is of Linux network interfaces is exposed, but besides grabbing the info from the `flags` value manually the administrative state is not shown.
This commit adds an `adminstate` label to metrics for network interfaces on Linux.
```
curl -s http://localhost:9100/metrics | grep admin                                                                                                                                                                                               
node_network_info{address="",adminstate="up",broadcast="",device="ffho-ops",duplex="full",ifalias="",operstate="unknown"} 1
node_network_info{address="00:00:00:00:00:00",adminstate="up",broadcast="00:00:00:00:00:00",device="lo",duplex="",ifalias="",operstate="unknown"} 1 …
```

Expose administrative state of Linux network interfaces

---

docs/node-mixin/alerts/alerts.libsonnet

This updates the annotation for the NodeClockSkewDetected mixin alert to match the new threshold set.
Original discussion was in this PR: https://github.com/prometheus/node_exporter/pull/1480
I spent an embarrassingly large amount of time trying to figure out how the heck that alert would mean 300s of clock skew. Turns out the annotation was just left the same after the threshold change.
@SuperQ 
@discordianfish

docs (node/mixin): fix annotation for Skew alert

---

collector/cpu_openbsd.go

Do not hand define `struct clockinfo` here. Instead use the version from `x/sys/unix`.
`struct clockinfo` was altered beginning of 2021 and this code was not adjusted.

Fix bad reporting of node_cpu_seconds_total in OpenBSD

---

collector/filesystem_bsd.go
collector/filesystem_openbsd.go

Fix filesystem collector for OpenBSD to not print loads of zero bytes

---

collector/bcache_linux.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar

@discordianfish can you please have a look when you have the chance? Thank you!

bcache: remove cache_readaheads_totals metrics #2103

---

README.md
collector/supervisord.go

Mark the `supervisord` as deprecated. This process
supevisor, like `runit`, is of scope for the node_exporter.

Deprecate supervisord collector

---

collector/diskstats_linux.go

On most hard drives, `ID_SERIAL_SHORT` and `SCSI_IDENT_SERIAL` are identical, but on some SAS drives they do differ. In that case, `SCSI_IDENT_SERIAL` corresponds to the serial number printed on the drive label, and to the value returned by `smartctl -i`.
So use that value by default for the `serial` label on the `node_disk_info` metric, and fallback to `ID_SERIAL_SHORT` only if it's undefined.

collector/diskstats: Use SCSI_IDENT_SERIAL as serial

---

README.md
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/softirqs
collector/softirq_linux.go
collector/softirqs_common.go
end-to-end-test.sh

Adds node_softirqs_functions_total to expose information from /proc/softirqs. Provides access to the counts per CPU for specific softirqs and is disabled by default.
I'm aware of feature request #2220 that led to the addition of the global counters but I could do with a bit more information. Could you let me know what you think? @SuperQ

Add detailed softirq metric

---

collector/netclass_rtnl_linux.go

Read missing dev_id, name_assign_type, and addr_assign_type from sysfs, since they only take a device-specific lock and not the whole RTNL lock. This means reading them is much less impactful on other system processes than many of the other attributes in sysfs that do take the RTNL lock.
@raptorsun

netlink: read missing attributes from sysfs

---

README.md

@SuperQ, @discordianfish: This is just a small change in the readme, because https://github.com/cloudalchemy/ansible-node-exporter has been deprecated on Mar 2, 2023.

Update ansible role in README.md

---

collector/filesystem_linux.go

Closes issue #1760 .
This change adds the ability to process multiple stat calls in parallel.
Processing is rate-limited based on the new flag
`collector.filesystem.stat-workers` (default 4).
Caveat: filesystem stats information is no longer in the same order as
returned by `/proc/1/mounts`.  This should not be an issue.
Caveat: This change currently uses unbuffered channels to prove
correctness without reliance on buffers.  Buffered channels will yield
superior performance.
Signed off by: Erica Mays <erica@emays.dev>

Parallelize stat calls in Linux filesystem collector.

---

README.md
collector/cpu_vulnerabilities_linux.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
end-to-end-test.sh
go.mod
go.sum

closes https://github.com/prometheus/node_exporter/issues/1046

Add cpu vulnerabilities reporting from sysfs

---

docs/node-mixin/alerts/alerts.libsonnet
docs/node-mixin/config.libsonnet

- e1f3b37 Add %(nodeExporterSelector)s to Network and conntrack alerts
- af23597 Add NodeDiskIOSaturation alert
- e2e7864 Set 'at' everywhere as preposition for instance
- 282c129 Decrease NodeNetwork*Errs pending period
- 94535a9 Add failed systemd service alert
- f685865 Add CPU and memory alerts
- 4d19e84 Decrease NodeFilesystem pending time to 15m
- 0336d13 Add mountpoint to NodeFilesystem alerts

Mixin: Add and update alerts

---

README.md
collector/fixtures/sys.ttar
collector/hwmon_linux.go
end-to-end-test.sh

Use the correct include value to the device filter function.
* Add new bogus hwmon fixture.
* Update end-to-end test to use hwmon chip include flag.

Fixup hwmon chip include

---

README.md

The DRM collector was missing in the README, this change includes it together with a short description. @SuperQ @discordianfish

Include drm collector in README

---

collector/netdev_linux.go

On some platforms, `msg.Attributes.Stats64` is `nil` because the kernel doesn't expose 64-bit stats. In that case, return `msg.Attributes.Stats` instead, which are the 32-bit equivalent.
Note that `RXOtherhostDropped` isn't available in that case, so we hardcode it to zero.
Fixes #2641, fixes #2756.

collector/netdev_linux.go: Fallback to 32-bit stats

---

collector/boot_time_solaris.go
collector/cpu_solaris.go
collector/cpufreq_solaris.go
collector/diskstats_openbsd.go
collector/fibrechannel_linux.go
collector/filesystem_openbsd.go
collector/infiniband_linux.go
collector/interrupts_openbsd.go
collector/meminfo_netbsd.go
collector/meminfo_openbsd.go
collector/netdev_openbsd.go
collector/netisr_freebsd.go
collector/nvme_linux.go
collector/selinux_linux.go
collector/slabinfo_linux.go
collector/time_linux.go
collector/zfs_solaris.go

Drop redundant GOOS build tags at start of file if the constraint is already specified by the filename, e.g. foo_GOOS.go or foo_GOOS_GOARCH.go, avoiding potential confusion in future.
cf. https://pkg.go.dev/cmd/go#hdr-Build_constraints

Drop redundant GOOS build tags if already in filename

---

collector/bonding_linux_test.go
collector/diskstats_linux_test.go
collector/ethtool_linux_test.go
collector/filefd_linux_test.go
collector/filesystem_linux_test.go
collector/interrupts_linux_test.go
collector/ipvs_linux_test.go
collector/loadavg_linux_test.go
collector/logind_linux_test.go
collector/meminfo_linux_test.go
collector/meminfo_numa_linux_test.go
collector/netdev_linux_test.go
collector/netstat_linux_test.go
collector/perf_linux_test.go
collector/systemd_linux_test.go
collector/tcpstat_linux_test.go
collector/textfile_test.go

Ensure that unwanted tests are correctly excluded when various build tags are specified, i.e. when the code that they test would be excluded from compilation.

Sync build tags in *_test.go

---

go.mod
go.sum

We're experiencing very poor performance in node_exporter when enabling the qdisc collector.
Profiling indicated that the call to net.InterfaceByIndex in [qdisc get.go line 260](https://github.com/ema/qdisc/blob/master/get.go#L260) causes the problem. It is a https://github.com/golang/go/issues/53660 that net.InterfaceByIndex is becoming very slow with many interfaces present.
Thus we've changed github.com/ema/qdisc so that it uses `net.Interfaces` to collect all interfaces, stores them in a map and then uses that map to perform lookups.
To take the profit we're upgrading github.com/ema/qdisc to v1.0.0 here.

Upgrade github.com/ema/qdisc to v1.0.0 to improve qdisc collector performance

---

collector/cpu_linux.go
collector/fixtures/e2e-output.txt

For CPUs which don't have an available (or insertable, like in managed kubernetes) cpufreq driver, the /proc/cpuinfo file can often have accurate CPU core frequency measurements. This change replaces the constant value of "1" for the "node_cpu_info" metric with the parsed CPU MHz value from /proc/cpuinfo for each core.
Feel free to reject this if you find that this change is inappropriate, or change it as you see fit. I don't see any other fields in my /proc/cpuinfo that vary (much?) with time, so this might be the only field in /proc/cpuinfo that makes sense as a value for this metric.
This change will probably help with these issues:
https://github.com/prometheus/node_exporter/issues/2198
https://github.com/prometheus/node_exporter/issues/2204 (/proc/cpuinfo is normally readable by all …

Add CPU MHz as the value for "node_cpu_info" metric

---

collector/btrfs_linux.go

Despite being quite hard to provoke (< 10% in my testing), the btrfs collector would occasionally leave stale FDs relating to btrfs mountpoints, making the filesystems unable to be unmounted.
Fixes: #2772.

btrfs: close btrfs.FS handle after use

---

collector/filesystem_common.go
collector/filesystem_linux.go

It should resolve the following situation:
https://discuss.prometheus.io/t/running-node-exporter-on-kubernetes-without-root-privileges/1896/2

Move RO status before error return

---

README.md

The present url https://github.com/prometheus/exporter-toolkit/blob/v0.1.0/https/README.md is out of date(v0.1.0) and gives misleading information like `To run a server with TLS, use the flag --web.config`.

Update README.md: update the 'more details' url in the section 'TLS endpoint'

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/nfsd_linux.go

fix: https://github.com/prometheus/procfs/pull/543 
It’s just that the lack of `OP_SETCLIENTID` and `OP_SETCLIENTID_CONFIRM` caused the index miss match.
ref: https://www.rfc-editor.org/rfc/rfc7530.html#page-299

NFSd: fix nfsd v4 index miss

---

README.md

fix #2821 
meminfo_numa collector use `/sys/devices/system/node/node[0-9]*` to expose memory statistics

fix: readme about expose memory statistics

---

docs/node-mixin/alerts/alerts.libsonnet

The node_bonding_xxx metrics are activated by default and can be used to define this alert
the commit is DCO signed off.

Add NodeBondingDegraded alert

---

docs/node-mixin/alerts/alerts.libsonnet
docs/node-mixin/config.libsonnet

This commit introduces a new configuration variable `fsSpaceFillingUpPredictionWindow` to the Node Exporter Mixin, allowing users to set a custom prediction window for the `NodeFilesystemSpaceFillingUp` alert. Previously, this was hardcoded to a 6-hour window, which could lead to false positives in environments with fluctuating disk usage patterns.
With this change, operators can now fine-tune the alert to better fit their specific use cases. The default value has been kept at 6 hours to maintain backward compatibility and to reflect the current behavior.
This update is especially useful for systems that experience short-term spikes in disk usage, which do not necessarily lead to a full filesystem but can trigger alerts unnecessarily. By adjusting the prediction window, users can avoid …

Make filesystem space prediction window configurable

---

collector/cpu_vulnerabilities_linux.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt

While the CPU vulnerabilities metric has been added in #2721, it's currently not including information regarding the mitigation strategy used for a given vulnerability.
This information can be quite valuable, as oftentimes different mitigation strategies come with a different performance impact.
This commit adds a third label to the cpu_vulnerabilities_info metric, to include the "mitigation" used for a given vulnerability - if a given vulnerability is not affecting a node or the node is still vulnerable, the mitigation is expected to be empty.

Add mitigation information label to the linux CPU vulnerabilities metric

---

collector/diskstats_linux.go
collector/diskstats_linux_test.go

As `ram` devices are already ignored by default by the diskstats collector, i want to suggest, that [zram](https://en.wikipedia.org/wiki/Zram) devices are also ignored by default.

diskstats: ignore zram devices on linux systems by default

---

.circleci/config.yml

We had recently pushed a new golang-builder version with this MR: https://github.com/prometheus/golang-builder/pull/239
Bumping this version to that latest one.

Bump golang-builder version

---

collector/exec_bsd.go

This PR fixes an incorrectly placed `labels` in `exec_bsd.go`.
This issue currently means that the BSDs (or, at least FreeBSD) cannot compile 1.7.0.

exec_bsd: Fix labels for vm.stats.sys.v_syscall sysctl

---

collector/hwmon_linux.go

sys class hwmon symbolic link maybe lost in some cases.

fix hwmon nil ptr

---

collector/hwmon_linux.go

Fix golangci-lint "ineffectual assignment" by correctly capturing any errors within the hwmon gathering loop.

Fix hwmon error capture

---

collector/filesystem_linux.go

After the unix.Statfs(rootfsFilePath(labels.mountPoint), buf) function ran, the original code always removed the mountpoint from stuckMounts, assuming it had recovered, regardless of the time taken. This made the mountTimeout parameter not working.
`
go stuckMountWatcher(labels.mountPoint, success, c.logger)
buf := new(unix.Statfs_t)
err := unix.Statfs(rootfsFilePath(labels.mountPoint), buf)
stuckMountsMtx.Lock()
close(success)
// If the mount has been marked as stuck, unmark it and log it's recovery.
if _, ok := stuckMounts[labels.mountPoint]; ok {
level.Debug(c.logger).Log("msg", "Mount point has recovered, monitoring will resume", "mountpoint", labels.mountPoint)
delete(stuckMounts, labels.mountPoint)
}
stuckMountsMtx.Unlock()
`
I moved the "Mount point has recovered" part to the …

Fix filesystem mountTimeout not working issue

---

docs/node-mixin/alerts/alerts.libsonnet

NodeDiskIOSaturation description should say "30 minutes" to match the "for: 30m" clause

Fix description for NodeDiskIOSaturation alert

---

.golangci.yml

Add depguard to golangci-lint to enforce the no-os/exec policy.

Enforce no subprocess policy

---

collector/filesystem_common.go
collector/filesystem_linux.go

Adding new label of "device_error" to surface error in node_filesystem_device_error.
Tests have been done for below scenarios:
**Scenario-1:** No device error
```
$ curl -s http://localhost:9100/metrics | grep node_filesystem_device_error | grep 100.70.222.247
node_filesystem_device_error{device="100.70.222.247:/share_5618cf05_5d99_44b6_a90d_8c2797929dbb",device_error="",fstype="nfs4",mountpoint="/test_nfs"} 0
```
**Scenario-2:** mountpoint timeout
```
$ curl -s http://localhost:9100/metrics | grep node_filesystem_device_error | grep 100.70.222.247
node_filesystem_device_error{device="100.70.222.247:/share_5618cf05_5d99_44b6_a90d_8c2797929dbb",device_error="mountpoint timeout",fstype="nfs4",mountpoint="/test_nfs"} 1
```
**Scenario-3:** error from statfs() e.g. permission denied
```
$ curl …
```

filesystem: surface device errors

---

README.md
collector/watchdog.go

This is to enable the watchdog module by default, as discussed with @SuperQ.
This seems low cardinality enough, and useful enough, we could consider enabling this by default.
_Originally posted by @SuperQ in https://github.com/prometheus/node_exporter/pull/2880#discussion_r1518539121_

Enable watchdog module by default

---

collector/ethtool_linux.go

Apply the same metric name sanitization to the keys as to the metric names. This avoids conflicting help strings in the metric registry.
Fixes: https://github.com/prometheus/node_exporter/issues/2893

Sanitize ethtool metric name keys

---

collector/fixtures/textfile/metrics_merge_different_help.out
collector/textfile.go

Avoid metrics with inconsistent help-texts. The earlier behaviour has been preserved in the sense that the first encountered instance is still used to generate metrics, whereas the subsequent inconsistent ones are ignored along with a few peripheral changes.
```
#TYPE node_scrape_collector_duration_seconds gauge
node_scrape_collector_duration_seconds{collector="textfile"} 0.0004005
node_scrape_collector_success{collector="textfile"} 1
node_textfile_mtime_seconds{file="/Users/rexagod/repositories/misc/node_exporter/ne-bar.prom"} 1.710812009e+09
node_textfile_mtime_seconds{file="/Users/rexagod/repositories/misc/node_exporter/ne-foo.prom"} 1.710811982e+09
node_textfile_scrape_error 1
promhttp_metric_handler_errors_total{cause="encoding"} 0 …
```

collector/textfile: Avoid inconsistent help-texts

---

collector/os_release.go
collector/os_release_test.go

os_release.go: Added support end parsing support.

---

collector/zfs_freebsd.go

When the zfs collector fails on FreeBSD it doesn't log which `mib` triggered the issue. This makes diagnostics harder.
Incompatibilities in the list of supported mibs is not uncommon with major os updates. By adding this change, it'll be easier for users to report the specific mib that is triggering the failure.
Related to #2847

zfs: Log mib when sysctl read fails on FreeBSD

---

collector/fibrechannel_linux.go
collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar

fixes https://github.com/prometheus/node_exporter/issues/2919
needs https://github.com/prometheus/procfs/pull/607: MERGED

fibre_channel: update procfs to take into account optional attributes

---

collector/os_release.go

os_release.go: Removed caching of modtime/filename of os-release file

---

collector/netclass_linux.go

fix data race issue:
```
fatal error: concurrent map read and map write
goroutine 420 [running]:
github.com/prometheus/node_exporter/collector.(*netClassCollector).getFieldDesc(0xc0004f6f40, {0x1c87090, 0x8})
github.com/prometheus/node_exporter@v1.6.1/collector/netclass_linux.go:139 +0x49
github.com/prometheus/node_exporter/collector.(*netClassCollector).netClassSysfsUpdate(0xc0004f6f40, 0x493ad7?)
github.com/prometheus/node_exporter@v1.6.1/collector/netclass_linux.go:115 +0xc9e
github.com/prometheus/node_exporter/collector.(*netClassCollector).Update(0x223d72656e696174?, 0x6e6567612d676f6c?)
github.com/prometheus/node_exporter@v1.6.1/collector/netclass_linux.go:71 +0x36
github.com/prometheus/node_exporter/collector.execute({0x1c872e0, 0x8}, {0x1f93920, 0xc0004f6f40}, 0x313734622d366530?, …
```

fix: data race of NetClassCollector metrics initialization when multiple requests happen

---

collector/watchdog_test.go

Ensure identical build flags embedded in both files.
golangci-lint and tests both failed when run on macos with the following error:
```
collector/watchdog_test.go:72:12: undefined: NewWatchdogCollector
```

Fix watchdog_test lint and test failures on macos.

---

collector/ethtool_linux.go

Add logging for ethtool device include/exclude and metrics include flags

---

.circleci/config.yml
Makefile.common

Alright, since I seem to have butchered my previous PR (see https://github.com/prometheus/node_exporter/pull/2916) beyond recovery with force pushes, I decided to open a new one that looks more sane.
Prevents SIGKILL issues on macs.
Fixes: https://github.com/prometheus/node_exporter/issues/2539, https://github.com/prometheus/node_exporter/issues/2217
I previously tested the darwin build that came out, and it ran well on my M1 mac, so this should be good to go.

Sign node exporter darwin binary with rcodesign

---

collector/cpu_solaris.go

Replace all `cpu_ticks_*` with `cpu_nsec_*`, since the former was off my a magnitude of `10e6`, and showed incorrect values for `node_cpu_seconds_total`.
Fixes: #1837

collector/cpu: `s/cpu_ticks*/cpu_nsec*` for solaris

---

collector/fixtures/proc/pressure/cpu
collector/pressure_linux.go

Check that the PSI metrics are returned in order to avoid nil pointer dereference.
Fixes: https://github.com/prometheus/node_exporter/issues/3015

Fix pressure collector nil reference

---

README.md
collector/slabinfo_linux.go

Add filter flags to the slab collector to allow reduced cardinality.

slabinfo: Add filters for slab name.

---

collector/btrfs_linux_test.go
collector/diskstats_linux_test.go
collector/ethtool_linux_test.go

Running `go test` in the collector directory, without the fixtures available, results in multiple panics, including `SIGSEGV`. Most of these are due to incorrect error handling. This cleans them up.

Do not panic as much in Linux collector tests

---

collector/pressure_linux.go

fix #3051
allow only some for CPU.

fix pressure metric collection fails on systems that do not expose a full CPU stat

---

collector/fibrechannel_linux.go
collector/mountstats_linux.go
collector/utils/utils.go
go.mod
go.sum

Needed-for: https://github.com/prometheus/node_exporter/pull/3032
***
`v0.15.1` introduced some breaking changes. This patch addresses those.

chore: sync with latest `procfs` release

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/proc/pressure/irq
collector/pressure_linux.go

Add IRQ PSI metrics.
Fixes: https://github.com/prometheus/node_exporter/issues/2902

collector/pressure: add IRQ PSI metrics

---

README.md

This pull request updates the `README.md` file to correct the spacing in the **EXPERIMENTAL** label within the "TLS endpoint" section. The previous version had extra spaces around the word, which have been removed for consistency.
The term **EXPERIMENTAL** was previously formatted with extra spaces (** EXPERIMENTAL **), which was inconsistent with the rest of the document's formatting. Removing the extra spaces improves the readability and consistency of the documentation.
- Updated the `README.md` file to change ** EXPERIMENTAL ** to **EXPERIMENTAL**.
- None
Please review the changes and let me know if any modifications are needed.

Fix: Correct spacing in EXPERIMENTAL label in README.md

---

README.md
collector/hwmon_linux.go

Fixes #2242
This commit adds two new flags (`collector.hwmon.sensor-include` and `collector.hwmon.sensor-exclude`) to the `hwmon` collector to allow inclusion or exclusion of specific sensors.
Some devices export nonsensical values for certain sensors. Here is an example:
```
node_hwmon_temp_celsius{chip="platform_nct6775_656",sensor="temp13"} 49.75
node_hwmon_temp_celsius{chip="platform_nct6775_656",sensor="temp15"} 3.892313987e+06
node_hwmon_temp_celsius{chip="platform_nct6775_656",sensor="temp16"} 3.892313987e+06
```
As a user I would like to only exclude these sensors, not necessarily the complete device (as is currently possible with the `--collector.hwmon.chip-exclude` flag) as other sensor values might be sensical or desired.
The new option filters based both on device name and …

Add include and exclude filter for sensors in hwmon collector

---

docs/node-mixin/dashboards/node.libsonnet
docs/node-mixin/dashboards/use.libsonnet
docs/node-mixin/lib/prom-mixin.libsonnet

Automatically add a uid to each dashboard. This prevents changing URLs when restarting a grafana pod and re-importing the dashboards via ConfigMaps.

Add UIDs to dashboards

---

collector/collector.go
collector/meminfo.go
collector/meminfo_darwin.go
collector/meminfo_linux.go
collector/meminfo_linux_test.go
collector/meminfo_netbsd.go
collector/meminfo_openbsd.go
collector/meminfo_openbsd_amd64.go

Part of #2957
Prometheus' procfs lib supports collecting memory info and we're using a
new enough version of the lib that has it available, so this converts
the meminfo collector for Linux to use data from procfs lib instead. The
bits I've touched for darwin/openbsd/netbsd are with intent to preserve
the original struct implementation/backwards compatibility.
Signed-off-by: TJ Hoplock <t.hoplock@gmail.com>

ref!: convert linux meminfo implementation to use procfs lib

---

README.md
collector/interrupts_common.go
collector/interrupts_linux.go
collector/interrupts_openbsd.go
collector/interrupts_openbsd_amd64.go

In order to reduce cardinality of the interrupts collector add filtering options
* Add include/exclude regexp filter flags.
* Add boolean flag to include zero values, enabled by default.

Add interrupts collector filtering

---

README.md
node_exporter.go

This PR adds an `exclude[]` URL parameter to exclude specific enabled collectors.
Compared to `collect[]` parameter, the `exclude[]` parameter results in a filtered list which equals enabled collectors minus excluded ones.

Add `exclude[]` parameter

---

examples/systemd/node_exporter.service

node_exporter has reasonable defaults so it is able to start without explicit config. Such a setup is common in /usr/-only images where /etc/ is an empty tmpfs upon boot.

Gracefully handle absence of environment configuration file

---

collector/cpu_aix.go
collector/diskstats_aix.go
collector/diskstats_common.go
collector/filesystem_aix.go
collector/filesystem_common.go
collector/loadavg.go
collector/loadavg_aix.go
collector/meminfo.go
collector/meminfo_aix.go
collector/netdev_aix.go
collector/netdev_common.go
collector/os_release.go
collector/uname.go
collector/uname_bsd.go
docs/node-mixin/dashboards/node.libsonnet
docs/node-mixin/lib/prom-mixin.libsonnet
go.mod
go.sum

This PR adds a basic set of AIX metrics, including a dashboard for the mixins:
Since adding tests is hard due to the unavailability of AIX test runners, I carefully manually verified the metrics: https://docs.google.com/document/d/1_9cPbLTNqrxIeTZ57ZbyVsgOurvzvEKy67GvSNSrOhk/edit?usp=sharing
Thanks to Grafana for sponsoring this work!

Add AIX support

---

collector/textfile.go
collector/textfile_test.go

We already support reading from multiple directories though only using globs. Now we can specify them outright.
Example use case is exporting both static info on a RO FS generated during image building and traditional uses of textfiles (e.g. for R/W service metrics files) without scripting a file copy.
* keep flag name for compatibility
* clarify flag help text
* add test case (replicating the glob one)

textfile: Allow specifiying multiple directory globs.

---

README.md
collector/filesystem_aix.go
collector/filesystem_bsd.go
collector/filesystem_common.go
collector/filesystem_freebsd.go
collector/filesystem_linux.go
collector/filesystem_netbsd.go
collector/filesystem_openbsd.go

Add support for allow lists of filesystem mount points and filesystem types. This allows for less messy regexps when you want to target only specific lists of mount points or filesystem types.

Add filesystem include flags

---

docs/node-mixin/alerts/alerts.libsonnet

Hello, 
This PR removes iowait from the NodeCPUHighUsage alert. Similar change was done in #2194. In my opinion there's no reason why it shouldn't be changed here as well. I'm not sure if it makes sense to keep steal in here but I'm open to someone else to chime in.

Exclude iowait from NodeCPUHighUsage alert

---

docs/node-mixin/alerts/alerts.libsonnet
docs/node-mixin/config.libsonnet

Adding a config option:
```
// Some of the alerts use predict_linear() to fire alerts ahead of time to
// prevent unrecoverable situations (eg. no more disk space). However, the
// node may have automatic processes (cronjobs) in place to prevent that
// within a certain time window, this may not align with the default time
// window of these alerts. This can cause these alerts to start flapping.
// By reducing the time window, the system gets more time to
// resolve this before problems occur.
```

fix(docs): add node(Warning|Critical)WindowHours to node-mixin

---

docs/node-mixin/alerts/alerts.libsonnet

The description of other alerts has the instance label, but the `NodeHighNumberConntrackEntriesUsed` alert does not have it.

chore: add the instance label to `NodeHighNumberConntrackEntriesUsed` alert description

---

collector/arp_linux.go

Go net package's net.InterfaceByIndex fetches the _entire_ interface table behind the scenes, despite us specifying the interface index that we are interested in. This results in an exponential amount of rtnetlink traffic (and thus `recvfrom` syscalls) as the number of interfaces in a host increases.
Fixes: #3075

arp: optimize interface name resolution

---

collector/uname.go

Rename `newUnameCollector` to `NewUnameCollector` in `collector/uname.go`.
* Export `NewUnameCollector` to make it accessible outside the package

Export newUnameCollector function in uname.go

---

collector/netstat_freebsd.go
collector/netstat_freebsd_test.go

I would like to extend network support for Prometheus node exporter on FreeBSD.
In this PR, I've added two counters to log the total TCP packets sent and received.
I hope everyone can discuss together whether this approach is feasible.

Add collector for netstats tcp packet counters for FreeBSD.

---

collector/diskstats_linux.go

Remove unused `queueDescs` value from diskstats collector.

Fix unused value

---

collector/ethtool_linux.go

ethtool only uses the device names from `NetClassDevices()`, not the whole NetClass data from `NetClass()`.
Improves ethtool collector performance on systems with lots of excluded devices.

collector/ethtool: skip full scan of NetClass directories

---

docs/node-mixin/dashboards/use.libsonnet

It looks like the changes made in #3147 introduced an invalid variable to the 2 cluster use dashboards, this PR removes them.
The invalid variable was most likely not caught since Grafana just removes it without complaining.
Culprit:
```
{
"datasource": {
"type": "prometheus",
"uid": "${datasource}"
},
"refresh": 2,
"sort": 1
}
```
Before:
```
"templating": {
"list": [
{
"name": "datasource",
"query": "prometheus",
"type": "datasource"
},
{
"datasource": {
"type": "prometheus",
"uid": "${datasource}"
},
"hide": 2,
"includeAll": false,
"name": "cluster",
"query": "label_values(node_time_seconds, cluster)",
"refresh": 2,
"sort": 1,
"type": "query"
},
{
"datasource": {
"type": "prometheus",
"uid": "${datasource}"
},
"refresh": 2,
"sort": 1
}
]
```
After:
```
"templating": {
"list": [
{ …
```

bugfix: [mixin] remove invalid variable from cluster use dashboards

---

collector/fixtures/e2e-64k-page-output.txt
collector/fixtures/e2e-output.txt
collector/fixtures/sys.ttar
collector/mdadm_linux.go
collector/mdadm_linux_test.go

Use `sysfs` for RAID stats. Also added tests for the collector.
Fixes: #842

collector/mdadm: Support RAID metrics

---

collector/filesystem_common.go
collector/filesystem_macos.go

This should fix issues reported with #3269 by using values rather than references while keeping the semantics of the original implementation.
@SuperQ , @discordianfish

Adressing potential memory leak introduced with the purgeable space reporting feature

---

collector/ethtool_linux.go

Fix S1009: should omit nil check; len() for nil maps is defined as zero (gosimple)

Fix linter warning

---

collector/fixtures/e2e-output-solaris.txt
end-to-end-test.sh

Ignore `node_cpu_frequency_max_hertz` to fix flaky Solaris end-to-end test.

Fix flaky Solaris test

---

collector/interrupts_openbsd_amd64.go
collector/utils/utils.go
collector/utils/utils_test.go

Sanitize zero terminated strings from OpenBSD device name parsing.
* Add byte-to-string util function.
Fixes: https://github.com/prometheus/node_exporter/issues/3287

Fix OpenBSD interrupt device parsing

---

collector/thermal_darwin.go

Use `utils.SafeBytesToString()` to sanitize C strings the Darwin thermal collector.

Sanitize darwin thermal strings

---

collector/diskstats_linux.go

As the comment says, this can be simplified now, as go 1.23 is required now.

diskstats: Simplify condition

---

collector/filesystem_macos.go

Fix macos filesystem collector memory leak introduced in #3206
- Properly free `C.CString`-allocated memory
- Fix memory leak of `fileURL`. Use autoreleasepool to manage memory and refactored the code a bit for better readability
closes #3314

Fix macos filesystem collector cgo memory leak

---

collector/ethtool_linux.go
collector/ethtool_linux_test.go
collector/fixtures/ethtool/eth0/statistics

The ethtool_linux looks for ethtool stats with their sanitized name which might be different from the name provisioned by ethtool.
This caused node-exporter to return a 0-value for sanitized metrics.
This patch works-around the missing key by copying ethtool stats to their sanitized name.

Fix ethtool returning 0 for sanitized metrics

---

collector/btrfs_linux.go
collector/cpu_linux.go
collector/cpu_netbsd.go
collector/ethtool_linux_test.go
collector/filesystem_linux.go
collector/meminfo_linux.go
collector/perf_linux_test.go
collector/systemd_linux_test.go
collector/zfs_linux.go
node_exporter.go

This should help prepare the repository for an upgrade of the commonly shared CI files to golangci-lint v2.

chore: Lint with golangci-lint v2

---

collector/systemd_linux.go

The same variable was used for timing every parallel operation.
I guess there isn't a test for this function.

Fix logging race in systemd_linux.go

---

collector/filesystem_macos.go
collector/meminfo_darwin.go

I noticed duplicate "C" import in a file when I was testing the exporter on my local laptop.

fix duplicate `cgo` import in macos filesystem
