node_exporter.go
=> Make flag names consistent across projects.

collector/diskstats.go
A followup to #44.
@juliusv @brian-brazil
=> Ignore floppy disk devices, due to it being 2015

CHANGELOG.md, Makefile, Makefile.COMMON
=> Use Makefile.COMMON and release version 0.8.0.

.travis.yml, README.md
Added travis automated build and build status on the READ.me file.
=> added travis automated build and status on the readme

README.md
=> Link Travis badge to Travis build status page.

collector/textfile.go
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/prometheus/node_exporter/58)
=> Switch protobuf import to its new github URL

collector/stat.go
by hardcoding `USER_HZ` (aka. `_SC_CLK_TCK`) to 100, which it is for all
platforms Go supports. See prometheus/node_exporter#52 for discussion around this too.
Closes prometheus/node_exporter#52.
=> remove cgo dependency

node_exporter.go
This fixes https://github.com/prometheus/node_exporter/issues/86
=> Make logging of collector executions less verbose.

collector/fixtures/megacli, collector/fixtures/megacli_disks.txt, collector/megacli.go, collector/megacli_test.go
Intel SSD do not report their temperature in MegaCLI output
Drive Temperature : N/A
=> Prevent crash when drive temperature is N/A

collector/time.go
Alternatively, you may just replace `%f` with `%d`.
=> Fix debug output

Makefile, Makefile.COMMON
Just putting this here. I guess you have a reason for not upping this yourselves so you are welcome to dismiss it. :smiley:
=> Changed Go version to 1.5.1

collector/runit.go
Closes prometheus/node_exporter#103
=> Add the time of the last service state change to runit collector

collector/mdadm_test.go, collector/megacli_test.go
Issue prometheus/node_exporter#95
=> Resolve go vet problems

collector/textfile.go
=> Move from client_golang/text to common/expfmt

collector/ntp.go
@juliusv @grobie Hi! I've add a patch(beevik/ntp@e4b381fc40a388d6768e30ea3153c7dbc226b7f8) that enables selecting of NTP protocol version. This PR will adds a flag with ntp protocol version to ntp collector.
=> Add NTP protocol version flag

node_exporter.go
@grobie and @discordianfish - First-time contributor here. Considered an update to the README as well, but it seems like additional documentation around securing exporters probably belongs on prometheus.io, rather than in the README.md
=> Closes #100 by removing support for HTTP basic auth

collector/ntp.go
The upstream library changed their interface - the global Version
variable is gone:
https://github.com/beevik/ntp/commit/283ed9d548825a1dae0994311560e8dbf8efac68
=> Fix protocol version setting in NTP collector.

node_exporter.go
Enabled by default collectors are chosen for Linux, which supports all
of the implemented collectors. But for other OSes (OS X, for example)
this list is not suitable, because they lack most of those collectors.
Because of that, it is not possible to run node_exporter with default
options on such OSes. Fix this by filtering list of enabled by default
collectors based on their availability for current platform.
Closes #149
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>
=> Filter list of collectors enabled by default

collector/stat_linux.go
=> Switch linux stat to using ConstMetric

README.md, collector/systemd_linux.go, collector/systemd_linux_test.go
Hi,
I wrote a basic systemd exporter a few weeks ago and saw that #173 requested one, so here is my code. Its main use is to detect failing services.
Feel free to comment :)
=> collector: add systemd services status

collector/fixtures/e2e-output.txt, collector/fixtures/sys/devices/system/node/node0/meminfo, collector/fixtures/sys/devices/system/node/node1/meminfo, collector/meminfo_numa_linux.go, collector/meminfo_numa_linux_test.go, end-to-end-test.sh
This pull request adds new per NUMA node memory statistics collector along with some tests for this new functionality.
=> Add new per NUMA node memory statistics collector

node_exporter.go
The option to write out a memory profile to file was removed in a730cff.
Declaring flags as local variable does not only result in cleaner, more
testable code, but also ensures that the program won't compile anymore
when unused flags are left in place.
@juliusv
=> Remove unused flag -debug.memprofile-file

collector/ntp.go
--ntpServer is actually -collector.ntp.server
=> Fix NTP server command line reference

collector/netdev_freebsd.go
Hey @matthiasr, @brian-brazil . I've been using node_exporter on a pfsense box, and it gave some negative readings. Using this patch, I could actually enjoy a few working graphs.
=> fix the uint conversion to strings

collector/ntp.go
This also updates vendoring for `github.com/beevik/ntp` to the latest
version that exposes more than just receive time.
=> Add NTP stratum to NTP collector.

README.md, collector/filefd_linux.go
Two tiny cleanups for the filefd collector.
=> filefd collector

collector/netstat_linux.go
Fixes https://github.com/prometheus/node_exporter/issues/280
=> Convert netstat collector to use ConstMetrics

collector/sockstat_linux.go
This suffers from the same concurrency bug as the netstat one:
https://github.com/prometheus/node_exporter/issues/280
=> Convert sockstat collector to use ConstMetrics

collector/meminfo_linux.go
This suffers from the same concurrency bug as the netstat one:
https://github.com/prometheus/node_exporter/issues/280
=> Convert meminfo collector to use ConstMetrics

collector/meminfo_bsd.go
This suffers from the same concurrency bug as the netstat one:
https://github.com/prometheus/node_exporter/issues/280
=> Convert BSD meminfo collector to use ConstMetrics

collector/systemd_linux.go, collector/systemd_linux_test.go
As discussed on the mailing list, and #276, this PR implements an `ignored-units` flag for the systemd collector.
Slightly WIP - I'd like to discuss if this is sufficient. The default ignore-list is a compilation of patterns I've seen in my environment that I'm not interested in, maybe there are others that should also be default-ignore? Also, a blacklist will become quite long, maybe a whitelist would be better? For my setup, `^.+.service$`, `^.+.socket$` and `^.+.mount$` is enough, which is a bit more concise that the current blacklist.
And then again, there are some that match those that I still don't want, such as the systemd-fsck and friends. So maybe both a white- and a blacklist?
Additionally, there are five possible states, of which `activating` and `deactivating` are quite …
=> Add ignored-units flag for systemd collector

README.md, collector/meminfo_bsd.go
Snagging the low-hanging fruit
=> Compile meminfo for dfly

AUTHORS.md, vendor/github.com/prometheus/procfs/AUTHORS.md, vendor/github.com/prometheus/procfs/mountstats.go, vendor/github.com/prometheus/procfs/proc.go, vendor/github.com/prometheus/procfs/proc_limits.go, vendor/vendor.json
Needed to begin work on a `mountstats` collector.
=> Update github.com/prometheus/procfs to latest revision

Makefile, end-to-end-test.sh
=> Add e2e tests makefile

collector/netdev_linux.go
=> Check for errors in netdev scanner

collector/cpu_freebsd.go
Corrects an incorrect merge in 8e50b80
=> Fix build of cpu_freebsd.go

collector/fixtures/e2e-output.txt, collector/megacli.go, collector/textfile.go, end-to-end-test.sh, node_exporter.go, vendor/github.com/prometheus/client_golang/prometheus/counter.go, vendor/github.com/prometheus/client_golang/prometheus/desc.go, vendor/github.com/prometheus/client_golang/prometheus/doc.go, vendor/github.com/prometheus/client_golang/prometheus/gauge.go, vendor/github.com/prometheus/client_golang/prometheus/go_collector.go, vendor/github.com/prometheus/client_golang/prometheus/http.go, vendor/github.com/prometheus/client_golang/prometheus/process_collector.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go, vendor/github.com/prometheus/client_golang/prometheus/registry.go, vendor/github.com/prometheus/client_golang/prometheus/summary.go, vendor/github.com/prometheus/client_golang/prometheus/untyped.go, vendor/github.com/prometheus/client_golang/prometheus/value.go, vendor/vendor.json
=> Use promhttp and setup logger

example.rules
Add some useful examples for CPU metrics.
=> Add an example rules file

collector/ipvs_linux_test.go
=> Fix two staticcheck issues in IPVS collector tests

vendor/github.com/prometheus/procfs/README.md, vendor/github.com/prometheus/procfs/buddyinfo.go, vendor/github.com/prometheus/procfs/fs.go, vendor/github.com/prometheus/procfs/mountstats.go, vendor/github.com/prometheus/procfs/xfs/parse.go, vendor/github.com/prometheus/procfs/xfs/xfs.go, vendor/vendor.json
For #454, #456, and a couple of typos in mountstats.
=> Update vendored procfs for buddyinfo, mountstats, and XFS changes

text_collector_examples/ntpd_metrics.py
Add some metrics using to the ntpd helper script using the "request
value"[0] command.
[0]: https://www.eecis.udel.edu/~mills/ntp/html/ntpq.html#system
=> Add ntpd metrics from ntpq rv

collector/diskstats_linux.go, collector/filefd_linux.go, collector/interrupts_linux.go, collector/meminfo_linux.go, collector/meminfo_numa_linux.go, collector/netdev_linux.go, collector/netdev_linux_test.go, collector/netstat_linux.go, collector/sockstat_linux.go, collector/zfs.go
Using gosimple and unconvert.
@mdlayher @dominikh
=> Simplify go code

README.md, collector/mountstats_linux.go, collector/nfs_linux.go, collector/systemd_linux_test.go
=> Add goreportcard

collector/edac_linux.go, collector/helper.go, collector/hwmon_linux.go, collector/ipvs_linux_test.go, collector/zfs.go
@discordianfish @mdlayher @dominikh
=> Delete unused code

vendor/github.com/mdlayher/wifi/client_linux.go, vendor/vendor.json
Fixes #486 .
/r @grobie
/cc @cumulus-drew
=> Bump github.com/mdlayher/wifi to fix #486

collector/wifi_linux.go
=> Unexport wifiCollector metrics

collector/fixtures/e2e-output.txt, collector/fixtures/wifi/interfaces.json, collector/wifi_linux.go
This should provide basic support for devices operating in AP or ad-hoc mode.
=> Expand wifi collector for more interface types

Makefile, circle.yml, test_image.sh
Fix #358 
Avoid pushing broken images (similar to #353)
=> Test docker image before pushing

collector/devstat_dragonfly.go
Undefined err:
https://github.com/prometheus/node_exporter/commit/84eaa8fecd511b5aacb9de5440fdec9c713761bd#diff-c1429b1ed3eddf76a9420fbbb51846dd
=> Fixes broken build on Dragonfly.

vendor/github.com/prometheus/procfs/ipvs.go, vendor/vendor.json
Fix IPVS ipv6 parsing, see also prometheus/procfs#40
=> Update github.com/prometheus/procfs dependency

node_exporter_test.go
=> Log response body if test fails.

test_image.sh
- added a cleanup step after the container was started and the metrics were scraped with curl.
- fixed some minor indentation issues
=> Resolves prometheus/node_exporter#585

.github/ISSUE_TEMPLATE.md
Request the command line flags to the exporter.
=> Add additional field to github issue template.

node_exporter_test.go
These tests are failing on slow machines due to the fixed 100ms sleep. Moreover, depending on how you are building, the binary cannot be found in the CWD.
=> Fix path and timing issues with integration tests.

Makefile
Try to determine the corresponding 32bit architecture from the current
GOARCH and run the tests under that architecture. This only works on a
GOOS/GOARCH that can execute binaries for the smaller architecture, such
as running linux/386 binaries under linux/amd64.
I tested that this works under linux/amd64 and darwin/amd64, the rest of
the architectures is guesswork.
While we still only run regular tests on Intel/Linux architectures, this
covers general integer overflow issues like #629.
=> Automatically cross-test 32bit based on GOARCH

README.md
[![Buildkite status](https://badge.buildkite.com/94a0c1fb00b1f46883219c256efe9ce01d63b6505f3a942f9b.svg)](https://buildkite.com/prometheus/node-exporter)
=> Add buildkite status badge.

text_collector_examples/apt.sh
* Add metric for pending upgrades.
* Add metric for pending reboot required.
=> Add text file helper for apt-get.

README.md
=> add rslave for docker example

node_exporter_test.go
=> Remove unnecessary select statement

circle.yml, collector/fixtures/e2e-output.txt, collector/netdev_common.go
Ensure end-to-end test is run.
Closes: https://github.com/prometheus/node_exporter/issues/760
=> Add full make to CircleCI

vendor/github.com/ema/qdisc/get.go, vendor/vendor.json
Depends on https://github.com/ema/qdisc/pull/2, fixes #777.
=> Fix panic by updating github.com/ema/qdisc dependency

collector/fixtures/e2e-ppc64le-output.txt, end-to-end-test.sh
* Add support for per-architecture fixtures.
* Add output for ppc64le.
=> Add fixture for ppc64le

collector/sysctl_bsd.go
=> Remove unsafe typecasts from sysctl_bsd getStructTimeval.

collector/cpu_openbsd.go
=> Use unified CPU metric description on OpenBSD

collector/filesystem_linux.go
=> Fix log level regression in #533

collector/fixtures/e2e-output.txt, collector/nfsd_linux.go
RPC Count should be a counter, not a gauge.
=> Fix NFSd metric type

collector/time.go, docs/TIME.md
=> Add _seconds suffix to node_time.

collector/nfs_linux.go, vendor/github.com/prometheus/procfs/fs.go, vendor/github.com/prometheus/procfs/nfs/parse.go, vendor/github.com/prometheus/procfs/nfs/parse_nfs.go, vendor/vendor.json
Use new procfs library to parse NFS client stats.
Closes: https://github.com/prometheus/node_exporter/issues/786
=> Refactor NFS client collector

README.md
Add missing documentation about the `nfsd` collector.
Closes: https://github.com/prometheus/node_exporter/issues/820
=> Update README with nfsd collector.

vendor/github.com/coreos/go-systemd/NOTICE, vendor/github.com/coreos/go-systemd/dbus/dbus.go, vendor/github.com/coreos/go-systemd/dbus/methods.go, vendor/github.com/coreos/go-systemd/dbus/subscription.go, vendor/github.com/golang/protobuf/proto/discard.go, vendor/github.com/prometheus/client_golang/prometheus/doc.go, vendor/github.com/prometheus/client_golang/prometheus/http.go, vendor/github.com/prometheus/client_golang/prometheus/process_collector.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go, vendor/github.com/prometheus/client_golang/prometheus/registry.go, vendor/golang.org/x/crypto/ssh/terminal/util_windows.go, vendor/golang.org/x/sys/unix/affinity_linux.go, vendor/golang.org/x/sys/unix/mksyscall.pl, vendor/golang.org/x/sys/unix/syscall_darwin.go, vendor/golang.org/x/sys/unix/syscall_dragonfly.go, vendor/golang.org/x/sys/unix/syscall_freebsd.go, vendor/golang.org/x/sys/unix/syscall_linux.go, vendor/golang.org/x/sys/unix/syscall_linux_gc.go, vendor/golang.org/x/sys/unix/syscall_netbsd.go, vendor/golang.org/x/sys/unix/syscall_openbsd.go, vendor/golang.org/x/sys/unix/syscall_solaris.go, vendor/golang.org/x/sys/unix/syscall_unix.go, vendor/vendor.json
* Update vendor golang.org/x/...
* Update vendor github.com/prometheus/...
* Update vendor github.com/golang/protobuf/proto@v1.0.0
* Update vendor github.com/coreos/go-systemd/dbus@v16
=> Update vendor before 0.16.0

collector/fixtures/e2e-ppc64le-output.txt
Updates fixture for ppc64le arch to latest output.
=> Update ppc64le fixture

circle.yml
* Use go 1.10
* Use latest aktau/github-release
=> Update Circle CI

text_collector_examples/README.md
Document how to use `sponge` to atomic update textfiles.
=> Document use of atomic wrapper

README.md, collector/bcache_linux.go, collector/exec_bsd.go, collector/fixtures/e2e-output.txt, collector/fixtures/e2e-ppc64le-output.txt, collector/supervisord.go
`codespell` can be found here: https://github.com/lucasdemarchi/codespell
Signed-off-by: Karsten Weiss <knweiss@gmail.com>
=> Fix spelling mistakes found by codespell

.circleci/config.yml
=> Add codespell to circleci.

collector/fixtures/e2e-ppc64le-output.txt, collector/netdev_linux.go
=> Fix formatting.

CONTRIBUTING.md
=> Document DCO in CONTRIBUTING.md

collector/fixtures/e2e-ppc64le-output.txt
=> Update ppc64le end-to-end fixture.

CHANGELOG.md, docs/V0_16_UPGRADE_GUIDE.md, docs/example-16-compatibility-rules.yml
* Add an upgrade guide.
* Add an example recording rules.
=> Document upgrade options for v0.16.0

docs/example-16-compatibility-rules.yml
Signed-off-by: Nicholas Capo <nicholas.capo@gmail.com>
=> docs: Add example recording rule for node_memory_MemAvailable

example-rules.yml, example.rules
* Remove Prometheus 1.x example file.
* Update CPU rules for 0.16.0.
=> Update example rules

Makefile, Makefile.common
#916
Hope it will be helpful. Please fill free to comment.
=> Add Makefile.common

vendor/github.com/mdlayher/wifi/client_linux.go, vendor/vendor.json
Fixes an RSSI calculation issue in my package.
=> vendor: bump github.com/mdlayher/wifi

collector/filesystem_linux.go, collector/filesystem_linux_test.go, collector/fixtures/proc/mounts
=> Adding support for evaluating octal characters in mountpoint

README.md
Closes: https://github.com/prometheus/node_exporter/issues/835
=> Add note about SYS_TIME capability for Docker.

collector/ntp.go
Make the ntp collector thread safe by wrapping a mutex lock around the
leapMidnight variable.
Fixes: https://github.com/prometheus/node_exporter/issues/1013
=> Fix ntp collector thread safety

collector/systemd_linux.go
Signed-off-by: Julius Volz <julius.volz@gmail.com>
=> systemd: Remove unneeded/unhandled error returns

Dockerfile
=> Using the recommended syntax for maintainer label

vendor/github.com/mattn/go-xmlrpc/xmlrpc.go, vendor/vendor.json
Closes https://github.com/prometheus/node_exporter/issues/1070
=> Update dependency mattn/go-xmlrpc

.promu-no-cgo.yml
=> Add ppc64 build.

.promu-no-cgo.yml
Closes: https://github.com/prometheus/node_exporter/issues/469
=> Add linux/s390x build

Makefile
=> Makefile: add target for checking Prometheus rules

text_collector_examples/storcli.py
Some enhancements for the storcli.py example script:
- Remove external dependencies of IntNum and dateutil
- Strip strings with whitespaces
- Parse to float to find issues with JSON parsing
- Add card temperatures
- Report which DG a PD belongs to
- Fix bug in BBU health detection
=> textfile example storcli enhancements

node_exporter.go
In order to avoid stuck collectors using up all system resources, add a
limit to the number of parallel in-flight scrape requests. This will
return a 503 error.
Default to 40 requests, this seems like a reasonable number based on:
* Two Prometheus servers scraping every 15 seconds.
* Failing scrapes after 5 minutes of stuckness.
Closes: https://github.com/prometheus/node_exporter/issues/244
=> Add a limit to the number of in-flight requests

collector/meminfo_darwin.go
=> update to host_statistics64 for Darwin meminfo

Makefile.common
See related PR https://github.com/prometheus/prometheus/pull/4918
=> Makefile.common: fix format rule

Makefile.common
=> Makefile.common: fix promu download path for arm32

text_collector_examples/btrfs_stats.py
=> Add a sample btrfs stats collection script

text_collector_examples/smartmon.sh
Update metrics following SMART attributes in [1][2]
- Seek_Error_Rate - ID: 7
- Reallocated_Event_Count - ID: 196
[1] https://en.wikipedia.org/wiki/S.M.A.R.T.#Known_ATA_S.M.A.R.T._attributes
[2] https://en.wikibooks.org/wiki/Minimizing_Hard_Disk_Drive_Failure_and_Data_Loss/Self-Monitoring,_Analysis,_and_Reporting_Technology
=> Add S.M.A.R.T metrics

CHANGELOG.md, README.md, collector/diskstats_common.go, collector/diskstats_darwin.go, collector/diskstats_linux.go, collector/diskstats_openbsd.go
Tested on i386 and amd64, OpenBSD 6.4 and -current.
Signed-off-by: Ralf Horstmann <ralf+github@ackstorm.de>
=> Add diskstats collector for OpenBSD

text_collector_examples/smartmon.py
Tested with Linux and FreeBSD. Untested with SAS devices.
solves #1217
=> Translate smartmon.py to Python

text_collector_examples/smartmon.py
- Sorted imports
- Added `self_test_re` regex to match output of `smart_ctl('--health', *device.smartctl_select())` in more broader way
- Added try...catch for `subprocess.run` to ignore exit status code of `smartctl` as it exits with non zero if any error occurs
What do you think?
=> Update smartmon.py to widen self_assessment_passed test

examples/openbsd-rc.d/node_exporter
node_exporter seems to work fine on OpenBSD, adding in an example rc.d script to control startup/shutdown of the daemon. Probably going to submit a pkg to the OpenBSD team too
=> OpenBSD rc.d script

README.md
=> README: Move pressure to enabled table

collector/processes_linux.go
=> log pid when there is a problem reading the process stats

CHANGELOG.md
* Fix ordering of CHANGE items by PR number.
* Add missing CHANGE for #1003
=> Fixup 0.17.0 changelog

go.mod, go.sum, vendor/github.com/prometheus/procfs/Makefile.common, vendor/github.com/prometheus/procfs/fixtures.ttar, vendor/github.com/prometheus/procfs/go.mod, vendor/github.com/prometheus/procfs/go.sum, vendor/github.com/prometheus/procfs/internal/fs/fs.go, vendor/github.com/prometheus/procfs/internal/util/valueparser.go, vendor/github.com/prometheus/procfs/mdstat.go, vendor/github.com/prometheus/procfs/mountinfo.go, vendor/github.com/prometheus/procfs/proc.go, vendor/github.com/prometheus/procfs/proc_environ.go, vendor/github.com/prometheus/procfs/proc_stat.go, vendor/github.com/prometheus/procfs/sysfs/class_infiniband.go, vendor/github.com/prometheus/procfs/sysfs/class_power_supply.go, vendor/modules.txt
procfs v0.0.3-0.20190620161747-f959769dfe3e is a requirement for
https://github.com/prometheus/node_exporter/pull/1357
=> Update procfs to v0.0.3-0.20190620161747-f959769dfe3e

collector/fixtures/e2e-64k-page-output.txt
Update for change in https://github.com/prometheus/node_exporter/pull/1224
=> Fix 64k page e2e fixture

text_collector_examples/storcli.py
Signed-off-by: Yosef Yudilevich <yosef.yudilevich@gmail.com>
@SuperQ , trying  again
=> fix for 'Celsius' spelling problem in storcli.py

collector/netdev_darwin.go
Fixes: https://github.com/prometheus/node_exporter/issues/1368
=> bugfix: avoid nil reference when ignore is nil in darwin

text_collector_examples/smartmon.sh
changed fields for disk write and read data of S.M.A.R.T
Signed-off-by: Bernd Müller <mueller@b1-systems.de>
=> changed fields for disk write and read data of S.M.A.R.T

docs/node-mixin/dashboards/use.libsonnet
- Normalize cluster memory utilisation.
- Fix missing `1m` in memory saturation.
- Have both disk-related row next to each other instead with the
network row in between.
- Correctly render transmit network traffic as negative, using
`seriesOverrides` and `min: null` for the y-axis.
- Make panel and row naming consistent.
- Remove legend where it would just display a single entry with
exactly the title of the panel.
- Fix metric name in individual node CPU Saturation panel.
- Break up disk space utilisation by device in the panel for an
individual node.
NB: All of that doesn't touch any of the more subtle issues captured in the
various TODOs.
@metalmatze
=> node-mixin: Fix various straight-forward issues in the USE dashboards

docs/node-mixin/dashboards/node.libsonnet
@metalmatze 
I found those mostly because I want to switch the kubernetes-mixin to pull in from the node-mixin. But of course we don't want to throw out recent improvements in the kubernetes-mixin.
=> More improvements for the node dashboard

docs/node-mixin/README.md
Following @discordianfish's suggestion
[here](https://github.com/prometheus/node_exporter/issues/1454#issuecomment-524225222).
Signed-off-by: beorn7 <beorn@grafana.com>
=> Node mixin: Clarify dashboard dependency on rules

collector/bcache_linux.go
=> collector: remove commented-out import from bcache collector

collector/drbd_linux.go
There were a lot of weird struct declaration styles and global state here, so I reworked it to be more idiomatic, reduce the mental overhead of the previous if/else blocks, and get rid of the global state.
=> collector: clean up DRBD collector, less global state

CHANGELOG.md, collector/cpu_linux.go, collector/fixtures/e2e-64k-page-output.txt, collector/fixtures/e2e-output.txt, collector/fixtures/proc/cpuinfo, end-to-end-test.sh
Adds topology and other information from /proc/cpuinfo
=> add node_cpu_info metric

docs/node-mixin/README.md
Two quick typo fixes in the README!
=> Two quick typo fixes

CHANGELOG.md, collector/cpufreq_linux.go, collector/fixtures/e2e-64k-page-output.txt, collector/fixtures/e2e-output.txt
Fixes #1510
Signed-off-by: John Belmonte <john@neggie.net>
=> fix typo in cpufreq metric names (#1510)

collector/filesystem_linux.go
Allow the user to specify a timeout for considering mounts stale. Previously this was set to a static 30s fairly arbitrarily. I lowered the default because I think it should be lower than the default scrape rate for prometheus so that a timeout doesn't cause a failed scrape. The reason I feel this should be adjustable is that it could be useful to change this value to better match a users scrape rate and the known load on a filesystem.
A couple scenarios that come to mind would be if an nfs mount goes stale and someone has a low scrape rate, say 5-10s, this means that there will be 3-6 failed scrapes from timing out. The user would probably rather set this timeout lower. Or the opposite, if a filesystem is known to be under heavy load at times, a user may not want to timeout quickly. …
=> Add a flag to adjust mount timeout

examples/init.d/node_exporter
Fix the grammar of an error message.
=> grammar fixes for examples/init.d

go.mod, go.sum, vendor/github.com/prometheus/procfs/CONTRIBUTING.md, vendor/github.com/prometheus/procfs/README.md, vendor/github.com/prometheus/procfs/cpuinfo.go, vendor/github.com/prometheus/procfs/fixtures.ttar, vendor/github.com/prometheus/procfs/go.mod, vendor/github.com/prometheus/procfs/go.sum, vendor/github.com/prometheus/procfs/internal/fs/fs.go, vendor/github.com/prometheus/procfs/internal/util/readfile.go, vendor/github.com/prometheus/procfs/internal/util/sysreadfile.go, vendor/github.com/prometheus/procfs/ipvs.go, vendor/github.com/prometheus/procfs/meminfo.go, vendor/github.com/prometheus/procfs/mountinfo.go, vendor/github.com/prometheus/procfs/net_dev.go, vendor/github.com/prometheus/procfs/proc.go, vendor/github.com/prometheus/procfs/proc_fdinfo.go, vendor/github.com/prometheus/procfs/proc_io.go, vendor/github.com/prometheus/procfs/proc_psi.go, vendor/github.com/prometheus/procfs/proc_stat.go, vendor/github.com/prometheus/procfs/proc_status.go, vendor/github.com/prometheus/procfs/stat.go, vendor/github.com/prometheus/procfs/sysfs/class_powercap.go, vendor/modules.txt
Update Prometheus procfs library to the latest release.
=> Bump procfs to v0.0.7

Makefile, collector/fixtures/sys.ttar
* Add makefile target to update sysfs fixtures.
* Use similar style for fixtures from procfs.
* Re-pack fixtures ttar file.
=> Add fixture update helper

collector/softnet_linux.go
Add missing update for new go-kit logging change.
=> Fix up softnet collector for go-kit change

.circleci/config.yml, .dockerignore, Makefile
Added changes to build  **s390x node_exporter** docker image. 
Please review changes.
=> Docker image for s390x

collector/netdev_common.go
=> netdev: clean zero-value assignments

collector/softnet_linux.go, go.mod, go.sum, vendor/github.com/prometheus/procfs/Makefile.common, vendor/github.com/prometheus/procfs/crypto.go, vendor/github.com/prometheus/procfs/fixtures.ttar, vendor/github.com/prometheus/procfs/loadavg.go, vendor/github.com/prometheus/procfs/net_conntrackstat.go, vendor/github.com/prometheus/procfs/net_softnet.go, vendor/github.com/prometheus/procfs/net_udp.go, vendor/github.com/prometheus/procfs/net_unix.go, vendor/github.com/prometheus/procfs/proc_status.go, vendor/github.com/prometheus/procfs/swaps.go, vendor/github.com/prometheus/procfs/sysfs/class_infiniband.go, vendor/github.com/prometheus/procfs/xfs/parse.go, vendor/github.com/prometheus/procfs/xfs/xfs.go, vendor/modules.txt
Bump to v0.0.10 procfs library.
=> Update to latest procfs library

collector/cpu_dragonfly.go, collector/cpu_linux.go, collector/interrupts_openbsd.go, collector/perf_linux.go
See also https://gist.github.com/evalphobia/caee1602969a640a4530
=> Use strconv.Itoa() instead of fmt.Sprintf()

collector/perf_linux.go
* Use `strconv.Itoa()` instead of `fmt.Sprintf()` for simple conversion.
* Eliminate copy-paste in collector setup.
=> Minor cleanup in perf collector

go.mod, go.sum, vendor/github.com/prometheus/procfs/.golangci.yml, vendor/github.com/prometheus/procfs/Makefile.common, vendor/github.com/prometheus/procfs/bcache/bcache.go, vendor/github.com/prometheus/procfs/bcache/get.go, vendor/github.com/prometheus/procfs/fixtures.ttar, vendor/github.com/prometheus/procfs/go.mod, vendor/github.com/prometheus/procfs/go.sum, vendor/github.com/prometheus/procfs/mountinfo.go, vendor/github.com/prometheus/procfs/net_softnet.go, vendor/github.com/prometheus/procfs/proc_fdinfo.go, vendor/github.com/prometheus/procfs/proc_maps.go, vendor/github.com/prometheus/procfs/proc_status.go, vendor/github.com/prometheus/procfs/sysfs/class_infiniband.go, vendor/github.com/prometheus/procfs/sysfs/net_class.go, vendor/modules.txt
Bump procfs to latest release.
Fixes: https://github.com/prometheus/node_exporter/issues/1625
Fixes: https://github.com/prometheus/node_exporter/issues/1634
=> Update procfs library

docs/node-mixin/alerts/alerts.libsonnet
More info https://deploy.live/blog/kubernetes-networking-problems-due-to-the-conntrack/
=> Add NodeHighNumberConntrackEntriesUsed

docs/node-mixin/alerts/alerts.libsonnet
=> [node-mixin] Add missing coma in alerts

docs/node-mixin/alerts/alerts.libsonnet
Introduced in #1480.
@paulfantom @DimitrijeManic
=> Fix sign error in `NodeClockSkewDetected`

docs/TIME.md
=> fix typo in TIME.md

collector/perf_linux.go, collector/perf_linux_test.go
Fixes #1648
Signed-off-by: Daniel Hodges <hodges.daniel.scott@gmail.com>
=> Fix initialization in perf collector when using multiple CPUs

.circleci/config.yml, .promu.yml
=> Update go to 1.14

.circleci/config.yml, .promu-cgo.yml, .promu.yml
=> Finish the update to go 1.14

https/README.md
=> https: Fix htpasswd command

https/README.md
=> Use our standard config doc format.

README.md
Repo is renamed and moved.
Signed-off-by: Calle Pettersson <calle@cape.nu>
=> Update windows_exporter reference

collector/udp_queues_linux.go
Signed-off-by: Karsten Weiss <knweiss@gmail.com>
=> udp_queues_linux.go: s/upd/udp/ in two error strings

CHANGELOG.md
Fixes: https://github.com/prometheus/node_exporter/issues/1759
=> Fix up node_md_disks changelog entry

https/tls_config.go
Closes: https://github.com/prometheus/node_exporter/issues/1785
=> better wording

collector/bcache_linux.go, end-to-end-test.sh
Fixes #1593
Signed-off-by: Aleksei Zakharov <zaharov@selectel.ru>
=> bcache: add priorityStats flag

collector/cpu_common.go, collector/cpu_dragonfly.go, collector/cpu_linux.go, collector/cpufreq_linux.go, collector/cpufreq_solaris.go, collector/fixtures/e2e-64k-page-output.txt, collector/fixtures/e2e-output.txt, collector/perf_linux_test.go
Signed-off-by: Julius Volz <julius.volz@gmail.com>
=> Fix capitalization of CPU acronym throughout

docs/node-mixin/alerts/alerts.libsonnet, docs/node-mixin/config.libsonnet
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
=> Configure 2 thresholds for NodeFilesystemAlmostOutOfSpace alert

.promu-cgo.yml, .promu.yml, node_exporter.go
=> Add a warning when node exporter runs as root

collector/netdev_bsd.go, collector/netdev_common.go, collector/netdev_darwin.go, collector/netdev_filter.go, collector/netdev_filter_test.go, collector/netdev_linux.go, collector/netdev_linux_test.go, collector/netdev_openbsd.go
It's just a simple refactorig to avoid code duplication.
=> Move ignore/accept to new netDevFilter struct

collector/netdev_openbsd_amd64.go
Use new filtering method from #1826
=> Update netdev OpenBSD amd64 filter

README.md
Related to https://github.com/prometheus/node_exporter/pull/1948
=> Mention the default listening port in the README.

collector/network_route_linux.go
* Use `device` label to match other `node_network_...` metics.
* Fix naming convention to match Promehteus best practices.
=> Fix network_route collector naming

collector/zfs_solaris.go
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>
=> Fix ineffassign issue

README.md
Took me ages to find this thing since there's literally nearly 100 other options that look almost the same.
https://github.com/prometheus/node_exporter/pull/1460#issuecomment-761816460 some other person wants this as well. :)
I'm not too fussed about the verbiage, happy to modify.
=> Mention `--collector.disable-defaults` in the README

collector/systemd_linux.go
=> Fix panix when using backwards compatible flags

docs/node-mixin/dashboards/node.libsonnet
this was a regression introduced in https://github.com/prometheus/node_exporter/pull/1995
fixes https://github.com/prometheus-operator/kube-prometheus/issues/1104
@beorn7 @discordianfish PTAL.
=> fix interval in graph panels of node dashboard

collector/hwmon_linux.go
Signed-off-by: kcx2366425574 <18279911430@163.com>
=> fix the uncorrect word

collector/collector.go
When /metrics is called for specific collectors, the collectors are
initialed every time. Which means that we spend a lot of time
re-initiating the same collectors again and again. Especially, some
collectors make the assumptions that that are initiated once - e.g.
systemd collector generates info message upon initiation.
=> Only initiate collectors once

CHANGELOG.md, collector/time.go
Add the time zone and offset in seconds.
Closes: https://github.com/prometheus/node_exporter/issues/2052
=> Add time zone offset metric

collector/meminfo_openbsd_amd64.go
=> Fix wrong value for OpenBSD memory buffer cache

docs/node-mixin/alerts/alerts.libsonnet
Add a new alert when fs.file-nr is close to fs.file-max
=> feat(rules): add NodeFileDescriptorLimit kernel exhaustion alert

collector/fixtures/e2e-output.txt, go.mod, go.sum
Pull in bug fix for noisy logging.
Fixes: https://github.com/prometheus/node_exporter/issues/2086
=> Bump prometheus/procfs library

go.mod, go.sum
Closes #2125
Signed-off-by: W. Andrew Denton <git@flying-snail.net>
=> mod: update safchain/ethtool dependency.

collector/fixtures/e2e-output.txt, collector/rapl_linux.go
fixes #2147
Signed-off-by: binjip978 <binjip978@gmail.com>
=> add path label to rapl collector

go.mod, go.sum
ethtool got its first release.
=> Upgrade ethtool library to v0.1.0

CHANGELOG.md, collector/thermal_darwin.go
Signed-off-by: Matt Oshry <matto@spatialinc.com>
=> Handle nil CPU thermal power status on M1

collector/fixtures/e2e-64k-page-output.txt
https://github.com/prometheus/node_exporter/issues/2243
=> delete duplicate items

.github/ISSUE_TEMPLATE.md
Point users at the community website.
=> Update issue template.

collector/ethtool_linux.go
Try to fix this issue : https://github.com/prometheus/node_exporter/issues/2288
Heavily inspired from : https://github.com/prometheus/node_exporter/pull/2267
=> ethtool_linux: add mutex around entries access

collector/helper.go, collector/lnstat_linux.go, collector/perf_linux.go, collector/systemd_linux.go, collector/systemd_linux_test.go
Signed-off-by: binjip978 <pdp.eleven11@gmail.com>
=> Fix staticcheck warnings on linux

docs/node-mixin/alerts/alerts.libsonnet
Currently critical alert for space available alerts on warning and
warning alert for space available alerts on critical.
=> Reverse fsSpaceAvailableCriticalThreshold and fsSpaceAvailableWarningThreshold

docs/node-mixin/lib/prom-mixin.libsonnet
This mixin has aggregated graph with sum of all filesystems total/used bytes. I found it hard to track out of space problems if you have more than one mountpoint. 
Summing up is also a bit confusing sometimes, for instance it shows 6TB in total for my 1TB mac.
This PR replaces filesystem aggregated graph to table that shows the output similar to `df -h` command with stats for each mount point:
Mac:
Linux:
Only two metrics are queried, the rest is calculated via Grafana transform feature.
=> mixin: Change disk graph to disk table

Makefile
=> Check 64k-page e2e fixtures

collector/os_release_test.go
Signed-off-by: Cosrider [cosrider7@gmail.com](mailto:cosrider7@gmail.com)
=> add file descriptor close safely in test

.circleci/config.yml, CHANGELOG.md, collector/fibrechannel_linux.go, node_exporter.go, scripts/codespell_ignore.txt
* Fix some mistakes
* Switch to an ignore file.
=> Fixup codespell

collector/zfs_linux.go
Resolves  #2068
Signed-off-by: tnextday <fw2k4@163.com>
=> Skip over the zfs IO metrics if their paths are missing

collector/diskstats_common.go
Correctly handle the new `collector.diskstats.device-exclude` flag to avoid errors when using the old `collector.diskstats.ignored-devices` flag.
Fixes: https://github.com/prometheus/node_exporter/issues/2486
=> Fix diskstats exclude flags

.github/ISSUE_TEMPLATE.md
Signed-off-by: Yury Vidineev <adeptg@gmail.com>
=> fix the docker link in the ISSUE_TEMPLATE

collector/thermal_zone_linux.go
Add a check for missing/unreadable thermal zone stats and ignore if not availlable.
Fixes: https://github.com/prometheus/node_exporter/issues/2552
=> Fix thermal_zone collector noise

collector/uname.go, collector/uname_bsd.go
This collector works just fine without any further changes.
=> Enable uname collector on NetBSD too

go.mod, go.sum
Pick up the fixes for 32-bit mode and updated HTML template.
=> Bump exporter-toolkit

CHANGELOG.md, README.md
=> Fix spelling issues

README.md
- doc
- Added undocumented include and exclude flags to `README.md`
=> doc: added undocumented include and exclude flags

README.md, collector/runit.go, go.mod, go.sum
=> Use go-runit fork, mark collector as deprecated

collector/device_filter.go
fix comment and remove redundant parentheses
=> fix(collector): fix comment and remove redundant parentheses

collector/fixtures/e2e-64k-page-output.txt, collector/fixtures/e2e-output.txt
Fix up correct e2e output for node_power_supply_info.
=> Update e2e output fixtures

CHANGELOG.md
fix issue in https://github.com/prometheus/node_exporter/issues/2714 for typo in CHANGELOG.md
=> fix misspell in CHANGELOG.md

go.mod, go.sum
=> Bump ethtool library

README.md
=> Add missing ethtool flag documentation

collector/qdisc_linux.go, end-to-end-test.sh
attempt to correct collector qdisc flags as noted in https://github.com/prometheus/node_exporter/issues/2781
=> fix(qdisc) flag naming corrected for consistency

.circleci/config.yml, .promu-cgo.yml, .promu.yml
* Update Go build to 1.21.
* Update machine images to Ubuntu 22.04 current.
=> Update to Go 1.21

collector/zfs_freebsd.go
Fixes https://github.com/prometheus/node_exporter/issues/2819
=> Fix inconsistent variable name, to address compilation issue

collector/filesystem_linux.go
Reverts prometheus/node_exporter#2903
=> Revert "Fix filesystem mountTimeout not working issue"

docs/node-mixin/lib/prom-mixin.libsonnet
This PR adds multi-cluster support for the `Nodes` dashboard like `USE Method / Cluster` & `USE Method / Node` have.
=> Feat: Add multi-cluster support for Nodes dashboard

README.md, collector/fixtures/e2e-64k-page-output.txt, collector/fixtures/e2e-output.txt, collector/fixtures/sys.ttar, collector/watchdog.go, collector/watchdog_test.go, end-to-end-test.sh
Fixes #2309
Blocked by procfs release - to make use of prometheus/procfs#594
=> Add new collector and metrics for watchdog

collector/filesystem_netbsd.go
Sync dependencies and log using the machinery introduced in #3097.
=> fix: address `master` issues

collector/netdev_bsd.go
Fixes #3129 
Just a build fix for now. I can look at a more complete implementation later, just want to at least fix the build first.
=> build fix on FreeBSD

.golangci.yml, collector/cpufreq_linux.go, collector/interrupts_common.go, collector/runit.go, collector/selinux_linux.go, collector/softirqs_common.go, collector/uname.go
Enable `goimports` golangci-lint linter and fix issues.
=> Enable goimports linter

.github/workflows/bsd.yml, collector/fixtures/e2e-64k-page-output.txt, collector/fixtures/e2e-output-darwin.txt, collector/fixtures/e2e-output-dragonfly.txt, collector/fixtures/e2e-output-freebsd.txt, collector/fixtures/e2e-output-openbsd.txt, end-to-end-test.sh
Ignore non-deterministic metrics and include deterministic ones.
=> chore: ignore/include metrics for FreeBSD

README.md
Remove formatting that doesn't render properly.
=> Fixup README formatting

collector/pressure_linux.go
Fix "no data" error on kernels that support some PSI status, but don't yet have IRQ presure metrics. Only report "no data" error if `pressure` is enabled and no PSI metrics were found.
Fixes: https://github.com/prometheus/node_exporter/issues/3259
=> pressure: Fix missing IRQ on older kernels

collector/netdev_darwin.go
There is a bug in darwin kernel since macOS Ventura 13.2.1, which results in interface i/o bytes values to be truncated at 4GiB.
This change uses a workaround to collect the same metrics, taking advantage of another bug.
fixes #3333
=> fix: darwin netdev i/o bytes metric

docs/node-mixin/alerts/alerts.libsonnet
=> Fix NodeBondingDegraded alert
